### ISSUE TITLE
Add diagnostic information to webserver

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/blackbox_exporter#10]
It'd be handy if the details of the last ~10 probes to each target/module were available via the web UI so you could look at things like HTTP responses, rather than just having the metrics on the Prometheus side

**Comment by brian-brazil** [comment]
@tomwilkie Can you give me a pointer to your in-process Loki/opentracing stuff?

**Comment by tomwilkie** [comment]
Sure!  Its a bit rough right now, but its here: https://github.com/weaveworks-experiments/loki/pull/7

I don't plan on doing any more work on it until post promcon, but it should give yo what you need.
