### ISSUE TITLE
Incorrect Result for probe_http_ssl

### ISSUE THREAD

**Issue by tusharsonawanes** [prometheus/blackbox_exporter#1013]
Hi Team,

I am using the latest version of blackbox exporter (docker) version

In my prometheus scrape config, I have mentioned 3 http endpoints and 2 https endpoints. 

From what I am noticing, the result for the metric **probe_http_ssl** for the first **http** entry is **zero** and for the second **https** entry is **one**. The second scenario is working as expected. 

The first https entry redirects me to a different link, which also is https.

This is surprising because I want to use the metric for almost more than 50 entries. 

Can anyone help me with this issue? I have attached a reference screenshot for your reference in the link mentioned below

https://freeimage.host/i/HYnrNnI

**Comment by SuperQ** [comment]
Looking over the code, the ssl status is not updated until after all redirects are done. Are you sure the final redirect for that URL is https?

**Comment by tusharsonawanes** [comment]
Hi @SuperQ ,

Thanks for your reply. 

Yes, the final redirect is https.

**Comment by tusharsonawanes** [comment]
What is surprising is, both the https endpoints redirect to the same https login page, and also, the status code, which is given by the metric **probe_http_status_code** for the link with the issue is **0**. 

https://freeimage.host/i/HYIXy2R

**Comment by tusharsonawanes** [comment]
Okaye @SuperQ , from the logs, it is seen that for the link with the issue, the certificates that were provided were self signed. **x509: certificate signed by unknown authority**

So I believe that the code throws an error if the certificates are self signed also

For the second issue, I rechecked http_status_codes for both the urls (the hit and the redirected one) both return 200.
