### ISSUE TITLE
Question: Modify referrer of blackbox exporter

### ISSUE THREAD

**Issue by auwaerter** [prometheus/blackbox_exporter#1014]
### blackbox_exporter version: 0.23.0

A request from blackbox reporter looks like this in the access.log:

```bash
192.168.0.241 - - [19/Jan/2023:13:45:21 +0000] "GET /login HTTP/2.0" 200 35990 "-" "Blackbox Exporter/0.23.0" 65 0.006 [netprobe-80] [] 192.168.130.185:3000 36031 0.006 200 8450a7efbceaf9be58f936de6921b5f4
```
For this, i do have a general question: Is it possible to modfiy the referrer **Blackbox Exporter/0.23.0**?

**Comment by electron0zero** [comment]
You can set `User-Agent` Header in your http checks to change it, this is default user agent. 
See https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md#http_probe for more details.


For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
