### ISSUE TITLE
fail_if_body_not_matches_regexp didn't matches

### ISSUE THREAD

**Issue by balmajoe** [prometheus/blackbox_exporter#1027]
Hello I do a regex to check the body but I can't when I add an alphanumeric character. I have in my body AX/4.0.13 200 ok, If I put in my blackbox.yml
      fail_if_body_not_matches_regexp:
        -"AX/4.0.13"
return ok
but 
      fail_if_body_not_matches_regexp:
        - "AX/4.0.13 200"
msg="Body did not match regular expression" regexp="AX/4.0.13 200 ok"
Any ideas?

**Comment by dswarbrick** [comment]
Can you post the output of a probe with `&debug=true` appended to the scrape URL?

**Comment by electron0zero** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
