### ISSUE TITLE
how to change default interval check in http module which is 15s

### ISSUE THREAD

**Issue by pablozone** [prometheus/blackbox_exporter#1051]
Hello, how to change default interval check in http module which is 15s to for example 1min.
I don't see any options in http module config, there is only timeout.
Is it possible to change.?

**Comment by dswarbrick** [comment]
I think you want to change the `scrape_interval` in your Prometheus config's scrape job definition.

blackbox_exporter won't do anything until it is asked to by e.g. Prometheus requesting the `/probe?target=...` endpoint.

**Comment by pablozone** [comment]
Parametr scrape_interval in Prometheus config's scrape job definition doesn't change anything.  Blackbox exporter still will be check the http site every 15s (default value). I want to change this probe-interval to 1 minute.

![1](https://user-images.githubusercontent.com/29774180/229749298-6e791dfa-68ad-41c6-b494-120811f310da.jpg)

**Comment by dswarbrick** [comment]
@pablozone I can assure you that blackbox_exporter itself is completely passive, and will not probe anything until it is prompted to by Prometheus (or some other process) hitting e.g. `/probe?target=foo&module=bar`.

Be aware that Prometheus will stagger the probes of multiple targets over the entire `scrape_interval`, to avoid the "thundering herd" phenomenon.

**Comment by pablozone** [comment]
no response
