### ISSUE TITLE
HTTPS in container failing

### ISSUE THREAD

**Issue by StephanMeijer** [prometheus/blackbox_exporter#1065]
### Host operating system: output of `uname -a`

Container.

### blackbox_exporter version: output of `blackbox_exporter --version`

```
blackbox_exporter, version 0.23.0 (branch: HEAD, revision: 26fc98b9c6db21457653ed752f34d1b7fb5bba43)
  build user:       root@f360719453e3
  build date:       20221202-12:27:10
  go version:       go1.19.3
  platform:         linux/arm64
```

### What is the blackbox.yml module config.

See repository

### What is the prometheus.yml scrape config.

N/A

### What logging output did you get from adding `&debug=true` to the probe URL?

N/A

### What did you do that produced an error?

Shell into container,

```
/ # wget "https://google.com/"
Connecting to google.com (142.250.179.206:443)
wget: note: TLS certificate validation not implemented
Connecting to www.google.com (142.251.36.36:443)
saving to 'index.html'
index.html           100% |**************************************************************************************************************************************************************************************************************************************************************************************| 15350  0:00:00 ETA
'index.html' saved
```

```
/ # wget "https://overheid.nl/"
Connecting to overheid.nl (62.112.246.66:443)
wget: note: TLS certificate validation not implemented
Connecting to www.overheid.nl (62.112.246.70:443)
saving to 'index.html'
index.html           100% |**************************************************************************************************************************************************************************************************************************************************************************************| 15874  0:00:00 ETA
'index.html' saved
```

```
/ # wget "https://tweakers.net/"
Connecting to tweakers.net (213.239.154.30:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 40): handshake failure
wget: error getting response: Connection reset by peer
```

Failed connections seem to be around Let's Encrypt, but when I query `nginx.org`:

```
/ # wget "https://nginx.org/"
Connecting to nginx.org (3.125.197.172:443)
wget: note: TLS certificate validation not implemented
saving to 'index.html'
index.html           100% |**************************************************************************************************************************************************************************************************************************************************************************************|  7731  0:00:00 ETA
'index.html' saved
```

### What did you expect to see?

Established connections

### What did you see instead?

TLS failures

**Comment by StephanMeijer** [comment]
Same results in my amd64 container:

<img width="1141" alt="image" src="https://github.com/prometheus/blackbox_exporter/assets/3169264/b9f5f53a-ed1a-46ae-bc55-722fea0936bb">

**Comment by danteu** [comment]
The container image (see [Dockerfile](https://github.com/prometheus/blackbox_exporter/blob/master/Dockerfile)) uses a busybox image as base image, which contains a wget binary that seems to have been built w/o the certificate validation implementation.

```bash
$ docker run -it quay.io/prometheus/busybox-linux-amd64:latest wget
BusyBox v1.36.0 (2023-03-13 19:03:55 UTC) multi-call binary.
[...]
```

Why is the missing cert validation in wget a problem?

**Comment by danteu** [comment]
Seems that busybox-wget has problems w/ specific ciphers (see e.g., [here](http://lists.busybox.net/pipermail/busybox/2022-January/089412.html)). The current blackbox-exporter Docker image is based on an older prometheus-busybox image with busybox-wget v1.34.1. The current prometheus-busybox image ships with version 1.36.0 which does not seem to have this problem:

```bash
$ docker run -it --entrypoint sh quay.io/prometheus/busybox-linux-amd64:latest
/ # wget https://tweakers.net/
Connecting to tweakers.net (213.239.154.31:443)
wget: note: TLS certificate validation not implemented
saving to 'index.html'
index.html           100% |**************************************************************************************************|  238k  0:00:00 ETA
'index.html' saved
```
So the problem should be resolved with the next blackbox-exporter release.

**Comment by StephanMeijer** [comment]
Alright. I will aslo take a look at other images of Blackbox Exporter. Thanks for your assistance.
