### ISSUE TITLE
blackbox configuration scrape_interval failed

### ISSUE THREAD

**Issue by pablozone** [prometheus/blackbox_exporter#1071]
Hello, can you please tell me how to set scrape_interval to blackbox probe. I want check http site every 1 min, (not default 15s), but scrape_interval parametr doesn't change enything, I add data interval from grafana and my prometheus config .
I user prometheus 2.37.7, blackbox_exporter 0.23.0

prometheus config:
  - job_name: 'blackbox-http-csci-prod'
    scrape_interval: 60s
    scrape_timeout: 50s
    metrics_path: /blackbox/probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://ci-jenkins***********/login?from=%2F
        - https://ci-jenkins-***************l/login?from=%2F
        - https://ci-**************/login?from=%2F
        .
        .
        .
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__

2023-05-15 09:45:00
0.0624
2023-05-15 09:45:15
0.0624
2023-05-15 09:45:30
0.0527
2023-05-15 09:45:45
0.0527
2023-05-15 09:46:00
0.0527
2023-05-15 09:46:15
0.0527
2023-05-15 09:46:30
0.0465
2023-05-15 09:46:45
0.0465
2023-05-15 09:47:00
0.0465
2023-05-15 09:47:15
0.0465
2023-05-15 09:47:30
0.0465
2023-05-15 09:47:45
0.0465
2023-05-15 09:48:00
0.0465
2023-05-15 09:48:15
0.0465
2023-05-15 09:48:30
0.0467
2023-05-15 09:48:45
0.0467

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by pablozone** [comment]
Its not a question, ITS a BUG. Scape interval parametr with blackbox-exporter doesn't work property.

**Comment by pablozone** [comment]
please re-open this issue.

**Comment by pablozone** [comment]
Ok sorry for bother you, I use community channels and resolve problem
