### ISSUE TITLE
This is a new demand

### ISSUE THREAD

**Issue by Iatbzh** [prometheus/blackbox_exporter#1079]
### What did you expect to see?
I hope that blackbox can configure the address configured in Prometheus dialing test separately in blackbox, Prometheus to collect dialing data, because Prometheus collects a large amount of other data, every time you need to add blackbox test address, you need to restart Prometheus, I hope Prometheus directly collects blackbox dialing data

**Comment by electron0zero** [comment]
This question is unclear, for questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
