### ISSUE TITLE
url detection exception

### ISSUE THREAD

**Issue by 02darlingX** [prometheus/blackbox_exporter#1106]
Rencently, when i used blackbox_exporter and prometheus to monitor the url of our websites, a strange situation happened:
The website is heathy, but the trend of Grafana is abnormal(Sometimes, the value is 0).
The time span is about several minutes,so,this cannot simply be explained by network fluctuations.
Is it an exporter problem or a configuration problem？ how to solve this？help~~~

**Comment by candlerb** [comment]
First, take Grafana out of the equation. Have a look what queries Grafana is sending (e.g. "probe_success == 0") and enter these into the PromQL browser in the Prometheus web interface.

Then look at these results in the "graph" view. Do they show failures, i.e. times where probe_success == 0? Then the probe actually is failing.

Then it's up to you to determine why blackbox_exporter is unable to communicate with the target host intermittently. Maybe the web server really *is* unhealthy from time to time, but you're not noticing it.  Maybe you have a network problem. Maybe the host where blackbox_exporter is running is overloaded.  This is entirely a problem within your network, and you can use blackbox_exporter to give you clues as to where to look.

If you set debugging mode on blackbox_exporter (`--log.level=debug`) you'll get detailed logs where you can see the individual probes and what went wrong.

**Comment by electron0zero** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
