### ISSUE TITLE
Correct documentation

### ISSUE THREAD

**Issue by stratanic** [prometheus/blackbox_exporter#1109]
Hi , I just want correct the "[CONFIGURATION.md]"(https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md)

for the proxy , this line: 
Specifies headers to send to proxies during CONNECT requests.
  [ proxy_connect_header**s**:
    [ <string>: [<secret>, ...] ] ]

the correct syntax is wihout "s":

 proxy_connect_header:

**Comment by opencmit2** [comment]
Hi @stratanic 
I compared the blackbox_exporter/example.yml and blackbox_exporter/CONFIGURATION.md files, the proxy_connect_header is correct, I'm very happy to help modify it for you.

**Comment by electron0zero** [comment]
merged https://github.com/prometheus/blackbox_exporter/pull/1126
