### ISSUE TITLE
Support windows service installer

### ISSUE THREAD

**Issue by zhaojinxin409** [prometheus/blackbox_exporter#1123]
Since blackbox support running as a service on windows, is it possible to release a msi that install blackbox as service

**Comment by electron0zero** [comment]
Hi, I don't think we can offer msi builds for windows due to various reasons. however, we do offer prebuilt .exe for windows.

It would be hard for us to support this because majority users and maintainers of the blackbox_exporter use unix or gnu/linux systems.
