### ISSUE TITLE
Unexpected 403 when probing for 200

### ISSUE THREAD

**Issue by senemamourr** [prometheus/blackbox_exporter#1135]
### What is the blackbox.yml module config.
Module configuration:
prober: http
timeout: 5s
http:
  valid_status_codes:
  - 200
  preferred_ip_protocol: ip4
  ip_protocol_fallback: true
  method: GET
  headers:
    Sec-Fetch-Dest: documentsd
  fail_if_body_not_matches_regexp:
  - '{"status":"UP"}'
  follow_redirects: true
  enable_http2: true
tcp:
  ip_protocol_fallback: true
icmp:
  ip_protocol_fallback: true
  ttl: 64
dns:
  ip_protocol_fallback: true
  recursion_desired: true
### What logging output did you get from adding `&debug=true` to the probe URL?
msg="Received HTTP response" status_code=403
msg="Body did not match regular expression" regexp="{\"status\":\"UP\"}"
### What did you do that produced an error?
Probed for HTTP 200 or 403  using blackbox exporter. All other hosts work fine, this returns a 403 
 the output  curl -kIL gives status code 200
### What did you expect to see?
status code of 200
### What did you see instead?
status code 403

**Comment by electron0zero** [comment]
can you check if you are correctly passing the required auth credentials?

For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
