### ISSUE TITLE
Multi-ICMP probe

### ISSUE THREAD

**Issue by SuperQ** [prometheus/blackbox_exporter#115]
In order to provide a more smokeping-like experience, it would be nice to have an ICMP probe mode that sends out multiple packets and buckets the probe time in a histogram and counts lost packets.

**Comment by brian-brazil** [comment]
I'm not sure about this, why would it be limited to just ICMP?

Multiple scrapes from Prometheus could provide this for all modules.

**Comment by SuperQ** [comment]
My thinking is that ICMP is lighter-weight than most of the TCP-based probes.

**Comment by brian-brazil** [comment]
If we support it for one, we should support it for all.

Smokeping is the best smokeping.

**Comment by SuperQ** [comment]
Yea, thinking about this more, I think we're already doing better than smokeping with the right PromQL.

**Comment by RichiH** [comment]
Smokeping is an island of data and you end up doing checks twice, though.

Some guidance for @qybl as to what's needed would be appreciated as he can implement this on company time.

**Comment by SuperQ** [comment]
I had some ideas today about a better way to do smokeping-like stats.

Running Prometheus with a high scrape interval and using recording rules is OK, but I think there are better options.

What I'm thinking is not a Blackbox exporter, where the scrapes are scheduled by Prometheus, but a network prober that has its own scheduling and exports more like a normal target.

**Comment by RichiH** [comment]
Is there an inherent reason why this needs to be done in an extra system? I am not saying I am opposed, just wondering.

Can you re-open this ticket for now?

**Comment by brian-brazil** [comment]
I'd consider this out of scope for the blackbox exporter. A blackbox probe is on or off. Smokeping is gathering metrics across multiple probes.

**Comment by RichiH** [comment]
And smokeping looks at the Blackbox state of a system. Either way, if you
wouldn't merge this, doing it elsewhere is better.

Please give final no if that's the case.

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

**Comment by brian-brazil** [comment]
I don't see a way to have this make sense in the blackbox exporter, and I'm not even sure it works well within Prometheus. It's a specialised use case.

**Comment by SuperQ** [comment]
I think this is not a good fit for the blackbox exporter.  But I think something similar has some more useful potential for network probing. I'd be keen on chatting about it.

**Comment by RichiH** [comment]
To create a public log: @SuperQ and me keep mulling things on Hangouts and we are coming up with ideas for a network latency exporter.

**Comment by blackliner** [comment]
I know, couple of years late, but is there a 2025 version of this? Interested in detecting package drops, so ~10 pings per second would be nice 😬

**Comment by SuperQ** [comment]
See the smokeping_prober linked above.
