### ISSUE TITLE
Request for FIPS-Compliant Image

### ISSUE THREAD

**Issue by nehajaju** [prometheus/blackbox_exporter#1157]
### Issue Description:
We require a FIPS-compliant version of the Prometheus Blackbox Exporter for our security needs.

- Can you confirm the possibility of providing a FIPS-compliant version of the Prometheus Blackbox Exporter?
- If available, please provide information on how to obtain or configure the FIPS-compliant image.

**Comment by SuperQ** [comment]
The current images as linked in the README are what we provide.
