### ISSUE TITLE
dns_sd_configs

### ISSUE THREAD

**Issue by edouardkleinhans** [prometheus/blackbox_exporter#116]
Hello, 

Is it possible to use dns_sd_configs with this exporter ?

**Comment by brian-brazil** [comment]
Yes, you can use them on the Prometheus end just like any other SD.

**Comment by edouardkleinhans** [comment]
Ok, good, but i've an issue with relabel.

Do you have any sample ?

2017-02-27 11:26 GMT+01:00 Brian Brazil <notifications@github.com>:

**Comment by brian-brazil** [comment]
https://github.com/prometheus/blackbox_exporter#prometheus-configuration is the standard example.

**Comment by edouardkleinhans** [comment]
can you help me on 

replacement: 127.0.0.1:9115 

It doesn't work with dns-sd

**Comment by brian-brazil** [comment]
That won't, you need to know the IP or DNS name of the blackbox exporter. Usually you'd run it beside the Prometheus.
