### ISSUE TITLE
No status code for HTTP probe when DNS lookup fails

### ISSUE THREAD

**Issue by Malet** [prometheus/blackbox_exporter#117]
We had a site with downtime recently, the alerts did not trigger when expected as the DNS lookup failed in the exporter, but did not return a status code to prometheus.

> Error for HTTP request to http://foo.com: Get http://www.foo.com/: dial tcp4: lookup www.foo.com on 1.2.3.4:53: no such host" source="http.go:166

**Comment by brian-brazil** [comment]
The probe_success metric is the one you're intended to be alerting on, the status code is there to help debugging more than anything else.

**Comment by Malet** [comment]
@brian-brazil `probe_success` doesn't get returned either, it seems to completely break all metrics if the DNS lookup fails.
<img width="1030" alt="screen shot 2017-03-03 at 14 12 28" src="https://cloud.githubusercontent.com/assets/358505/23554087/86c868d0-001b-11e7-8bd4-d92a36071534.png">

**Comment by brian-brazil** [comment]
That's not possible in the code, are you timing out the scrape and getting an up of 0?

**Comment by Malet** [comment]
Ah, that'd be it, the http timeout we have set is larger than the prometheus timeout :man_facepalming:, that should fix it! Thank you!
