### ISSUE TITLE
packaged deb version of blackbox_exporter

### ISSUE THREAD

**Issue by vinay-keshava** [prometheus/blackbox_exporter#1179]
Hi, we are providing a packaged version of blackbox exporter deb for amd64
https://packages.deeproot.in/pool/main/b/blackboxexporter/

If you're interested, please include this in your repository for better reach.

Thanks
Vinay

**Comment by electron0zero** [comment]
Hi, we can only recommend official sources or building from source for supply chain security reasons.

however they are many other third part builds of blackbox_exporter, so please feel free to keep providing it.

fyi: the attached [link](https://packages.deeproot.in/pool/main/b/blackboxexporter/) is down and returning 502.
