### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by gburton1** [prometheus/blackbox_exporter#1194]
There are about 9 months of accumulated changes since the last release; it would be great to get a fresh release.

**Comment by mamccorm** [comment]
+1 to this. Any updates?

**Comment by derhuerst** [comment]
[`0.25.0` has been released on 2024-04-09](https://github.com/prometheus/blackbox_exporter/releases/tag/v0.25.0).

**Comment by electron0zero** [comment]
closing because [0.25.0](https://github.com/prometheus/blackbox_exporter/releases/tag/v0.25.0) was released after this issue was opened.
