### ISSUE TITLE
feature: regexp matching in the HTTP body

### ISSUE THREAD

**Issue by stapelberg** [prometheus/blackbox_exporter#12]
Before I send a pull request, I wanted to check whether the following feature would be accepted:

As a defence in depth mechanism, the [HTTP module in probers such as kanla](http://kanla.zekjur.net/docs/userguide.html#_body) supports checking whether the returned body matches a certain regular expression. That way, you can be alerted when the webserver still returns an HTTP 200, but all the application prints is “could not connect to database”. Obviously, applications should return proper HTTP status codes, but I still think it’s a nice feature to get some more confidence in your alerting, especially when you’re running applications that you did not write yourself.

What do you think?

**Comment by brian-brazil** [comment]
This is a feature I plan to have, with both positive and negative regexes. PRs accepted :)
