### ISSUE TITLE
TPC Prober only returns 0 values

### ISSUE THREAD

**Issue by xf0e** [prometheus/blackbox_exporter#1233]
### Host operating system: output of `uname -a`
Windows Server 21H2

### blackbox_exporter version: output of `blackbox_exporter --version`
0.25.0 / 2024-04-09

### What is the blackbox.yml module config.
standard

### What is the prometheus.yml scrape config.
 - job_name: 'blackbox'
    scrape_interval: 2s
    scrape_timeout: 2s
    metrics_path: /probe
    file_sd_configs:
     - files:
        - /etc/prometheus/blackbox/targets/*.yml
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*:_:(.*):_:.*:_:.*:_:.*'
        target_label: module
      - source_labels: [__address__]
        regex: '.*:_:.*:_:.*:_:(.*):_:.*'
        target_label: geohash
      - source_labels: [__address__]
        regex: '.*:_:.*:_:.*:_:.*:_:(.*)'
        target_label: instance
      - source_labels: [__address__]
        regex: '.*:_:.*:_:(.*):_:.*:_:.*'
        target_label: job
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [instance]
        target_label: __param_target
      - source_labels: [__address__]
        regex: '(.*):_:.*:_:.*:_:.*:_:.*'
        target_label: __address__

### What logging output did you get from adding `&debug=true` to the probe URL?
no change

### What did you expect to see?
If probe is succeeded, why where are only zeto values being returned?
This behaviour does not emerge vor all probes, but often (ca 20%). The same blackbox_exporter but for linux, which is configure for the same target doent have the same problem.

### What did you see instead?
This ist a log from the probe:
Logs for the probe:
ts=2024-04-15T08:35:16.794418Z caller=main.go:190 module=tcp_connect target=********:8471 level=info msg="Beginning probe" probe=tcp timeout_seconds=1.5
ts=2024-04-15T08:35:16.794418Z caller=tcp.go:40 module=tcp_connect target=********:8471 level=info msg="Resolving target address" target=********e ip_protocol=ip6
ts=2024-04-15T08:35:16.794418Z caller=tcp.go:40 module=tcp_connect target=********:8471 level=info msg="Resolved target address" target=******** ip=********
ts=2024-04-15T08:35:16.794418Z caller=tcp.go:112 module=tcp_connect target=********:8471 level=info msg="Dialing TCP without TLS"
ts=2024-04-15T08:35:16.794418Z caller=handler.go:119 module=tcp_connect target=********:8471 level=info msg="Successfully dialed"
ts=2024-04-15T08:35:16.794418Z caller=main.go:190 module=tcp_connect target=********:8471 level=info msg="Probe succeeded" duration_seconds=0

Metrics that would have been returned:
probe_dns_lookup_time_seconds 0
probe_duration_seconds 0
probe_failed_due_to_regex 0
probe_ip_addr_hash 3.130538077e+09
probe_ip_protocol 4
probe_success 1

**Comment by electron0zero** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
