### ISSUE TITLE
feature request: please sign your releases

### ISSUE THREAD

**Issue by udf2457** [prometheus/blackbox_exporter#1237]
It is easier than ever to do in 2024! You can even do it fully-automated via Github Actions, Github OIDC and [Sigstore "keyless" signing](https://docs.sigstore.dev/signing/overview/).

**Comment by udf2457** [comment]
Useful references:
https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#provenance-for-goreleaser
https://goreleaser.com/blog/slsa-generation-for-your-artifacts/#slsa-github-generator

**Comment by electron0zero** [comment]
Hi, it needs to be a prometheus org wide decision, and can't be done it just blackbox_exporter. please start a discussion on release signing in [community](https://prometheus.io/community/).

also see: 
> If you are concerned about the exact provenance of your binaries, it is recommended to build them yourself rather than relying on the pre-built binaries provided by the project.
> 
> from: https://prometheus.io/docs/operating/security/#build-process
