### ISSUE TITLE
For icmp_probe module  provide option to pass port number along with ipaddress

### ISSUE THREAD

**Issue by RakeshAMD** [prometheus/blackbox_exporter#1245]
How to pass port number along with ipaddress in the config file.

Some of the machines can be accessed via same ipaddress with different port. How to handle this situation? Please guide

**Comment by showipintbri** [comment]
ICMP does not use ports.

Can you give a description and example of what you're trying to to do and why you think icmp_probe is the tool for the job?

**Comment by RakeshAMD** [comment]
Hello, thanks for the response.

For getting the system status (whether its online/offline), we thought of doing it with simple ping. If it responds then we conclude the system if online or else offline. 

For that we thought of using icmp_probe module in blackbox_exporter. But how to pass port number also in [here](https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md#icmp_probe). Any constructive feedback is suggestions is always welcome.
