### ISSUE TITLE
Error writing to socket" err="write ip 0.0.0.0->${DST_IP}: sendmsg: message too long. icmp module.

### ISSUE THREAD

**Issue by 0megam** [prometheus/blackbox_exporter#1249]
Hello.
We are running blackbox_exporter as a docker container (official image) to probe some of our infrastructure with icmp module.
For some reason after few days/weeks of constant probing blackbox exporter starting to returned probe_success metric with value 0 for some targets.
If I curl blackbox_exporter with this target and `&debug=true` parameter I'm getting following output:
```
curl 'http://192.168.10.2:9115/probe?module=icmp&target=${DST_IP}&debug=true'
Logs for the probe:
ts=2024-05-30T08:08:07.411598137Z caller=main.go:181 module=icmp target=${DST_IP} level=info msg="Beginning probe" probe=icmp timeout_seconds=3
ts=2024-05-30T08:08:07.411699339Z caller=icmp.go:91 module=icmp target=${DST_IP} level=info msg="Resolving target address" target=${DST_IP} ip_protocol=ip6
ts=2024-05-30T08:08:07.411718022Z caller=icmp.go:91 module=icmp target=${DST_IP} level=info msg="Resolved target address" target=${DST_IP} ip=${DST_IP}
ts=2024-05-30T08:08:07.411733126Z caller=handler.go:120 module=icmp target=${DST_IP} level=info msg="Creating socket"
ts=2024-05-30T08:08:07.411798973Z caller=handler.go:120 module=icmp target=${DST_IP} level=info msg="Creating ICMP packet" seq=26515 id=60301
ts=2024-05-30T08:08:07.41186266Z caller=handler.go:120 module=icmp target=${DST_IP} level=info msg="Writing out packet"
ts=2024-05-30T08:08:07.411891262Z caller=handler.go:120 module=icmp target=${DST_IP} level=debug msg="Overriding TTL (raw IPv4)" ttl=64
ts=2024-05-30T08:08:07.412139679Z caller=handler.go:120 module=icmp target=${DST_IP} level=warn msg="Error writing to socket" err="write ip 0.0.0.0->${DST_IP}: sendmsg: message too long"
ts=2024-05-30T08:08:07.412223981Z caller=main.go:181 module=icmp target=${DST_IP} level=error msg="Probe failed" duration_seconds=0.000571897



Metrics that would have been returned:
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 1.7268e-05
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.000571897
# HELP probe_icmp_duration_seconds Duration of icmp request by phase
# TYPE probe_icmp_duration_seconds gauge
probe_icmp_duration_seconds{phase="resolve"} 1.7268e-05
probe_icmp_duration_seconds{phase="rtt"} 0
probe_icmp_duration_seconds{phase="setup"} 0.000128335
# HELP probe_ip_addr_hash Specifies the hash of IP address. It's useful to detect if the IP address changes.
# TYPE probe_ip_addr_hash gauge
probe_ip_addr_hash 2.164536847e+09
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0



Module configuration:
prober: icmp
timeout: 3s
http:
  ip_protocol_fallback: true
  follow_redirects: true
  enable_http2: true
tcp:
  ip_protocol_fallback: true
icmp:
  ip_protocol_fallback: true
  payload_size: 1472
  dont_fragment: true
  ttl: 64
dns:
  ip_protocol_fallback: true
  recursion_desired: true
```
Problem resolves after blackbox_exporter container has been restarted, but will resurfaces again after few days/weeks.
Worth mention that other destinations on same blackbox_exporter with using same module are working fine, only few specific ones returning `sendmsg: message too long`.

### Host operating system: output of `uname -a`
```
Linux host-1 5.15.0-102-generic #112-Ubuntu SMP Tue Mar 5 16:50:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
### blackbox_exporter version: output of `blackbox_exporter --version`
```
blackbox_exporter, version 0.24.0 (branch: HEAD, revision: 0b0467473916fd9e8526e2635c2a0b1c56011dff)
  build user:       root@e5bbfcc8184e
  build date:       20230516-11:07:25
  go version:       go1.20.4
  platform:         linux/amd64
  tags:             netgo
```

### What is the blackbox.yml module config.
```
modules:
  icmp:
    icmp:
      dont_fragment: true
      payload_size: 1472
    prober: icmp
    timeout: 3s
```

**Comment by electron0zero** [comment]
I am not able to reproduce this issue locally, and from the look of the error message. It seems to be coming from the `sendmsg` [syscall](https://linux.die.net/man/2/sendmsg). 

> Worth mention that other destinations on same blackbox_exporter with using same module are working fine, only few specific ones returning sendmsg: message too long.

this makes me think that issue with the network, or it could be due the `dont_fragment: true` and the MTU is lower then the payload_size. trying reducing the `payload_size` or increasing the MTU.

For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by electron0zero** [comment]
> This is feels like a bug with packet size calculation on the blackbox_exporter side

can you share an example that reproduces this issue or a test case that reproduces this bug and shows that this is an bug in blackbox_exporter? 

It's hard to narrow down and figure out if this is a bug in blackbox_exporter without an test case or a reproducible example setup.

**Comment by 0megam** [comment]
Hi @electron0zero,

Could you please reopen this ticket? I was finally able to reproduce this. Basically, the problem starts when the blackbox-exporter receives an ICMP Destination unreachable, Fragmentation needed (Type 3, Code 4) from one of the hops on the way to the destination IP.
```
Internet Control Message Protocol
    Type: Destination unreachable (3)
        [Expert Info (Note/Response): Type indicates an error]
            [Type indicates an error]
            [Severity level: Note]
            [Group: Response]
    Code: 4 (Fragmentation needed)
    Checksum: 0xf712 [correct]
    [Checksum Status: Good]
    Unused: 00
    Length: 17
    [Length of original datagram: 68]
    MTU of next hop: 1496
    Internet Protocol Version 4, Src: 192.168.10.2, Dst: ${DST_IP}
    Internet Control Message Protocol
```

Even if we fix the MTU size on the hop that sent the ICMP message, the blackbox-exporter continues to print `msg="Error writing to socket" err="write ip 0.0.0.0->${DST_IP}: sendmsg: message too long"` and does not attempt to send ICMP echo requests until it is restarted.

A workaround for this is to insert the following rule into the DOCKER-USER iptables chain to block those packets:
```
iptables -I DOCKER-USER 1 -o ${DOCKER_CUSTOM_BRIDGE_NAME} -p icmp --icmp-type fragmentation-needed -j DROP -m comment --comment "Prevent blackbox-exporter from getting stuck with sendmsg: message too long"
```
My guess is that the ICMP library used by the blackbox-exporter reacts this way to the Type 3, Code 4 ICMP packet. 
Is it possible to implement a flag or configuration in the blackbox-exporter to ignore such ICMP packets and prevent it from getting stuck?

**Comment by electron0zero** [comment]
please avoid posting on old closed issues and open a new issue with details to reproduce the issue, Blackbox exporter version info, and config file.
