### ISSUE TITLE
ICMP: measure packet loss

### ISSUE THREAD

**Issue by dswarbrick** [prometheus/blackbox_exporter#126]
A small feature request for the ICMP probe: it would be great if it were possible to specify a ping count and interval, and have the probe report the number of successful replies. I realise this can technically be achieved by simply setting a low scrape interval and using a function in the rule. But it's not quite the same as periodically sending a short burst of pings, and reporting packet loss, before going to sleep again for a minute or two.

**Comment by brian-brazil** [comment]
There's no plans to add this, see #115

**Comment by dswarbrick** [comment]
Ah woops. Should have searched a bit more first. Sorry about the noise.
