### ISSUE TITLE
 remote error: tls: handshake failure

### ISSUE THREAD

**Issue by weibote** [prometheus/blackbox_exporter#1261]
### Host operating system: output of `uname -a`
Host operating system ：centos stream 9 5.14.0-354.el9.x86_64
### blackbox_exporter version: output of `blackbox_exporter --version`

blackbox_exporter-0.24.0
### What is the blackbox.yml module config.
modules:
  http_alive:
    prober: http
    http:
      fail_if_body_not_matches_regexp:
      - "alive"
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
      valid_status_codes: [200,301,302,303]
      follow_redirects: true
      tls_config:
        insecure_skip_verify: true
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  grpc:
    prober: grpc
    grpc:
      tls: true
      preferred_ip_protocol: "ip4"
  grpc_plain:
    prober: grpc
    grpc:
      tls: false
      service: "service1"
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
      - send: "SSH-2.0-blackbox-ssh-check"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
  icmp_ttl5:
    prober: icmp
    timeout: 5s
    icmp:
      ttl: 5

### What is the prometheus.yml scrape config.
  - job_name: 'web'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http:xxxx
        labels:
          group: web
          hostname: 'xxxx'
          ipaddr: 'xxx'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: url
      - target_label: __address__
        replacement: localhost:9118
### What logging output did you get from adding `&debug=true` to the probe URL?
Logs for the probe:
ts=2024-06-28T09:38:18.172106624Z caller=main.go:190 module=http_2xx target=https://xxxxxxxxx/bspt-tx-prd/ level=info msg="Beginning probe" probe=http timeout_seconds=119.5
ts=2024-06-28T09:38:18.172223902Z caller=http.go:328 module=http_2xx target=https://xxxxxxxxx/bspt-tx-prd/ level=info msg="Resolving target address" target=xxxx ip_protocol=ip4
ts=2024-06-28T09:38:18.172840551Z caller=http.go:328 module=http_2xx target=https://xxxxxxxxx/bspt-tx-prd/ level=info msg="Resolved target address" target=xxxx ip=xxxx
ts=2024-06-28T09:38:18.172896481Z caller=client.go:259 module=http_2xx target=https://xxxxxxxxx/bspt-tx-prd/ level=info msg="Making HTTP request" url=https://xxxxx:4433/bspt-tx-prd/ host=xxxxxxx:4433
ts=2024-06-28T09:38:18.175849016Z caller=handler.go:119 module=http_2xx target=https://xxxxxxxxx/bspt-tx-prd/ level=error msg="Error for HTTP request" err="Get \"https://xxxxx:4433/bspt-tx-prd/\": remote error: tls: handshake failure"
ts=2024-06-28T09:38:18.175873335Z caller=handler.go:119 module=http_2xx target=https://xxxxxxxxx/bspt-tx-prd/ level=info msg="Response timings for roundtrip" roundtrip=0 start=2024-06-28T17:38:18.172958507+08:00 dnsDone=2024-06-28T17:38:18.172958507+08:00 connectDone=2024-06-28T17:38:18.173182643+08:00 gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z tlsStart=2024-06-28T17:38:18.173193003+08:00 tlsDone=2024-06-28T17:38:18.175840164+08:00 end=0001-01-01T00:00:00Z
ts=2024-06-28T09:38:18.175892472Z caller=main.go:190 module=http_2xx target=https://xxxxxxxxx/bspt-tx-prd/ level=error msg="Probe failed" duration_seconds=0.003744405
### What did you do that produced an error?
Follow the normal steps to deploy
### What did you expect to see?
# TYPE probe_success gauge
probe_success 1
### What did you see instead?
# TYPE probe_success gauge
probe_success 0

**Comment by electron0zero** [comment]
the error `remote error: tls: handshake failure` is an issue on the target being probed and not an issue with blackbox_exporter.

For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
