### ISSUE TITLE
Specify DNS when probing http

### ISSUE THREAD

**Issue by RorFis** [prometheus/blackbox_exporter#1275]
Hi,
I use blackbox exporter to check the status of multiple urls. The machine where blackbox exporter is installed is setup to use my private DNS which returns private IPs. I was wondering if there was a way to configure blackbox to use a public dns instead of defaulting to the host's one.

**Comment by halohsu** [comment]
https://github.com/prometheus/blackbox_exporter/issues/1356

**Comment by halohsu** [comment]
Jan 23 16:39:22 master001 blackbox_exporter[1276790]: blackbox_exporter: error: unknown long flag '--dns', try --help
