### ISSUE TITLE
Meta: Maintenance Status?

### ISSUE THREAD

**Issue by EconomicTouristsArmLate** [prometheus/blackbox_exporter#1277]
I know that time is scarce, but given that

- there are open pull requests accumulating, and
- there are no replies from maintainers even for status-requests (https://github.com/prometheus/blackbox_exporter/pull/1105 https://github.com/prometheus/blackbox_exporter/pull/1115 https://github.com/prometheus/blackbox_exporter/pull/1112), 

.. I was wondering if this project is in need of more maintainers, or if this is a short-term under"staffing" only.

I don't want to pressure anyone here, just want to clarify the status so that we can move forward, in case this is not a short term situation.

To throw some ideas into the air:
- maybe advertise need for maintainers (publicly or among existing maintainers in other prometheus repos)
- maybe review the requirements for maintainer status (I didn't look into what the current situation is so far)
- ..?

**Comment by electron0zero** [comment]
Hi, The project is active, with the latest release `0.25.0` on `2024-04-09`. the project is fairly mature so we are just selective about the features we accept to make sure they are relevant to the project and we can support these features once they are accepted.

If you have any pending PR's that are useful to you, please start a conversation on those relevant PR's and mention your use-cases / why that PR is useful to help us out.

[PR #1112](https://github.com/prometheus/blackbox_exporter/pull/1112) is under review and will be merged once approved.

**Comment by electron0zero** [comment]
going to close this, I hope my reply and other activity in the repo answers the issue.
