### ISSUE TITLE
feature: IRC probing

### ISSUE THREAD

**Issue by stapelberg** [prometheus/blackbox_exporter#13]
Would a pull request be accepted which verifies that an IRC server is running on a specific address?

Thanks.

**Comment by brian-brazil** [comment]
I think this would fall under general TCP probing, IRC is text based and pretty simple so I don't think it needs it's own module.

**Comment by stapelberg** [comment]
Correct me if I’m wrong, but with the TCP prober, I can only verify that _something_ is accepting a TCP connection, right?

I don’t think probing TCP connections is generally enough for a modern service. As an example, when hosting services on Google Container Engine, you’ll get a load-balanced IP address which will accept any connection. If the service to which you want to load-balance is not actually available, that connection will be closed immediately after it was accepted. A simple TCP prober would say “this is fine, I got a connection”.

More specifically for the IRC case: I’m actually interested in the fact that a (simple) IRC exchange happens correctly. [RobustIRC](https://robustirc.net), the service in question, might be degraded in such a way that it can still serve connections and serve read-only traffic, but writes are stuck.

**Comment by brian-brazil** [comment]
I intend that tcp probing will be able to do simple query/response, which should cover things like SMTP, IRC, ssh banner checks etc.

**Comment by stapelberg** [comment]
Okay, cool. Do you want to work on the query/response probing feature yourself or would you accept a pull request for that? If so, what do you have in mind with regards to configuration?

**Comment by brian-brazil** [comment]
I'd be happy to take a pull request, I've a long todo list as is.

I was thinking something like:
```
- expect: regex 
  send: somestring
```
possibly with the ability to use capture groups from the expect in the send.
