### ISSUE TITLE
Blackbox Ping Timeout

### ISSUE THREAD

**Issue by Bowen-Tang** [prometheus/blackbox_exporter#1315]
Logs for the probe:
ts=2024-10-30T09:36:50.55957757Z caller=main.go:181 module=icmp target=10.11.62.232 level=info msg="Beginning probe" probe=icmp timeout_seconds=5
ts=2024-10-30T09:36:50.559659647Z caller=icmp.go:91 module=icmp target=10.11.62.232 level=info msg="Resolving target address" target=10.11.62.232 ip_protocol=ip4
ts=2024-10-30T09:36:50.559677982Z caller=icmp.go:91 module=icmp target=10.11.62.232 level=info msg="Resolved target address" target=10.11.62.232 ip=10.11.62.232
ts=2024-10-30T09:36:50.559690817Z caller=handler.go:117 module=icmp target=10.11.62.232 level=info msg="Creating socket"
ts=2024-10-30T09:36:50.559717051Z caller=handler.go:117 module=icmp target=10.11.62.232 level=debug msg="Unable to do unprivileged listen on socket, will attempt privileged" err="socket: permission denied"
ts=2024-10-30T09:36:50.559780971Z caller=handler.go:117 module=icmp target=10.11.62.232 level=info msg="Creating ICMP packet" seq=43269 id=27393
ts=2024-10-30T09:36:50.559798158Z caller=handler.go:117 module=icmp target=10.11.62.232 level=info msg="Writing out packet"
ts=2024-10-30T09:36:50.559809856Z caller=handler.go:117 module=icmp target=10.11.62.232 level=debug msg="Setting TTL (IPv4 unprivileged)" ttl=64
ts=2024-10-30T09:36:50.559880156Z caller=handler.go:117 module=icmp target=10.11.62.232 level=info msg="Waiting for reply packets"
ts=2024-10-30T09:36:55.560497414Z caller=handler.go:117 module=icmp target=10.11.62.232 level=debug msg="Cannot get TTL from the received packet. 'probe_icmp_reply_hop_limit' will be missing."
ts=2024-10-30T09:36:55.560594812Z caller=handler.go:117 module=icmp target=10.11.62.232 level=warn msg="Timeout reading from socket" err="read ip 0.0.0.0: raw-read ip4 0.0.0.0: i/o timeout"
ts=2024-10-30T09:36:55.560700411Z caller=main.go:181 module=icmp target=10.11.62.232 level=error msg="Probe failed" duration_seconds=5.001082113

How To Resolve this issue

**Comment by Bowen-Tang** [comment]
![image](https://github.com/user-attachments/assets/092990e3-3990-4ff0-ab59-c83aac1779a4)

**Comment by electron0zero** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
