### ISSUE TITLE
Seeking Advice on Automating Blackbox Configuration for Dynamic Endpoint Monitoring with Probes CRD

### ISSUE THREAD

**Issue by Pger-Y** [prometheus/blackbox_exporter#1325]
Hi, sorry to bother. I recently discovered Probes CRD and found it extremely convenient. I'm currently using it as the foundation for my Pingmesh server. However, I've encountered a challenge while attempting to configure Prometheus and Blackbox to monitor my HTTP servers using Probes. My goal is to request numerous endpoints such as http://server1/path with custom-body1 and custom-header1, followed by http://server2/path with custom-body2 and custom-header2, and so on. This list may grow to hundreds of endpoints. It's impractical to keep updating the Blackbox configuration each time new endpoints are added. I am wondering if there are any plans to support this scenario, or if there is something incorrect in my approach. Your guidance would be much appreciated.
Is there any plan for blackbox project :)

**Comment by electron0zero** [comment]
Hi, We don't have any plans for dynamic configuration.

For parts related to Probes CRD, please ask in https://github.com/prometheus-operator/prometheus-operator.
