### ISSUE TITLE
What is the difference between network_exporter and blackbox exporter

### ISSUE THREAD

**Issue by jedi201321** [prometheus/blackbox_exporter#1339]
Hello，
I am a rookie. I'd like to know the difference between these two products . Thanks.

ps:
network_exporter is here: 
https://github.com/syepes/network_exporter

**Comment by electron0zero** [comment]
I see some similarity and some differences based on the quick look at the README.md, you can use either based on your requirements. 

For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
