### ISSUE TITLE
(Bug) Failed to connect: "connect: cannot assign requested address""

### ISSUE THREAD

**Issue by andrewhowdencom** [prometheus/blackbox_exporter#134]
Just had an instance of the blackbox exporter failed to connect to an endpoint for about 3 hours or so; ended up deleting it and rebuilding it (it's in a docker image). 

Runtime environment was Kubernetes 1.5.5 on GKE with their container linux. 

Check was HTTP check. Configuration worked fine for lots of other targets. Target wasn't actually down, but was reliably being shown as down when queried directly. Same process on same machine run later shows target up.

I didn't check logs or anything; unfortunately, I just rm'd it to get the monitoring to stop chirping =\ I will keep an eye on this, and update if it happens again. In the mean time, I'm opening this issue, which if it's fine, I will close again on Monday.

Edit: This was written quite late at night. It's a little incoherent.

**Comment by andrewhowdencom** [comment]
Hasn't since reappeared, but now running multiple replicas to ensure stateful errors don't affect uptime probes. Weird problem.

**Comment by andrewhowdencom** [comment]
This has reappeared. Logs are:
```
time="2017-05-05T04:51:40Z" level=warning msg="Error for HTTP request to http://www.redacted.de: Get http://www.redacted.de/: dial tcp4 185.88.xxx.xxx:80: connect: cannot assign requested address" source="http.go:159" 
```

Looking further

**Comment by andrewhowdencom** [comment]
This might be a problem with networking in Kubernetes, on GKE.

**Comment by brian-brazil** [comment]
This is something to do with the networking on your end.

**Comment by andrewhowdencom** [comment]
Ja. Closing as not a bug in Blackbox exporter; I'll set up some sort of monitoring on open TCP connections on the hosts, and run more exporters so connections are more evenly spread.
