### ISSUE TITLE
Rewrite http header with specified targets

### ISSUE THREAD

**Issue by Colstuwjx** [prometheus/blackbox_exporter#135]
Hi,  is there any way to rewrite http header while the target is in specified list?

**Comment by brian-brazil** [comment]
No, you can create modules with the headers you need.

**Comment by Colstuwjx** [comment]
To support this, blackbox exporter may need add some modules and prometheus use `relabel` to determine the real `module` param. Thus, it also need to be reloadable.

**Comment by brian-brazil** [comment]
It already supports modules via params. Please read the documentation.
