### ISSUE TITLE
Need a IP White list support

### ISSUE THREAD

**Issue by Colstuwjx** [prometheus/blackbox_exporter#138]
Hi team,

Due to some security reason, we maybe need introduce a white list config, thus, **ONLY** IPs in this white list could make a normal request, otherwise, blackbox exporter directly return 403.

**Comment by brian-brazil** [comment]
For authorisation you can run a reverse proxy in front of the exporter.

Usually you'd be running the blackbox exporter right beside the prometheus, so could bind to localhost.

**Comment by Colstuwjx** [comment]
To mock up the real world user request, we maybe need to run exporter on some outside nodes. It could  confirm sth about `is the DNS resolution ok`,  `is the network reachable`, etc.
