### ISSUE TITLE
Docker level=error msg="Error listening to socket: listen ip4:icmp 0.0.0.0: socket: operation not permitted" file=icmp.go line=32

### ISSUE THREAD

**Issue by kaihendry** [prometheus/blackbox_exporter#14]
This is my service file: http://s.natalian.org/2015-11-20/blackbox-exporter.service

Note I am running with `--privileged` which should provide all CAPS.

http://sg.dabase.com:9115/probe?target=dabase.com&module=icmp 
results in errors like:

    Nov 20 08:06:17 rojak docker[8786]: time="2015-11-20T08:06:17Z" level=error msg="Error listening to socket: listen ip4:icmp 0.0.0.0: socket: operation not permitted" file=icmp.go line=32

Some what confusingly I get metrics like:

    probe_duration_seconds 0.000251
    probe_success 0

When the domain exists or not [1]. Is 0 success ?!

[1] http://sg.dabase.com:9115/probe?target=doesnotexist.example.com&module=icmp

**Comment by brian-brazil** [comment]
This seems like more of a Docker/security/systemd problem than one with the blackbox exporter. I'd suggest asking those communities how to get raw socket access.

0 means failure, in general for boolean metrics 0 is false and 1 is true.

**Comment by kaihendry** [comment]
Is the golang program somehow dropping perms I wonder? Inside the container I can ping fine.
```
[root@rojak system]# docker exec -i -t blackboxprober sh
/bin $ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=58 time=2.023 ms
64 bytes from 8.8.8.8: seq=1 ttl=58 time=1.748 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
```

**Comment by brian-brazil** [comment]
ping is SUID, so it has root.

**Comment by kaihendry** [comment]
can't the golang binary be setup to also have suid in the Dockerfile?

**Comment by jimmidyson** [comment]
So if we want to run this in Docker we should probably try to do the same thing in this exporter? AFAIK ping is suid, raises privs to open socket & then returns to non-suid to continue. Can we do the same?

**Comment by brian-brazil** [comment]
It's a bit more complicated as 1) we'd need to support dropping privs on all platforms with all the associated options and 2) we'd need to share the one open socket across all the scrapes.

**Comment by jimmidyson** [comment]
True but doable. Could be a "fun" challenge :)

**Comment by eimann** [comment]
The ping binary should not have suid set, but rather have appropriate capabilities:

$ getcap /bin/ping
/bin/ping = cap_net_raw+ep

Same goes for the exporter:
sudo setcap cap_net_raw+ep blackbox_exporter

With this setting the exporter will run properly without suid/uid=0 set.

**Comment by StianOvrevage** [comment]
I'm hitting this problem as well. Can't use setcap within the container either.

**Comment by sdurrheimer** [comment]
Can you guys try with the `master` tag ? 
The current `latest` tag is based on `alpine` and run with an unprivileged user `golang`.
The current `master` tag is based on `busybox` and run as root.

**Comment by StianOvrevage** [comment]
Working!

probe_success 1

Thanks!

**Comment by brian-brazil** [comment]
We've documented the requirements now.
