### ISSUE TITLE
How Can We Use Blackbox_Exporter To Get HTTP Request

### ISSUE THREAD

**Issue by hmmxp** [prometheus/blackbox_exporter#141]
Dear All,

How Can We Use Blackbox_Exporter To Get HTTP Request Of Website?

Idea is Having Blackbox_Exporter On Separate Machine To Probe Websites To Check ping, How Long Does It Take To Request The Website Etc. Then From Prometheus Server Pulling The Data From This Blackbox_Exporter Machine

Thank You In Advance

**Comment by brian-brazil** [comment]
Usage questions are best asked on https://groups.google.com/forum/#!forum/prometheus-users
