### ISSUE TITLE
Dynamic parameters

### ISSUE THREAD

**Issue by adam-devapp** [prometheus/blackbox_exporter#143]
The documentation doesn't really cover dynamic parameters in clear usable terms. I'm looking to feed in a content check parameter, the check always returns no error.

I've been following the example at: http://www.dendeer.com/post/intro_prometheus/ with no luck.

The black box service runs and returns:
http://x.x.x.x.:9115/probe?target=www.xxxx.com.au.io&module=http_content_check&content=5476543885434

		probe_ip_protocol 4
		probe_http_status_code 200
		probe_http_content_length 111
		probe_http_redirects 0
		probe_http_ssl 0
		probe_duration_seconds 0.060533
		probe_success 0

In my blackbox.yaml file I have:

	      http_content_check:
	        tcp:
	          query_response:
	          - expect: "^+OK"
	        prober: http
	        tcp:
	          protocol: tcp4
	        timeout: 10s
	        http:
	          method: GET
	          valid_status_codes: [200]
	          headers:
	            Host: monitor.server.com
	            Accept-Language: en-US
	          no_follow_redirects: true
	          fail_if_ssl: false
	          fail_if_not_ssl: false
	          fail_if_not_matches_regexp: [__param_content]

And in the prometheus.yml:

		  - job_name: "website"
		    scrape_interval: "15s"
		    scheme: "http"
		    metrics_path: "/probe"
		    params:
		      module: ["http_content_check"]
		      target: ["www.domain.com"]
		      content: ["555 254 254"]

I am looking to have one black box check, and multiple prometheus checks which use this check with different target and expected http content on the page.

**Comment by brian-brazil** [comment]
> The documentation doesn't really cover dynamic parameters in clear usable terms.

We usually only document features that exist. Use multiple modules.

**Comment by kubicgruenfeld** [comment]
for everyone stumbling upon this issue.
i found this gist very helpful to configure blackbox-exporter jobs dynamically:

https://gist.github.com/ycyr/0110b34878f4f49d3cce80c6be207010

**Comment by mous2890** [comment]
@kubicgruenfeld can you please share the configuration you ended up using for dynamically configuring jobs. Trying to do something similar with the http probe passing in headers dynamically
