### ISSUE TITLE
IF probe_success == 0 always returning 0

### ISSUE THREAD

**Issue by adam-devapp** [prometheus/blackbox_exporter#145]
I have an alert setup that always triggers, even though running the check manually returns correct i.e. 1. Why is the alert always failing.

The alert is setup as:

			ALERT Websites
			  IF probe_success == 0
			  FOR 3m
			  LABELS {job="domain.com.au"}
			  ANNOTATIONS {description="{{$labels.job}} has been down for more than 3 minutes.", summary="{{$labels.job}} down"}

With a check of:

		  - job_name: "domain.com.au"
		    metrics_path: /probe
		    scrape_interval: 60s
		    params:
		      module: [custom_website_check]
		      target: ["https://domain.com.au"]
		    scheme: http
		    static_configs:
		    - targets:
		      - "localhost:9115"

With a blackbox rule of:

		  custom_website_check:
		    prober: http
		    timeout: 10s
		    http:
		      fail_if_not_matches_regexp:
		      - "Expected Text"

Why does the alert always return true (i.e. 0), yet a manual check shows false (i.e. 1):
http://x.x.x.x:9115/probe?target=www.domain.com.au&module=custom_website_check

		probe_ip_protocol 4
		probe_ssl_earliest_cert_expiry 1534824000.000000
		probe_http_status_code 200
		probe_http_content_length -1
		probe_http_redirects 1
		probe_http_ssl 1
		probe_duration_seconds 0.827440
		probe_success 1

**Comment by brian-brazil** [comment]
Those are not the same targets.

**Comment by adam-devapp** [comment]
Can you explain a bit further, and give an example of what it should be? Assuming the target is fed to the probe as a URL, which is triggered by the job name.

**Comment by adam-devapp** [comment]
I have it showing as a parameter:

      - source_labels: [match]
        regex: (.*)
        target_label: '__param_fail_if_not_matches_regexp'
        replacement: '${1}'

however I'm not sure if the key is "__param_fail_if_not_matches_regexp" which is being replaced - What should this key be? i.e. __http_param_fail_if_not_matches_regexp ?

**Comment by adam-devapp** [comment]
Have fixed by creating a static check:

		  my_website_content_check:
		    prober: http
		    timeout: 10s
		    http:
		      fail_if_not_matches_regexp:
		      - "my HTML text to check"

And having all of the web sites to check in a file, which injects into prometheus.yml config:


    global:
        external_labels:
           monitor: 'hostname'

    rule_files:
        - '/etc/prometheus/alert.rules'

    scrape_configs:
      - job_name: 'http_content_check'
        scrape_interval: 60s
        scrape_timeout: 10s
        metrics_path: /probe
        file_sd_configs:
          - files:
            - '/etc/prometheus/targets/sites.json'
        relabel_configs:
          - source_labels: [__address__]
            regex: (.*)(:80)?
            target_label: __param_target
            replacement: ${1}
          - source_labels: [__param_target]
            regex: (.*)
            target_label: instance
            replacement: ${1}
          - source_labels: []
            regex: .*
            target_label: __address__
            replacement: 10.0.3.159:9115
          - source_labels: [checker]
            regex: (.*)
            target_label: __param_module
            replacement: '${1}'

And the targets/sites.json file contains an array of sites, with differing methods

[{
                "targets": ["https://sitetocheck.com"],
                "labels": {
                        "checker": "my_website_content_check"
                }
        },
]
