### ISSUE TITLE
Support DISPLAY-HINT attributes

### ISSUE THREAD

**Issue by SuperQ** [prometheus/blackbox_exporter#153]
[RFC 2579](https://tools.ietf.org/html/rfc2579#section-3.1) specifies how `OCTET STRING` entries can be displayed.

It would be useful to support these in the generator/exporter for improved label value mappings.

**Comment by brian-brazil** [comment]
Are there particular OIDs you want to capture?

To get good metrics out we need some care, as for example date times (which are `2d-1d-1d,1d:1d:1d.1d,1a1d:1d`) should be converted to a unix timestamp.

**Comment by RichiH** [comment]
Closing as this is snmp, not blackbox.

**Comment by RichiH** [comment]
Tossing https://github.com/prometheus/snmp_exporter/issues/163 in here to get the nice reference block.
