### ISSUE TITLE
SSL certificate expiry fails to see new certificate

### ISSUE THREAD

**Issue by ipstatic** [prometheus/blackbox_exporter#163]
We are using Let's Encrypt SSL certificates for a few of our sites and monitoring them for expiry. Several times now we have gotten alerts for different sites having a low expiry time. When investigating, they have already rotated out and gotten a new certificate. If we restart the blackbox exporter, it sees the new certificate and expiration time and recovers. Has anyone else experienced this?

**Comment by Suhas-Git** [comment]
Can you please share your blackbox.yml for the SSL certificate?

**Comment by ipstatic** [comment]
blackbox.yml:
`modules:
    https_2xx:
      prober: http
      timeout: 5s
      http:
        no_follow_redirects: true`

prometheus.yml:
`{
  "job_name": "blackbox_https_2xx",
  "metric_relabel_configs": [
    {
      "action": "drop",
      "source_labels": [
        "__name__"
      ],
      "regex": "[^:]+:[^:]+:[^:]+"
    }
  ],
  "relabel_configs": [
    {
      "source_labels": [
        "__address__"
      ],
      "regex": "(.*)(:80|:443)?",
      "target_label": "__param_target",
      "replacement": "https://${1}"
    },
    {
      "source_labels": [
        "__address__"
      ],
      "regex": "(.*)(:80|:443)?",
      "target_label": "instance",
      "replacement": "${1}"
    },
    {
      "source_labels": [
        "__param_module"
      ],
      "regex": "(.*)",
      "target_label": "module",
      "replacement": "${1}"
    },
    {
      "source_labels": [

      ],
      "regex": ".*",
      "target_label": "__address__",
      "replacement": "127.0.0.1:9115"
    }
  ],
  "metrics_path": "/probe",
  "params": {
    "module": [
      "https_2xx"
    ]
  },
  "scrape_interval": "60s",
  "static_configs": [
    {
      "targets": [
        "cert.example.com",
      ]
    }
  ]
}`

**Comment by brian-brazil** [comment]
That doesn't sound right, the only thing that I can think of that'd cause that would be keepalives and we disable those.

**Comment by brian-brazil** [comment]
We've seen no other reports of this and there's nothing in the code that could cause this, so it sounds like it might be something specific to your environment (some caching?). If you're still seeing this, please reopen,
