### ISSUE TITLE
Feature Request: Add how long the HTTP probe took to respond

### ISSUE THREAD

**Issue by andrewhowdencom** [prometheus/blackbox_exporter#165]
At the moment, we're querying a binary "is up/down", based on whether or not the site responds within a ${X] period. However, in some cases it's useful to know just how "up" a site is. For example, ideally I would put an alert around "takes longer than 5 seconds to respond", but allow the the request to complete and log it, so that I can track the latency before and after the "is down" check.

I'm not sure whether the blackbox probe is the correct place to do this. Ideally, we'd instrument the webserver such that we could get a snapshot of the request latencies from that -- however, that does not capture the intermediary load balancers, or just network issues. Thus, I feel it's at least reasonable to track the latency in this exporter. 

Perhaps something like

```
# HELP How long the request took to complete (in seconds)
# TYPE gauge
http_probe_response_time_total
```

**Comment by brian-brazil** [comment]
probe_duration_seconds

**Comment by andrewhowdencom** [comment]
lol oh god I missed that. Thanks @brian-brazil <3 I appreciate your patience.
