### ISSUE TITLE
Please document what metrics are exposed

### ISSUE THREAD

**Issue by nafg** [prometheus/blackbox_exporter#166]

**Comment by brian-brazil** [comment]
It's not normal to document metrics, as they come from a number of different pieces of code which you rarely have control of all of. The HELP and name of the metric should give you enough to work with, and at the end of the day the only real way to understand a metric is to look at the code. Duplicating that elsewhere is just going to get stale.

**Comment by nafg** [comment]
How is it different than any API? What's the point of the readme or any
prose docs if the code will change?

**Comment by SuperQ** [comment]
I disagree, we should have good reference docs for our exporters.  "Read the code" is not sufficient.

**Comment by brian-brazil** [comment]
In my experience read the code is the only thing that ultimately works for metrics. Every attempt I've seen to comprehensively document metrics has failed.

**Comment by nafg** [comment]
The same is true of APIs, yet we​ try...

**Comment by brian-brazil** [comment]
APIs are (usually) explicitly for consumption by others, whereas most metrics are added on a whim for potential future use in debugging/analysis.

**Comment by SuperQ** [comment]
For the blackbox_exporter, it's very much an API.

**Comment by brian-brazil** [comment]
There's a fair few subtleties, which basically boils down to re-rewriting the code in English.

**Comment by nafg** [comment]
Prometheus is a debugging tool?

If there are such subtleties doesn't that make it more important?

Would "rewriting the code in English" make it easier to maintain
documentation... or are you conceding that currently reading the code is
not a solution?

All I want is to set up Prometheus alerting when one of my servers goes
down. Is that like an unsupported corner case??

**Comment by brian-brazil** [comment]
If the metric name and HELP aren't enough, it's unlikely anything short of the source code will help you.

> If there are such subtleties doesn't that make it more important?
> Would "rewriting the code in English" make it easier to maintain
documentation... or are you conceding that currently reading the code is
not a solution?

Such subtleties mean you'd just be writing the code a 2nd time in English, which would add maintenance burden without much benefit to the user.

> All I want is to set up Prometheus alerting when one of my servers goes
down. Is that like an unsupported corner case??

That is supported.That is not however what you have requested in this issue.

**Comment by nafg** [comment]
I want a list of the metric names and what they do. Yes it is included in
the metrics page, but I needed it before it was running. (Everything is
managed via salt in version control and applied on push. I didn't want to
have to push twice and wait each time.) And I didn't expose the port to the
world so I can't easily see them. And how do I know the metrics I'm seeing
are the only ones it can serve (right now I'm doing a very barebones http
config)?

**Comment by nafg** [comment]
Also I don't mind reading code but I would have no idea where to look (I
don't write Go). At a minimum you could link to where on the code they're
defined...

**Comment by brian-brazil** [comment]
What you're really looking for is a user guide, a detailed reference guide for metrics is not realistic.

Here's some that might help:
https://michael.stapelberg.de/Artikel/prometheus-blackbox-exporter
https://www.robustperception.io/get-alerted-before-your-ssl-certificates-expire/
https://www.robustperception.io/checking-if-ssh-is-responding-with-prometheus/

> And how do I know the metrics I'm seeing
are the only ones it can serve (right now I'm doing a very barebones http
config)?

If that's not the case, that's generally a bug on the part of the application.

**Comment by matthiasr** [comment]
As a potential user, when I evaluate whether Prometheus is suited for me, and intend to collect metrics about blackbox probes, I need to know what metrics I can expect. As a current user, I need to understand how metrics relate to one another, which is not something I can get from the HELP. 

Reading the code is _not_ a sufficient substitute. We cannot assume that every Prometheus user knows Go or require that they learn it. Because metrics are constructed throughout the code, it's not even obvious to someone moderately familiar with the client library how to locate the code that generates a particular metric.

Documenting the intent and semantics does not "re-implement the code", the code implements the intent and semantics. If the intent is not documented, the code is meaningless, any and all behaviour are "by design" if the design is whatever the current behaviour is.

Exposing metrics is _the only thing that an exporter does_, so yes, the metrics that it exposes are the API.

**Comment by brian-brazil** [comment]
> As a current user, I need to understand how metrics relate to one another, which is not something I can get from the HELP.

That's the case for anything exposing metrics. 

> If the intent is not documented, the code is meaningless, any and all behaviour are "by design" if the design is whatever the current behaviour is.

Reference docs document semantics, not intent. Intent is in design documents and comments, which is different to what was originally requested here.

**Comment by matthiasr** [comment]
The documentation of the _semantics_ can link the design documents, if any exist. This does not invalidate the point that "read the code" is not an answer to "what does this even mean."

**Comment by brian-brazil** [comment]
Read the code is ultimately the only answer to what something means. It is unrealistic to think otherwise.

If you want to attempt to maintain comprehensive metric documentation in the repositories you maintain you're free to do so, however I'm not willing to attempt what my experience tells me is a fool's errand in this repository.

**Comment by nafg** [comment]
> Read the code is ultimately the only answer to what something means. It is unrealistic to think otherwise.

How is that not true of every API?


Really, maybe I'm missing something due to ignorance but I don't get what the big deal is that you're pushing back against. I mean if the README would have said "The http module exposes a metric `probe_success` which is set to `1` if the probe succeeds and `0` if it fails" that would have saved me time and frustration. Why are you so against doing that?

**Comment by brian-brazil** [comment]
> How is that not true of every API?

APIs are designed to be a useful abstraction by others. Metrics not so much.

> I mean if the README would have said "The http module exposes a metric probe_success which is set to 1 if the probe succeeds and 0 if it fails" that would have saved me time and frustration.

That metric is mentioned in the readme.

**Comment by nafg** [comment]
If metrics are not designed to be a useful abstraction by others, then what are they designed for?

**Comment by brian-brazil** [comment]
For most metrics, to be a debugging aid.

**Comment by nafg** [comment]
And there I was thinking metrics were about knowing whether your
mission-critical production systems are working properly... 😁

**Comment by nafg** [comment]
Also I get the feeling that you're mainly describing metrics in general,
like someone sprinkles various guages around their webapp, while I'm trying
to discuss the official Prometheus exporter for performing uptime checks on
users' systems.

**Comment by SuperQ** [comment]
@nafg This documentation is something we need, it will get written up, not to worry.

**Comment by fabxc** [comment]
> In my experience read the code is the only thing that ultimately works for metrics. Every attempt I've seen to comprehensively document metrics has failed.

As a data point: https://github.com/kubernetes/kube-state-metrics/tree/master/Documentation
All metrics in kube-state-metrics are documented and tested at a basic level. Users seem very happy and we see lots of contributions that all care about keeping docs and tests up to date.

**Comment by brian-brazil** [comment]
The kube-state-metrics ones are nothing the /metrics wouldn't tell you. A better current example would be etcd, which has good operational information beyond the HELP.

The previous times I've seen lists of metrics they've been just that, often from a team just getting starting with metrics and with the best of intentions. Within 3-6 months, the page they're documented on is forgotten. When someone asks for a list of metrics, that's what I'm thinking of.

**Comment by shibumi** [comment]
Hi, is there any update to this issue? I think it would be really helpful to have a full list and documentation of all metrics for the exporters, especially for beginners.

**Comment by SuperQ** [comment]
Yes, I agree, the exporter is pretty stable these days. We could add a docs directory with some info on the per-probe details.

**Comment by jbomaileva** [comment]
Would be great.

**Comment by shibumi** [comment]
so do we re-open this issue?

**Comment by SuperQ** [comment]
@shibumi Sure, I think things are stable enough that it would be worth documenting the collectors better. Do you have some time and urge to help out? :grin:

**Comment by shibumi** [comment]
@SuperQ I still have this this cifs support for procfs on my to do. But documentation doesn't sound so time consuming. Do you have any wishes? Do you want it in a Wiki or a website or just as markdown files in a seperate `docs` folder?

**Comment by SuperQ** [comment]
Markdown files in `docs` is fine. I'd say one README.md that documents the common metrics, and then a file for each prober detailing prober-specific stuff.

**Comment by SuperQ** [comment]
Another option would be to generate this with godoc.

**Comment by mclate** [comment]
Voting for documentation here as well. It is quite confusing to see metrics such as `probe_success` with values of `0`. I would expect it to be at least `1` so that one can count sum on them. Another example would be `probe_http_status_code` with no status code reported (and only `0` in values). It would make sense to have this behaviour documented with some examples on how these metrics were supposed to be used (considering the values they expose).

**Comment by den-is** [comment]
Please generate a documentation list of all available metrics

**Comment by JensRantil** [comment]
I would love to see documentation, too. Accessing the actual `/metrics` endpoint for me is a bit hard. Had the `HELP` text been accessible through through the Prometheus GUI this would not have been needed for us. I filed an issue for this just now: https://github.com/prometheus/prometheus/issues/6814

**Comment by cosenmarco** [comment]
Could please someone familiar with the code, meanwhile this issue is discussed and evaluated, put a reference in the README as to where to find in the code the different definitions and labels? It would save time to people (like me) evaluating this exporter for production use not having to read the entire code searching for the information.

**Comment by shibumi** [comment]
@cosenmarco this is not easily possible. The metric descriptions are scattered in the code. For example you can find three DNS metrics here:

https://github.com/prometheus/blackbox_exporter/blob/master/prober/dns.go#L127L140

Some HTTP metrics + descriptions are here:

https://github.com/prometheus/blackbox_exporter/blob/master/prober/http.go#L232L290

**Comment by shibumi** [comment]
@SuperQ Wouldn't this be a nice project for Google Summer of Docs? Somebody could work on documenting metric descriptions in all prometheus/*_exporter.

**Comment by SuperQ** [comment]
@shibumi Yes, that sounds like a great idea. I guess Prometheus would [need to apply](https://developers.google.com/season-of-docs/docs/get-started).

**Comment by shibumi** [comment]
@SuperQ yes, and application period for organizations is [already over](https://developers.google.com/season-of-docs/docs/timeline). Maybe next year.
