### ISSUE TITLE
ValidStatusCodes glob usage

### ISSUE THREAD

**Issue by yosefy** [prometheus/blackbox_exporter#171]
need to enable any http exit  status codes
looks from code that i need to list all possible codes

could be good to enable [1xx,2xx,3xx,4xx,5xx] or something like that
and not:

[100,101,102,200,201,202,203,204,205,206,207,208,226,300,301,302,303,304,305,307,308,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,421,422,423,424,426,428,429,431,444,451,499,500,501,502,503,504,505,506,507,508,510,511,599]

may be there is better way i don't know
thanks

**Comment by SuperQ** [comment]
The current code only supports an explicit list of integers, so enumerating all of them is required.

Happy to review PRs that would improve this.

**Comment by brian-brazil** [comment]
I think most users have no more than a handful of codes they expect. I'd be hesitant to add additional grammar to support a very rare use case. If you really need all potential 500 current and future codes, a config management system can generate them.

**Comment by yosefy** [comment]
Brian, you are right i guess it as no one else has such a problem :)
i just was asked to monitor service for "any" http reply
thats why i got into this thing
 thanks
