### ISSUE TITLE
how to set prometheus blackbox endpoints url

### ISSUE THREAD

**Issue by pc10201** [prometheus/blackbox_exporter#175]
![blackbox](https://user-images.githubusercontent.com/8475089/27676456-8dee91da-5ce0-11e7-944c-1ac1e0bc45e6.png)

I want to change prometheus blackbox endpoints with my server public IP.Not 127.0.0.1

Make the URL valid.How to config that?

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!aboutgroup/prometheus-users
