### ISSUE TITLE
Missing probe: 'probe_ssl_earliest_cert_expire'

### ISSUE THREAD

**Issue by BalintSzigeti** [prometheus/blackbox_exporter#178]
I tried to set up a https check with backbox_exporter but it doesn't return with the expiration time. 
Checking the code:
https://github.com/prometheus/blackbox_exporter/blob/master/http.go#L85
and I noticed the 85-87 code block is missing from 91-94. Is it the bug?

I read https://www.robustperception.io/get-alerted-before-your-ssl-certificates-expire/ blog but I can't get the 'probe_ssl_earliest_cert_expiry'

Here is an example that I get:
curl -v 'http://localhost:9115/probe?target=https://google.com&module=http_2xx'
* About to connect() to localhost port 9115 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9115 (#0)
> GET /probe?target=https://google.com&module=http_2xx HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9115
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Wed, 28 Jun 2017 13:58:38 GMT
< Content-Length: 161
< Content-Type: text/plain; charset=utf-8
<
probe_ip_protocol 6
probe_http_status_code 0
probe_http_content_length 0
probe_http_redirects 0
probe_http_ssl 0
probe_duration_seconds 0.004397
probe_success 0
* Connection #0 to host localhost left intact

How can I get the probe_ssl_earliest_cert_expire?

**Comment by brian-brazil** [comment]
The current release is missing a line of code to make it work. This is already fixed in master, which will hopefully get released next week. Older versions work correctly.
