### ISSUE TITLE
Differentiate between "could not connect" and "certificate expired"

### ISSUE THREAD

**Issue by sandersaares** [prometheus/blackbox_exporter#194]
At the moment an expired certificate just looks like the URL to be probed is down, with no indication that an expired certificate is the reason. It would be desirable to differentiate between a failure to connect and an expired certificate, to allow any triggered human action to be more easily directed at the root cause of the problem.

**Comment by brian-brazil** [comment]
From the standpoint of a users' browser, these are basically the same thing.

It's not practical for us to enumerate every single possible error that can occur down in the Go http client as a metric, as that's basically event logging and would require a never ending amount of effort. This is also an error that's going to be really obvious when you go manually test it (or if you've setup alerts for certs about to expire).
