### ISSUE TITLE
Extract prober from exporter

### ISSUE THREAD

**Issue by discordianfish** [prometheus/blackbox_exporter#205]
Hi,

I've created my own fork of the blackbox_exporter to modify it for my needs but would like to re-use as much as possible from the original exporter as well as contribute back prober and prober changes/fixes which is hard right now.

Therefor I propose to extract the probers into their own package that can be reused.
We could create an interface `ProberFn(ctx context.Context, target string, config Config, registry *prometheus.Registry)` where Config would be a prober specific config struct that is referenced in the blackbox_exporter config struct.

This change would be fairly light on the blackbox_exporter and arguably it's main namespace is quite big already so IMO moving probers in their own package makes sense anyway. It would also make the exporter a bit more testable.

Thoughts?

**Comment by brian-brazil** [comment]
I'd be open to that, though for proper decoupling you'll need to thing a bit more about how to pass down the config.

**Comment by discordianfish** [comment]
Right now in my fork I have a ProberFn interface which takes blackbox.Module as config, but I don't think that coupling like this is a very good idea.

Better would be for the Probers to export a config struct which could be referenced by the blackbox.Module struct. That seems straight forward to me and what I would try out.

Alternatively we could also take an interface{} or io.Reader and keep all knowledge in the prober but I don't think that's a better approach.

**Comment by brian-brazil** [comment]
I agree that an interface is not a good idea, that'd be difficult for config validation for example.

**Comment by discordianfish** [comment]
I believe my 2nd option boils down to using an interface{} too, since for a generic ProbeFn interface we need to have an interface for the config too.

The more I think about this, the more I believe one shared config is the best option. While it might be nicer to pass only the config bits to the prober that it requires it complicates everything.

So instead I'd go with option 1 and just pass blackbox.Module to the prober:

- move config.go to own config package (could also keep at root, think own package is cleaner)
- move probeXX to own prober package
- create interface `ProberFn(ctx context.Context, target string, config.Module, registry *prometheus.Registry)` in prober package
- use init() in each prober to register prober function

What do you think?

**Comment by brian-brazil** [comment]
This still leaves us a coupling for the configs, which I don't think we can avoid (or at least would be a lot of work at this stage). I'd suggest for now keeping the config up in main for the sake of simplicity, unless you've a technical reason you want it in a proper package.

Given there's still the coupling, I'm not sure using `init()` buys much. It works for the node exporter because there's no config.

**Comment by discordianfish** [comment]
Leaving it in main sounds fine, the only reason for a separate package at this point would be a nicer import name. Agree on the other points. Will submit a PR soon!
