### ISSUE TITLE
Blackbox exporter configuration (Question)

### ISSUE THREAD

**Issue by songcaixin** [prometheus/blackbox_exporter#211]
In blackbox_exporter configuration,there are following texts:
<http_probe>
# Accepted status codes for this probe. Defaults to 2xx.
  [ valid_status_codes: <string>, ... | default = "2xx" ]

But in my machine，the status of codes is not array of strings,but []int.
If i input string, i will get back error messages...
I want to know the problem..

**Comment by Conorbro** [comment]
This is a mistake in the documentation for the Blackbox exporter. It should be an array of integers, not strings.
