### ISSUE TITLE
6 when ip4 with dns prober

### ISSUE THREAD

**Issue by marrotte** [prometheus/blackbox_exporter#216]
### Host operating system: output of `uname -a`
Linux d68fbc84b1fe 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`
blackbox_exporter, version 0.8.1 (branch: HEAD, revision: 9741061ec748fa75990c54eb8b8bbce9c63bdc7c)
  build user:       root@8f0109211fef
  build date:       20170808-13:41:49
  go version:       go1.8.3

### What is the blackbox.yml module config.
modules:
  dns_tcp:
    prober: dns
    timeout: 5s
    dns:
      preferred_ip_protocol: "ip4"
      transport_protocol: "tcp"

### What is the prometheus.yml scrape config.
None.  Testing with curl
curl "http://192.168.4.1:9115/probe?target=[my.domain.tld]&module=dns_tcp"

### What logging output did you get from the `blackbox_exporter`?
time="2017-09-01T23:41:53Z" level=warning msg="Error while sending a DNS query: dial tcp6 :53: connect: cannot assign requested address" source="dns.go:159"

### What did you do that produced an error?
curl "http://192.168.4.1:9115/probe?target=[my.domain.tld]&module=dns_tcp"

### What did you expect to see?
probe_ip_protocol 4

### What did you see instead?
probe_ip_protocol 6

**Comment by brian-brazil** [comment]
With the current release you need to specify the :53 in the address.

**Comment by marrotte** [comment]
Thank you! Thank you!  That works.  Any chance the query_name can be passed in?

**Comment by brian-brazil** [comment]
No, it only comes from the config file.
