### ISSUE TITLE
SSL Errors in blackbox

### ISSUE THREAD

**Issue by Priyotosh008** [prometheus/blackbox_exporter#226]
### Host operating system: output of `uname -a`
Linux muclhi614 2.6.32-696.6.3.el6.x86_64 #1 SMP Fri Jun 30 13:24:18 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`
blackbox_exporter-0.8.1.linux-amd64

### What is the blackbox.yml module config.
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: "ip4"
      http_config:
        insecure_skip_verify: true
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: false
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp

### What is the prometheus.yml scrape config.
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://171.76.45.17:2243/console

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 171.17.24.25:9115  # Blackbox exporter.

  - job_name: 'jmx'
    static_configs:
      - targets: ['localhost:9101']

### What logging output did you get from the `blackbox_exporter`?
time="2017-09-13T18:16:26Z" level=error msg="Error for HTTP request to https://171.76.45.17:2243/sst/status.html: Get https://171.76.45.17:2243/sst/status.html: x509: certificate is valid for 171.17.29.43, 82.10.23.1, not 171.76.45.16" source="http.go:178"

### What did you do that produced an error?
NA

### What did you expect to see?
200 value for probe_http_status_code

### What did you see instead?
0 value for probe_http_status_code even if the URL is UP and running

**Comment by brian-brazil** [comment]
> Get https://171.76.45.17:2243/sst/status.html: x509: certificate is valid for 171.17.29.43, 82.10.23.1, not 171.76.45.16" source="http.go:178"

This seems self-explanatory.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
