### ISSUE TITLE
rabbitmq aliveness test problem

### ISSUE THREAD

**Issue by yosefy** [prometheus/blackbox_exporter#228]
### Host operating system: output of `uname -a`
Linux sgp1-prometheus 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`
blackbox_exporter, version 0.7.0 (branch: master, revision: 9b67dd9b488160bb656cf130718b2aa62a7f30e6)
  build user:       root@756261f4b8ec
  build date:       20170714-14:40:00
  go version:       go1.8.3

### What is the blackbox.yml module config.
modules:
  rabbit_alive:
    prober: http
    timeout: 30s
    http:
      no_follow_redirects: false
      method: GET
      preferred_ip_protocol: "ipv4"
      basic_auth:
        username: "user"
        password: "pass"
      fail_if_not_matches_regexp:
        - '{"status":"ok"}'

### What is the prometheus.yml scrape config.
  - job_name: rabbit_alive
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: /probe
    params:
      module: [rabbit_alive]
    ec2_sd_configs:
      - region: ap-southeast-1
        refresh_interval: 60s
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Type]
        regex: Rabbit
        action: keep
      - source_labels: [__meta_ec2_tag_Env]
        regex: Prod
        action: keep
      - source_labels: [__meta_ec2_instance_state]
        regex: running
        action: keep
      - source_labels: [__address__]
        regex: (.*)(:80)
        target_label: __param_target
        replacement: ${1}:15672/api/aliveness-test/%2F
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 127.0.0.1:9115

### What logging output did you get from the `blackbox_exporter`?
none

### What did you do that produced an error?
http://blackbox:9115/probe?target=http://rabbit:15672/api/aliveness-test/%2F&module=rabbit_alive

### What did you expect to see?
{"status":"ok"}
### What did you see instead?

404

as it said here:
https://stackoverflow.com/questions/13237628/rabbitmq-http-api-call-to-aliveness-test-returns-404-but-other-calls-work

so we need to add %2F after slash

i have tested with tcpdump on rabbit machine and i see that blackbox_exporter removes it
while curl doesn't

is there some workaround?

thanks

**Comment by brian-brazil** [comment]
That sounds like a buggy HTTP implementation on the part of rabbit, I'm not sure there's anything we can do on our side.

**Comment by yosefy** [comment]
kinda agree...
closing
