### ISSUE TITLE
My name is not "sure"

### ISSUE THREAD

**Issue by jj30** [prometheus/blackbox_exporter#229]
I am trying to get prometheus running with our customizations, which is how I got here. However, I am unable to 'make' or 'docker build' the blackbox_exporter. I'd venture that it's not a bug, but that it may be a common deployment issue for windows users.

When I run 'docker build -t blackbox_exporter .'

```
PS C:\Code_Develop\blackbox_exporter> docker build -t blackbox_exporter .
Sending build context to Docker daemon  4.556MB
Step 1/7 : FROM quay.io/prometheus/busybox:latest
latest: Pulling from prometheus/busybox
aab39f0bc16d: Extracting [==================================================>]  692.3kB/692.3kB
a3ed95caeb02: Download complete
2cd9e239cea6: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\d660a9c494e6f7730a1d29e107aafc30cae724b86d2ddf4b5d178ad973b106de: The system cannot find the path specified.
```

... which it really should say, since the specified subfolder in C:\ProgramData\Docker\windowsfilter does not exist.

I know that my Docker installation is ok, from my hello-world output.

```
PS C:\Code_Develop\Virtualization-Documentation\windows-server-container-tools> docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run a Windows Server container with:
 PS C:\> docker run -it microsoft/windowsservercore powershell

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
```

I ran something called Debug-ContainerHost, based on a suggestion I found when googling the above error (but for another docker image or container).

Here is that output.

[Debug-ContainerHost.txt](https://github.com/prometheus/blackbox_exporter/files/1307714/Debug-ContainerHost.txt)

You can see that it says something about 'elevation' (line 7). I am indeed running the powershell window as administrator.

Line 23 again with the '[I] do not have required permission' (I do).

I did not understand about the NAT (line 32).

Does anyone have any insight that may help me? Any help is appreciated.

**Comment by brian-brazil** [comment]
I don't think your problem is anything to do with Prometheus or the blackbox exporter, I think you'll get better help from a Docker on Windows forum.

**Comment by jj30** [comment]
Hello @brian-brazil, can I ask what makes you say that? I don't know the nature of the folders in C:\ProgramData\Dockers\windowsfilter. Could it be that blackbox_exporter is supposed to deploy something there?

Also, I did not expect a reply so quickly, so I have to ask you to read my edits. In particular, there is a section where I run docker 'hello world.' Wouldn't this mean that the problem isn't docker + windows?

Thanks

**Comment by brian-brazil** [comment]
I know nothing about how docker on windows works, nor is it something we really support. I can't help you with this, all I can say is that it works on a Unix system.

**Comment by thz** [comment]
Actually the Dockerfile looks like it is not building anything but just creating the docker image from a previously built blackbox_exporter binary: `COPY blackbox_exporter  /bin/blackbox_exporter`
For that reason the `README.md` is confusing by stating "building with docker".

This might cause your `The system cannot find the path specified.`
The rest of your questions leave me puzzled ;-)

With a Dockerfile like this:
```FROM golang:1.8 as buildstage
RUN mkdir -p /go/src/github.com/prometheus/blackbox_exporter
COPY . /go/src/github.com/prometheus/blackbox_exporter
ENV GOPATH=/go
RUN make -C /go/src/github.com/prometheus/blackbox_exporter build


FROM        quay.io/prometheus/busybox:latest
# MAINTAINER  The Prometheus Authors <prometheus-developers@googlegroups.com>

COPY --from=buildstage /go/src/github.com/prometheus/blackbox_exporter/blackbox_exporter /bin/blackbox_exporter
COPY blackbox.yml       /etc/blackbox_exporter/config.yml

EXPOSE      9115
ENTRYPOINT  [ "/bin/blackbox_exporter" ]
CMD         [ "--config.file=/etc/blackbox_exporter/config.yml" ]
```
You could actually build the binary and the image with one Dockerfile in two stages (requires recent docker).

**Comment by jj30** [comment]
I hear you, @brian-brazil. I bet I hate Microsoft more than you do. I run Linux Mint at home. The business world is a slave.

```
C:\Code_Develop\blackbox_exporter>docker build -t blackbox_exporter .
Sending build context to Docker daemon  4.557MB
Step 1/11 : FROM golang:1.8 as buildstage
1.8: Pulling from library/golang
no matching manifest for windows/amd64 in the manifest list entries
```
I have no idea what I'm doing.

**Comment by jj30** [comment]
After creating a default virtual machine with

`docker-machine --native-ssh create -d hyperv default`

Now the issue when 'building' with 

`docker build -t blackbox_exporter .`

is 

```
Sending build context to Docker daemon  4.557MB
Step 1/11 : FROM golang:1.8 as buildstage
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:50981->[::1]:53: read: connection refused

```
Trying stuff in 

https://github.com/moby/moby/issues/31510

.. had no effect.

**Comment by brian-brazil** [comment]
I don't think this issue is anything to do with us.
