### ISSUE TITLE
Version info is written to the stderr instead of stdout

### ISSUE THREAD

**Issue by hasso** [prometheus/blackbox_exporter#230]
blackbox_exporter from version 0.8.0 writes version info into stderr instead of stdout.

<pre>bash-3.2$ ./blackbox_exporter-0.7.0 -version
blackbox_exporter, version 0.7.0 (branch: master, revision: 9b67dd9b488160bb656cf130718b2aa62a7f30e6)
  build user:       root@756261f4b8ec
  build date:       20170714-14:40:36
  go version:       go1.8.3
bash-3.2$ ./blackbox_exporter-0.7.0 -version > /dev/null
bash-3.2$ ./blackbox_exporter-0.8.0 --version
blackbox_exporter, version 0.8.0 (branch: HEAD, revision: 6a3dfec5de88641dc19f199dcbeb53f62f4a3e98)
  build user:       root@27010337b9b1
  build date:       20170808-13:27:55
  go version:       go1.8.3
bash-3.2$ ./blackbox_exporter-0.8.0 --version > /dev/null
blackbox_exporter, version 0.8.0 (branch: HEAD, revision: 6a3dfec5de88641dc19f199dcbeb53f62f4a3e98)
  build user:       root@27010337b9b1
  build date:       20170808-13:27:55
  go version:       go1.8.3
bash-3.2$</pre>

**Comment by brian-brazil** [comment]
This is how the new kingpin library works for this functionality.
