### ISSUE TITLE
blackbox_exporter memory leak

### ISSUE THREAD

**Issue by pc10201** [prometheus/blackbox_exporter#236]
blackbox.yml is defalut

blackbox_exporter 0.9.1 increase memory by time.

blackbox_exporter 0.8.1 is not.

**Comment by SuperQ** [comment]
Would you please grab a pprof dump of the running process and attach it to this issue?  If you have both versions running, a dump of both would be useful.

```
go tool pprof -svg http://localhost:9115/debug/pprof/heap > heap.svg
```

**Comment by brian-brazil** [comment]
Have you performed a few hundred probes yet? Building up the probe history will look like a leak initially.

**Comment by pc10201** [comment]
yes.I have 400+ tcp probes.

**Comment by brian-brazil** [comment]
It's probably the history logic then.
