### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by hasso** [prometheus/blackbox_exporter#24]
- ICMP module is IPv4 only.
- While TCP/HTTP modules seem to support IPv6, it's unclear how the choice is made between IPv4 and IPv6. For monitoring it's often good idea to force to is it either one.

**Comment by RichiH** [comment]
For all of the blackbox_exporters, I would prefer to be able to force v4, v6, or v4 _and_ v6. Obviously, at least the last will need to have a label attached to avoid duplicates.
