### ISSUE TITLE
Document metric names and meanings exposed by the probers

### ISSUE THREAD

**Issue by reegnz** [prometheus/blackbox_exporter#241]
As a user, I would like to have a clear reference about what metrics each probe exposes and what each metric means.
To get to this information I currently either need to grok the source code.
It would be desirable to have documentation about it eg. in an .md file.

**Comment by Maxeh** [comment]
Is there still no documentation? There are so many commands and I just do not know what they are there for? How should I know, how all the probers work and what to do with them? Does someone has a cheat sheet?

**Comment by matclab** [comment]
Also see #166 and PR #663.

**Comment by reegnz** [comment]
This is still open? LOL!
I'm going to close this issue, I've given up hope years ago. Too many resistance from the maintainers for this to ever get proper traction... 
#663 just shows that usability is not a priority for this project. The documentation is **generated from the code** FFS.

Sad.
