### ISSUE TITLE
Feature request: SSL earliest certificate issue date

### ISSUE THREAD

**Issue by pracucci** [prometheus/blackbox_exporter#247]
As you may be aware, Google (first) and Mozilla (then) decided to distrust Symanted SSL certificates issued before a specific date.

I'm wondering if there's an interest to export a metric on the earliest certificate issue date in the blackbox exporter, in order to quickly get such information if you're already monitoring a large set of HTTPS endpoints.

I perfectly understand this request is probably far from being useful to the majority of people, that's why I would like to ask it before - in case - contributing with a PR.

Thank you,
Marco

**Comment by brian-brazil** [comment]
I'm not against exporting this, but I'm sure how this helps you. Can you go into more detail with an example chain?

**Comment by pracucci** [comment]
_The more I think about it, the less sense it makes (at least, it just cover a very specific use case that probably none else want to solve via this exporter)._

The original idea was exporting a metric per target whose label is the certificate issuer name (ie. `Symantec`) and the value the certificate issued date. You can then alert on issuer=~symantec and issued before `2016-01-01`: these are certificates that should be distrusted on `March 15, 2018`.

**Comment by brian-brazil** [comment]
That's something more custom alright, and as a cert chain is in principle unbounded probably not the best choice for a label. If you want to emulate a browser and it's semantics, you might want to look at something like https://github.com/mattbostock/webdriver_exporter
