### ISSUE TITLE
Verify certificate CRL/OCSP endpoints?

### ISSUE THREAD

**Issue by rgl** [prometheus/blackbox_exporter#248]
Can blackbox also monitor the CRL/OCSP endpoints embedded in the certificate? Is there a recommended way of doing so?

**Comment by brian-brazil** [comment]
This probably is best done via a separate tool, as among other things, Go doesn't support this.

**Comment by rgl** [comment]
I'm not asking for blackbox to actually validate the certificate against the CRL/OCSP, only the endpoints. That is, to verify that the CRL/OCSP endpoint are up, like blackbox already does for HTTP(S).

The CRL/OCSP endpoints are available in Go `Certificate.CRLDistributionPoints` and `Certificate.OCSPServer` properties.

**Comment by brian-brazil** [comment]
That sounds like a standard http probe.

**Comment by rgl** [comment]
Can the std probe get the endpoints from the Certificate.CRLDistributionPoints and Certificate.OCSPServer properties or you mean I should do that manually or with other tool?

**Comment by brian-brazil** [comment]
That's a service discovery question, which would likely mean file_sd on the Prometheus side.
