### ISSUE TITLE
dns module?

### ISSUE THREAD

**Issue by filippog** [prometheus/blackbox_exporter#25]
hi,
is a dns module something you'd be interested in having in blackbox exporter? if so I'm happy to take a stab at it using e.g. https://github.com/miekg/dns

thanks!

**Comment by brian-brazil** [comment]
What exactly is it that you want to test with the module?

**Comment by filippog** [comment]
I'm mainly interested in checking response time, rrdata for expected contents, possibly expected record type too

**Comment by RichiH** [comment]
@filippog Any update from your side? Basic DNS availability and matching of expected values would be quite handy to verify that things are working OK.

**Comment by grobie** [comment]
I'd also be interested in having a DNS blackbox test to ensure our internal DNS resolution works.

**Comment by RichiH** [comment]
I think splitting further into A, AAAA, MX, (just make it arbitrary), etc
and matching that specific result would be best.
That way we can see what specific part breaks, and still monitor the rest
on expected partial changes to one of them.

Richard

Sent by mobile; excuse my brevity.

**Comment by filippog** [comment]
@RichiH no updates, I haven't been able to find time to work on it. Ideas on how the module would look like though? IOW what to put on module configuration vs query string

**Comment by brian-brazil** [comment]
The DNS name gges in the query string, everything else is module config
