### ISSUE TITLE
Support for specifying TLS ciphers

### ISSUE THREAD

**Issue by mattbostock** [prometheus/blackbox_exporter#267]
blackbox_exporter exposes metrics for TLS certificate expiry.

It's possible to determine multiple TLS certificates for a service when not all clients are able to support a given cipher. For example, elliptical curve ciphers may be preferred where CPU cost is a concern with a fallback to RSA for older clients.

In order to properly monitor such configurations, it would be useful if the blackbox_exporter could specify the cipher(s) to use when negotiating TLS.

**Comment by brian-brazil** [comment]
This may be getting a bit specific and niche to add, as practically speaking what you're requesting is that Prometheus and all other components with TLS configuration support all potential TLS options. This may be the case for a custom exporter (or a small shell script on top of the openssl command line tool. If you've got that sort of setup, it's likely you want ciphers Go doesn't support).

**Comment by mattbostock** [comment]
> as practically speaking what you're requesting is that Prometheus and all other components with TLS configuration support all potential TLS options

Why? I think this can be constrained to the blackbox_exporter. It's like probing both IPv4 and IPv6.

Agree this is a little niche, but I think it makes sense to add to blackbox_exporter if it doesn't introduce too many new options or complexity.

Go supports the main ciphers, which are the ones I had in mind:
https://golang.org/pkg/crypto/tls/#pkg-constants

**Comment by brian-brazil** [comment]
> Why? I think this can be constrained to the blackbox_exporter. It's like probing both IPv4 and IPv6.

The relevant code is intended to be shared across the entire project, not just the blackbox exporter.

**Comment by brian-brazil** [comment]
Given there has only been one request for this, and how we're approaching things server side for TLS, I don't think this is something we'll be adding to all HTTP clients in Prometheus.

**Comment by klausenbusk** [comment]
One use-case for this is servers providing both a ECDSA and a RSA certificate (supported by ex nginx: https://scotthelme.co.uk/hybrid-rsa-and-ecdsa-certificates-with-nginx/). It is currently (AFAIK) not possible to monitor both certificates with blackbox_exporter.

**Comment by klausenbusk** [comment]
I did some research and opened a new issue for my use-case: https://github.com/prometheus/blackbox_exporter/issues/731
