### ISSUE TITLE
Support for HTTP headers as labels

### ISSUE THREAD

**Issue by bobrik** [prometheus/blackbox_exporter#268]
We probe certain HTTP endpoints to get timings. These endpoints hit local cache most of the time, but from time to time they have to fetch resources from the origin. This skews our metrics and we can't filter bogus datapoints in any way.

Endpoints return header indicating whether resource was fetched from local cache. They also provide other important information like upstream address, we'd like to have that too.

My suggestion is to add some mechanism that would allow us to do this filtering based on header.

**Comment by SuperQ** [comment]
What about setting a `Cache-Control: no-cache` header in your requests so you always hit the backend?  There is a header [example](https://github.com/prometheus/blackbox_exporter/blob/master/example.yml#L9-L11) config.

**Comment by bobrik** [comment]
@SuperQ, thing is: I want to measure cache performance, not origin performance.

**Comment by SuperQ** [comment]
Blackbox probes are not really good for that.  If you want to measure the cache performance, you probably want to get those metrics directly from the cache server itself.

**Comment by brian-brazil** [comment]
Returning the headers as labels back to Prometheus doesn't make much sense on cardinality grounds, that's getting more into event logging. Passing/failing a probe based on headers would make sense though.

**Comment by bobrik** [comment]
Failing probe on cache miss can solve "I only want cache hits", but it won't solve "I want to know which upstream responded".

**Comment by brian-brazil** [comment]
As Ben says, that's a bit out of scope for the blackbox exporter.
