### ISSUE TITLE
out of memory on make

### ISSUE THREAD

**Issue by Robertbaelde** [prometheus/blackbox_exporter#28]
It throws an out of memory option when i run the make command 
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x698ab0, 0x16)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sysMap(0xc824970000, 0x100000, 0x68b00, 0x7af258)
        /usr/local/go/src/runtime/mem_linux.go:143 +0x9b
runtime.mHeap_SysAlloc(0x790840, 0x100000, 0x0)
        /usr/local/go/src/runtime/malloc.go:423 +0x160
runtime.mHeap_Grow(0x790840, 0x8, 0x0)
        /usr/local/go/src/runtime/mheap.go:628 +0x63
runtime.mHeap_AllocSpanLocked(0x790840, 0x1, 0x2b4533105ce0)
        /usr/local/go/src/runtime/mheap.go:532 +0x5f1
runtime.mHeap_Alloc_m(0x790840, 0x1, 0x13, 0x2b4533105ce0)
        /usr/local/go/src/runtime/mheap.go:425 +0x1ac
runtime.mHeap_Alloc.func1()
        /usr/local/go/src/runtime/mheap.go:484 +0x41
runtime.systemstack(0xc820041e50)
        /usr/local/go/src/runtime/asm_amd64.s:278 +0xab
runtime.mHeap_Alloc(0x790840, 0x1, 0x10000000013, 0x40dde4)
        /usr/local/go/src/runtime/mheap.go:485 +0x63
runtime.mCentral_Grow(0x799258, 0x0)
        /usr/local/go/src/runtime/mcentral.go:190 +0x93
runtime.mCentral_CacheSpan(0x799258, 0x2b4533105ce0)
        /usr/local/go/src/runtime/mcentral.go:86 +0x4d4
runtime.mCache_Refill(0x2b4532e3f000, 0xc800000013, 0x2b4533105ce0)
        /usr/local/go/src/runtime/mcache.go:118 +0xcf
runtime.mallocgc.func2()
        /usr/local/go/src/runtime/malloc.go:611 +0x2b
runtime.systemstack(0xc820022000)
        /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82003ac00 sp=0xc82003abf8
runtime.mallocgc(0x140, 0x664640, 0x0, 0xc8200877c0)
        /usr/local/go/src/runtime/malloc.go:612 +0x842 fp=0xc82003acd0 sp=0xc82003ac00
runtime.newobject(0x664640, 0xc822063290)
        /usr/local/go/src/runtime/malloc.go:760 +0x42 fp=0xc82003acf8 sp=0xc82003acd0
cmd/link/internal/ld.readsym(0xc820072000, 0xc8248b38e0, 0xc820eb3270, 0xd, 0xc8248aa150, 0x6d)
        /usr/local/go/src/cmd/link/internal/ld/objfile.go:208 +0x76a fp=0xc82003b140 sp=0xc82003acf8
cmd/link/internal/ld.ldobjfile(0xc820072000, 0xc8248b38e0, 0xc820eb3270, 0xd, 0x34e38, 0xc8248aa150, 0x6d)
        /usr/local/go/src/cmd/link/internal/ld/objfile.go:147 +0xa56 fp=0xc82003b350 sp=0xc82003b140
cmd/link/internal/ld.ldobj(0xc8248b38e0, 0xc820eb3270, 0xd, 0x34e60, 0xc8248aa150, 0x6d, 0xc820fe4d90, 0x65, 0x1)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:1208 +0x14e1 fp=0xc82003b5b8 sp=0xc82003b350
cmd/link/internal/ld.objfile(0xc820fe4e70)
        /usr/local/go/src/cmd/link/internal/ld/lib.go:730 +0x10d5 fp=0xc82003b8c8 sp=0xc82003b5b8
cmd/link/internal/ld.loadlib()
        /usr/local/go/src/cmd/link/internal/ld/lib.go:482 +0x5ce fp=0xc82003b9f0 sp=0xc82003b8c8
cmd/link/internal/ld.Ldmain()
        /usr/local/go/src/cmd/link/internal/ld/pobj.go:212 +0x1c4c fp=0xc82003be70 sp=0xc82003b9f0
cmd/link/internal/amd64.Main()
        /usr/local/go/src/cmd/link/internal/amd64/obj.go:44 +0x19 fp=0xc82003be78 sp=0xc82003be70
main.main()
        /usr/local/go/src/cmd/link/main.go:26 +0x189 fp=0xc82003bf50 sp=0xc82003be78
runtime.main()
        /usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc82003bfa0 sp=0xc82003bf50
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82003bfa8 sp=0xc82003bfa0
make: **\* [blackbox_exporter] Error 2

**Comment by brian-brazil** [comment]
How much memory do you have, and what does `/usr/bin/time make` say?
