### ISSUE TITLE
Would like to be able to see the complete HTTP request in debug logs

### ISSUE THREAD

**Issue by malcolmr** [prometheus/blackbox_exporter#280]
Debugging some issues would be a lot simpler if the debug logs contained the actual HTTP requests that were being made.

Ideally I'd like to see something like the `curl` output shown in #279: the complete HTTP request and the response status and headers, for each requests made by the prober. Whether this should be included by default in `&debug=true` output, or require another option, I'm not sure.

**Comment by brian-brazil** [comment]
We can't share the complete request and likely also the response, as depending on the service in question it may contain secrets.

**Comment by malcolmr** [comment]
Presumably only if `basic_auth` or one of the bearer token options was set in the module configuration? In the general case, the HTTP request should be deterministic based on the config and target, both of which are already accessible to anyone who can see the debug logs.

Or are you thinking that HTTP response headers might contain secrets? (I guess I could construct a situation where someone with access to the debug logs wouldn't also have access to replay the request manually.)

I suspect that most people don't have secrets in their prober request/response headers, though. Would it be reasonable to require a separate command-line flag to enable this, akin to Prometheus's `--web.enable-lifecycle`?

**Comment by brian-brazil** [comment]
> Presumably only if basic_auth or one of the bearer token options was set in the module configuration?

Yes, for the request. We promise not to expose those.

> Or are you thinking that HTTP response headers might contain secrets? 

Yes, that's going to be fairly common any time there's auth going on.

> I guess I could construct a situation where someone with access to the debug logs wouldn't also have access to replay the request manually.

It's expected that untrusted users will have access to the exporter's HTTP interface.


There's always tcpdump.

**Comment by malcolmr** [comment]
tcpdump doesn't work very well when the request is HTTPS, though, as it was here.

**Comment by brian-brazil** [comment]
Not much we can do here.
