### ISSUE TITLE
target_groups should be renamed to static_configs

### ISSUE THREAD

**Issue by wernight** [prometheus/blackbox_exporter#281]
Since Prometheus 0,20 it seems that `target_groups` has been renamed, see
https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md#0200--2016-06-15

However the README on https://hub.docker.com/r/prom/blackbox-exporter/ shows `target_groups` in the sample config.

**Comment by SuperQ** [comment]
I replaced the copy-n-paste of the README.md with a link to avoid it getting stale.
