### ISSUE TITLE
support regexes in /probe

### ISSUE THREAD

**Issue by adamdecaf** [prometheus/blackbox_exporter#291]
Looking through the [`/probe`](https://github.com/prometheus/blackbox_exporter/blob/v0.11.0/main.go#L61) handler there doesn't seem to be support for a regex check. I'd like to be able to use `fail_if_matches_regexp`/`fail_if_not_matches_regexp` from `/probe?target=1.2.3.4`.

I can see a sprawl of query params turned into yaml attributes if this isn't handled well, but would y'all be open to figuring out some solution for this?

**Comment by brian-brazil** [comment]
fail_if_matches_regexp is how this is supported for HTTP, configuration from modules only comes from the file.

**Comment by adamdecaf** [comment]
Does that mean all http probes would need to match the regex in `fail_if_not_matches_regexp`? I'd only want a few probes to match on a regex.

**Comment by brian-brazil** [comment]
You can create different modules with different configurations.

**Comment by adamdecaf** [comment]
Ah. I see now. I can add custom modules in `config.yaml` Thanks.
