### ISSUE TITLE
Basic auth information are displayed in url tag

### ISSUE THREAD

**Issue by athoune** [prometheus/blackbox_exporter#292]
When I query a blackbox's probe with basic auth, login and password are displayed in the url tag.

Replacing password with '***' should be more secure.

**Comment by brian-brazil** [comment]
Can you indicate where exactly you are seeing this? Basic auth passwords should be hidden.

**Comment by athoune** [comment]
Hum, I just check with curl. blackbox_exporter is clean, the guilty is telegraf's prometheus input.

Sorry for the noise.
