### ISSUE TITLE
dnsname as parameter

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/blackbox_exporter#296]
feature request.

I would love to see DNS name as parameter of /probe.

**Comment by brian-brazil** [comment]
Can you be more specific? Which probe type? How would it be used?

**Comment by roidelapluie** [comment]
The query_name of the DNS probe. Would be used to check if the some DNS names are working.

**Comment by brian-brazil** [comment]
You need to have a module per query_name, and modules are explicitly configured only from the config file.

**Comment by roidelapluie** [comment]
OK. That is what I do now but I wanted to write a filesd integration for it.
