### ISSUE TITLE
go 1.10 bug On Windows, the ReadFrom and WriteTo methods of RawConn are not implemented.

### ISSUE THREAD

**Issue by birdie7761** [prometheus/blackbox_exporter#301]
https://github.com/golang/net/blob/release-branch.go1.10/ipv4/packet.go
// BUG(mikio): On Windows, the ReadFrom and WriteTo methods of RawConn
// are not implemented.

blackbox_exporter.exe --log.level=debug
ts=2018-03-06T09:28:05.3332264Z caller=main.go:174 module=ping target=x.x.x.x level=debug msg="Error writing to socket" err="write ip 0.0.0.0->x.x.x.x: raw-write ip4 0.0.0.0: not implemented"

blackbox_exporter.exe --version
blackbox_exporter, version 0.12.0 (branch: HEAD, revision: 4a22506cf0cf139d9b2f9cde099f0012d9fcabde)
  build user:       root@634195974c8e
  build date:       20180227-11:52:09
  go version:       go1.10

**Comment by avonwyss** [comment]
@birdie7761 I'm facing the same problem. Do you have a solution, or why did you close the issue?
