### ISSUE TITLE
Issue with IPv6 addresses

### ISSUE THREAD

**Issue by DavidJeche** [prometheus/blackbox_exporter#304]
### Host operating system: output of `uname -a`

Linux f01a0a17c3e6 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`
blackbox_exporter, version 0.12.0 (branch: HEAD, revision: 4a22506cf0cf139d9b2f9cde099f0012d9fcabde)
  build user:       root@634195974c8e
  build date:       20180227-11:50:29
  go version:       go1.10

### What is the blackbox.yml module config.

modules:
  https_2xx:
    prober: http
    http:
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  http_2xx_v6:
    prober: http
    http:
      preferred_ip_protocol: "ip6"

### What is the prometheus.yml scrape config.

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://www.unixdaemon.net
        - https://www.france.com
        - https://www.zenko.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

These generally work fine since they all revert to ipv6 addresses.

### What logging output did you get from adding `&debug=true` to the probe URL?

ts=2018-03-09T17:29:55.305690696Z caller=main.go:116 module=http_2xx_v6 target=https://www.google.co.uk level=info msg="Beginning probe" probe=http timeout_seconds=9.5
ts=2018-03-09T17:29:55.30587632Z caller=utils.go:42 module=http_2xx_v6 target=https://www.google.co.uk level=info msg="Resolving target address" preferred_ip_protocol=ip6
ts=2018-03-09T17:29:55.308359353Z caller=utils.go:65 module=http_2xx_v6 target=https://www.google.co.uk level=info msg="Resolved target address" ip=2a00:1450:4005:800::2003
ts=2018-03-09T17:29:55.308406935Z caller=http.go:282 module=http_2xx_v6 target=https://www.google.co.uk level=info msg="Making HTTP request" url=https://[2a00:1450:4005:800::2003] host=www.google.co.uk
ts=2018-03-09T17:29:55.308585453Z caller=http.go:297 module=http_2xx_v6 target=https://www.google.co.uk level=error msg="Error for HTTP request" err="Get https://[2a00:1450:4005:800::2003]: dial tcp [2a00:1450:4005:800::2003]:443: connect: cannot assign requested address"
ts=2018-03-09T17:29:55.308613368Z caller=http.go:354 module=http_2xx_v6 target=https://www.google.co.uk level=info msg="Response timings for roundtrip" roundtrip=0 start=2018-03-09T17:29:55.308499437Z dnsDone=2018-03-09T17:29:55.308499437Z connectDone=2018-03-09T17:29:55.308559456Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=2018-03-09T17:29:55.30858098Z
ts=2018-03-09T17:29:55.308643204Z caller=main.go:129 module=http_2xx_v6 target=https://www.google.co.uk level=error msg="Probe failed" duration_seconds=0.002829006

### What did you do that produced an error?

curl "http://127.0.0.1:8885/probe?target=https://www.google.co.uk&module=http_2xx_v6&debug=true"

### What did you expect to see?

At least I expected to see probe success. 

# TYPE probe_success gauge
probe_success 1

### What did you see instead?

# TYPE probe_success gauge
probe_success 1

**Comment by brian-brazil** [comment]
You don't have a working v6 setup.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by marji** [comment]
Similar (dupe?) to #105 , which has more info.
