### ISSUE TITLE
Not able to build the image

### ISSUE THREAD

**Issue by ashish235** [prometheus/blackbox_exporter#305]
Hi, 

I 'm trying to build the image by cloning this git repo. When I try to build I 'm getting buile failure. Reason being "COPY blackbox_exporter  /bin/blackbox_exporter" and there is no file or directory present with the name  blackbox_exporter.

> 
> ubuntu@ip-172-31-5-21:~/blackbox_exporter$ sudo docker build -t blackbox_exporter .
> Sending build context to Docker daemon  13.57MB
> Step 1/7 : FROM        quay.io/prometheus/busybox:latest
>  ---> 747e1d7f6665
> Step 2/7 : MAINTAINER  The Prometheus Authors <prometheus-developers@googlegroups.com>
>  ---> Using cache
>  ---> f544eae4cf05
> Step 3/7 : COPY blackbox_exporter  /bin/blackbox_exporter
> COPY failed: stat /var/lib/docker/tmp/docker-builder226161324/blackbox_exporter: no such file or directory

**Comment by brian-brazil** [comment]
The dockerfile is for the use of our own tooling, if you want to use it you must first build the blackbox exporter.
