### ISSUE TITLE
Blackbox console assumes http_2xx module is defined

### ISSUE THREAD

**Issue by jamtur01** [prometheus/blackbox_exporter#307]
The default console:

![screenshot from 2018-03-31 12-32-38](https://user-images.githubusercontent.com/4365/38165331-ae6fe364-34df-11e8-9810-33dde54a6f65.png)

Assumes a module called http_2xx exists in the blackbox configuration. This might be confusing for folks who assume this would just work. What would folks think of removing this?

**Comment by brian-brazil** [comment]
I think this makes it easier to get up and running with the default config, so I'm not inclined to remove it.

**Comment by jamtur01** [comment]
Sure. I can see that. Just think it's very weird to hard-code a link to config that isn't hard-coded inside a console. Very non-intuitive behavior IMHO. :)
