### ISSUE TITLE
On Windows, IPv4 ICMP fails but IPv6 ICMP succeeds

### ISSUE THREAD

**Issue by avonwyss** [prometheus/blackbox_exporter#314]
### Host operating system
Windows 2016 Datacenter, Version 1607, Build 14393.2189

### blackbox_exporter version
version=0.12.0, branch=HEAD, revision=4a22506cf0cf139d9b2f9cde099f0012d9fcabde

### What is the blackbox.yml module config.
Unchanged from release package.

### What logging output did you get from adding `&debug=true` to the probe URL?
```
ts=2018-04-24T09:29:59.1632814Z caller=main.go:116 module=icmp target=172.21.100.2 level=info msg="Beginning probe" probe=icmp timeout_seconds=9.5
ts=2018-04-24T09:29:59.1632814Z caller=utils.go:42 module=icmp target=172.21.100.2 level=info msg="Resolving target address" preferred_ip_protocol=ip6
ts=2018-04-24T09:29:59.1632814Z caller=utils.go:52 module=icmp target=172.21.100.2 level=warn msg="Resolution with preferred IP protocol failed, attempting fallback protocol" fallback_protocol=ip4 err="address 172.21.100.2: no suitable address found"
ts=2018-04-24T09:29:59.1632814Z caller=utils.go:65 module=icmp target=172.21.100.2 level=info msg="Resolved target address" ip=172.21.100.2
ts=2018-04-24T09:29:59.1632814Z caller=icmp.go:71 module=icmp target=172.21.100.2 level=info msg="Creating socket"
ts=2018-04-24T09:29:59.1720999Z caller=icmp.go:117 module=icmp target=172.21.100.2 level=info msg="Creating ICMP packet" seq=24 id=2072
ts=2018-04-24T09:29:59.1720999Z caller=icmp.go:129 module=icmp target=172.21.100.2 level=info msg="Writing out packet"
ts=2018-04-24T09:29:59.1720999Z caller=icmp.go:139 module=icmp target=172.21.100.2 level=warn msg="Error writing to socket" err="write ip 0.0.0.0->172.21.100.2: raw-write ip4 0.0.0.0: not implemented"
ts=2018-04-24T09:29:59.1720999Z caller=main.go:129 module=icmp target=172.21.100.2 level=error msg="Probe failed" duration_seconds=0.0088184

```
### What did you expect to see?
Probe successful

### What did you see instead?
Probe failed

### Additional info
Tried running the exporter as local service, network service, domain admin, the error is always the same. It even fails for the localhost address 127.0.0.1. The same exporter instance can, however, successfully ping IPv6 targets:
```
ts=2018-04-24T09:44:13.4871333Z caller=main.go:116 module=icmp target=2a00:1450:400a:806::2003 level=info msg="Beginning probe" probe=icmp timeout_seconds=9.5
ts=2018-04-24T09:44:13.4871333Z caller=utils.go:42 module=icmp target=2a00:1450:400a:806::2003 level=info msg="Resolving target address" preferred_ip_protocol=ip6
ts=2018-04-24T09:44:13.4871333Z caller=utils.go:65 module=icmp target=2a00:1450:400a:806::2003 level=info msg="Resolved target address" ip=2a00:1450:400a:806::2003
ts=2018-04-24T09:44:13.4871333Z caller=icmp.go:71 module=icmp target=2a00:1450:400a:806::2003 level=info msg="Creating socket"
ts=2018-04-24T09:44:13.4871333Z caller=icmp.go:117 module=icmp target=2a00:1450:400a:806::2003 level=info msg="Creating ICMP packet" seq=963 id=2072
ts=2018-04-24T09:44:13.4881269Z caller=icmp.go:129 module=icmp target=2a00:1450:400a:806::2003 level=info msg="Writing out packet"
ts=2018-04-24T09:44:13.4881269Z caller=icmp.go:157 module=icmp target=2a00:1450:400a:806::2003 level=info msg="Waiting for reply packets"
ts=2018-04-24T09:44:13.5049861Z caller=icmp.go:177 module=icmp target=2a00:1450:400a:806::2003 level=info msg="Found matching reply packet"
ts=2018-04-24T09:44:13.5049861Z caller=main.go:127 module=icmp target=2a00:1450:400a:806::2003 level=info msg="Probe succeeded" duration_seconds=0.0178529
```

This seems to be the same as/similar to issue #301 but that one was closed without additional information.

**Comment by avonwyss** [comment]
@brian-brazil I hope you don't mind me pinging you for this issue. This problem effectively prevents getting IPv4 ICMP to work on Windows, which seems like a major bug to me (and it is a killer since it prevents monitoring IPv4 device availability). Who could have a look at it?

**Comment by brian-brazil** [comment]
I'm afraid I'm not a Windows person, so you'd need to find someone who has Go networking experience on Windows. I suspect this one will require work inside Go itself.

**Comment by avonwyss** [comment]
Thank you for the reply. From my googling around I wonder if all that is needed may be to to replace the raw packet `NewRawConn` with a `IPv4PacketConn` (analogous to the IPv6 ICMP code), which would not really be a Windows-specific (or Go) code change. I'd be happy to test the result on Windows if that helps.

**Comment by avonwyss** [comment]
If Don't Fragment support is vital, why not use the raw connection code only when this option is set, and the "native" IPv4PacketConn otherwise? Not having DF support on Windows can be documented and feels like a non-issue to me. Also this may (or may not) help towards implementing #147 if I read the docs correctly.

**Comment by avonwyss** [comment]
I have tried to make code adjustments but I cannot get it to build locally (on Windows):
`.\main.go:124:19: cannot use registry (type *"github.com/prometheus/client_golang/prometheus".Registry) as type *"github.com/prometheus/blackbox_exporter/vendor/github.com/prometheus/client_golang/pro
metheus".Registry in argument to prober`

Since there are no artifacts in the TravisCI and CircleCI builds I have no idea how I can actually try my changes. And having zero Go experience I'm also completely lost with that error message and vendoring stuff.

**Comment by brian-brazil** [comment]
That sounds like your Go environment isn't setup correctly. See https://github.com/golang/go/wiki/SettingGOPATH#windows

**Comment by avonwyss** [comment]
@brian-brazil I did follow the instructions and do have a GOPATH pointing to a valid dir and `go get` did add a bunch of stuff into the pkg and src in that folder. What I did not get is how the workspace is related to the cloned repo folder which was outside the GOPATH folder. Building from inside the `src` folder seems to work, it's all pretty confusing for me...

**Comment by brian-brazil** [comment]
You'll want to work entirely inside the GOPATH, so move the clone repo inside there to the appropriate directory.

**Comment by avonwyss** [comment]
Thanks, wish I'd known that before... ;) Created PR #329

**Comment by timlharrison** [comment]
Will this be in a release at some point soon? This is preventing me from using ICMP on Windows 2016.

**Comment by avonwyss** [comment]
@timlharrison Here's my personal build if you're interested:
[blackbox_exporter.zip](https://github.com/prometheus/blackbox_exporter/files/2470968/blackbox_exporter.zip)

**Comment by timlharrison** [comment]
@avonwyss thanks very much.  I'm using tcp_connect as a workaround, but I'm worried at some point that wont work for me.  Is there any release schedule or anything for this project? I'm new to Prometheus.
