### ISSUE TITLE
blackbox log issue

### ISSUE THREAD

**Issue by maplewf** [prometheus/blackbox_exporter#319]
### Host operating system: output of `uname -a`
Linux xxxx 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`
blackbox_exporter, version 0.11.0 (branch: HEAD, revision: 200181ba84e595570eeed8cb1848491d3d4f85f0)
  build user:       root@3db6abb4b9fb
  build date:       20171128-13:47:58
  go version:       go1.9.2

### What is the blackbox.yml module config.

> modules:
  icmp:
    timeout: 5s
    prober: icmp
    icmp:
      preferred_ip_protocol: "ip4"

### What is the prometheus.yml scrape config.

>   - job_name: 'probe_info@test'
    # using blackbox_exporter
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 10.12.0.12
        labels:
          target_name: 'test'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

### Problem description 
Hi, 

I just upgrade blackbox exporter from 0.8.1 to 0.11.0 recently, and found that the log generated from new version is different from old version and became unexpected. Let me take example for you: 

the log level is info, and there is ping failure happened.

in 0.8.1, the log is 
`time="2018-05-06T21:18:42+08:00" level=warning msg="Timeout reading from socket for 10.12.0.12: read ip4 0.0.0.0: i/o timeout" source="icmp.go:112"`

but in 0.11.0, there is no ping failure log like above under info log level, unless I set the log level with debug, then I can get log below:
`ts=2018-05-06T12:29:57.546962927Z caller=main.go:174 module=icmp target=10.12.0.12 level=debug msg="Timeout reading from socket" err="read ip4 0.0.0.0: i/o timeout"`

I just wonder if this behavior change for log is expected? And I actually tried the latest version (0.12.0), it's same as 0.11.0. I think old version is more reasonable and helpful for troubleshooting.

Besides, I found that the timestamp in log of new version is only using UTC time, even I set the time zone to others, but there is no problem in old version.

Could you help to check it? Thanks in advance.

**Comment by brian-brazil** [comment]
This is expected, we changed log libraries and how debug logging was done. In general Prometheus only does UTC, and we don't make any promises about how our log messages will be worded.

**Comment by maplewf** [comment]
Hi Brian,

From the code below, it seems still want to use warning level to log this message but it turn out that it's only logged in debug level though, I'm just little confused, but thanks for your reply anyway.

> 			if nerr, ok := err.(net.Error); ok && nerr.Timeout() {
				level.Warn(logger).Log("msg", "Timeout reading from socket", "err", err)
				return
			}

**Comment by brian-brazil** [comment]
That's expected, it's a warning within the context of that specific probe but in terms of the exporter itself it's debug information.
