### ISSUE TITLE
Amount of retry for icmp [feature request]

### ISSUE THREAD

**Issue by do11** [prometheus/blackbox_exporter#320]
Please allow to specify number of retries of requests for icmp probing. It's beneficial, because icmp sometimes lost (dropped by traffic policer for example) and in that case `probe_success` is 0, which is fluctuation.

It's common to have retry amount of 3. (For example in `fping`).

**Comment by SuperQ** [comment]
This is an interesting idea, but I'm not sure it makes sense for the blackbox_exporter.  The exporter specifically does single probes, and reports on the success or failure of that single probe.

For ICMP monitoring, I typically do a very high scrape rate, say 1 second.  Then I use recording rules to generate summaries of the probes every 30 seconds.

This allows me to get full detailed information on each probe, and things like `avg_over_time(probe_success[30s])` to figure out packet loss.

**Comment by brian-brazil** [comment]
As Ben says, this doesn't really make sense for the blackbox exporter. You can always adjust your alerting threshold to tolerate a few failures, and in fact retries would hide failures and make latency numbers harder to interpret.

**Comment by andreymal** [comment]
There is a case where packet loss and latency info are not important, I just need to check if some instance is online. I don't want to flood Prometheus with unneccessary metrics and then filter them out by aggregate functions like `avg_over_time`, I just want to retry ping if a previous one was lost. I deliberately want to hide failures.

This also applies to dns probe.

(But it seems I'll have to fork blackbox_exporter for this case...)

**Comment by LastStupid** [comment]
Hi, same for me. i got more than 3k device too look at, every 1 minute, I cannot set alert on offline because there is too mutch false positive (probe_success == 0). 
Event increase polling to 2 minutes, 5% of the devices return 0 randomly, (timout 30s) 

Any formula with changes() are not working
Could be great to set  "retry: 2"
                                  "waitForRetry: 10s"

Thanks
