### ISSUE TITLE
Alternate DNS probe mode: specify DNS server in config, target contains domain name to resolve

### ISSUE THREAD

**Issue by avonwyss** [prometheus/blackbox_exporter#331]
## Proposal
**Use case. Why is this important?**
Currently, for each DNS domain to check a separate module has to be configured with a `query_name` set. This is good for checking if some DNS servers work correctly.

However, I'd like to check if my domain names resolve correctly publicly, e.g. using 8.8.8.8 or some other single DNS server.

If I could specify either `query_name` or `server_name` (exact parameter name open for discussion), the blackbox exporter could use the target for the complementing value. This would allow me to efficiently implement the domain name checks against one server per module.

**Comment by brian-brazil** [comment]
The purpose of the DNS probe is to test individual DNS servers, not queries. This is the same as for all the other probes - you pass the name of the target which is to be talked to.

If you're looking to test whether a DNS name is generally resolvable, you'd be best off using a tcp/http/icmp probe which will test that and more.

**Comment by avonwyss** [comment]
I want to test DNS resolution, not a DNS server. As you said tcp/http/icmp do more than that - I don't want to test connectivity to the actual server.

**Comment by brian-brazil** [comment]
You'll need a module per potential query then. It's by design not possible to adjust module configuration via HTTP, as that'd be unmanageable in general and lead to the blackbox exporter being an open proxy.

**Comment by ilyaglow** [comment]
Does blackbox exporter necessary imply the fact that anyone in the world is able to get metrics from it? I have similar tasks as @avonwyss, but I'd like to monitor probably tens of new hosts and different dns records per day and it seems unfeasible to manage the config file by just editing it every time.

**Comment by TangTHL** [comment]
> Does using blackbox exporter necessary imply the fact that anyone in the world should be able to get metrics from it? I have similar tasks as @avonwyss, but I'd like to monitor probably tens of new hosts and different dns records per day and it seems unfeasible to manage the config file by just editing it every time.

====
hi. i have same tasks as you too.  have you solved this probelm in an elegant way ?
