### ISSUE TITLE
Add metrics for actual content length returned for http

### ISSUE THREAD

**Issue by slyall** [prometheus/blackbox_exporter#337]
### Host operating system: output of `uname -a`

Linux prometheus.darkmere.gen.nz 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.12.0 (branch: HEAD, revision: 4a22506cf0cf139d9b2f9cde099f0012d9fcabde)
  build user:       root@634195974c8e
  build date:       20180227-11:50:29
  go version:       go1.10

### What is the blackbox.yml module config.

  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: ip4

### What is the prometheus.yml scrape config.

n/a

### What logging output did you get from adding `&debug=true` to the probe URL?

No change

### What did you do that produced an error?

Tested against various websites. Dozens

### What did you expect to see?

A number that matched the size of the content being returned  or -1 if the query was to a redirect.

### What did you see instead?

Almost all sites returned -1. I did find one site that worked ( http://www.newzealandchess.co.nz) and I think this worked because gzip compression is turned off there. It works for both http and https.

I tried this config to turn off http compression

  http_2xx_test:
    prober: http
    http:
      preferred_ip_protocol: ip4
      headers:
        Accept-Encoding: none

and now more sites work (such as my site https://www.darkmere.gen.nz and https://twitter.com ) but some still sites don't ( https://prometheus.io ) . I think with the compression turned off the sites that work are the ones that return an explicit "Content-Length" header.

**Comment by brian-brazil** [comment]
This metric works off the Content-Length header, and without that Go set it to -1. See https://golang.org/pkg/net/http/#Response

**Comment by slyall** [comment]
This seems to be the main problem. Content length is removed when compression is present (which is true in 99% of all web queries).

From that the library page:
``
        // Uncompressed reports whether the response was sent compressed but
        // was decompressed by the http package. When true, reading from
        // Body yields the uncompressed content instead of the compressed
        // content actually set from the server, ContentLength is set to -1,
        // and the "Content-Length" and "Content-Encoding" fields are deleted
        // from the responseHeader. To get the original response from
        // the server, set Transport.DisableCompression to true.
        Uncompressed bool

Do you think this is worth reporting as a bug to the library since it is explicit behavior?

**Comment by brian-brazil** [comment]
The original content-length wouldn't be much use I think, as it'd be the compressed length.

**Comment by jeremybz** [comment]
We're being hit by this as well.  What's the right way forward?  Should we add something like  `response_http_compressed_length` and `response_http_uncompressed_length`?

**Comment by brian-brazil** [comment]
Something like that sounds like an idea, though I'm not sure how much Go gives us to work with.

**Comment by jacekn** [comment]
It may also be useful to allow users to disable compression in the module config:
```
modules:
  http_no_compression:
    prober: http
    http:
      disable_compression: true
```
But since most http requests will use compression I think it's better to add support for it by exposing 2 new metrics like @jeremybz suggested.
