### ISSUE TITLE
Add parameter to specify http proxy

### ISSUE THREAD

**Issue by Jean-Daniel** [prometheus/blackbox_exporter#34]
Hello,

I'm trying to add a blackbox probe to test the availability of an http proxy. The http module could be perfect for such task if it was possible to pass a proxy URL in parameter.

It would be helpful to be able to do:

http://blackbox:9115/probe?target=http://example.com&proxy=http://myproxy:3128&module=http_2xx

Or simply being able to define a proxy in the module configuration and do:

http://blackbox:9115/probe?target=http://example.com&module=http_2xx_proxy

I can workaround that limitation by launching an instance of the blackbox exporter for each proxy I need to test (using the HTTP_PROXY env var to set the proxy), but it would be cleaner to have a single blackbox exporter instance for all checks.

**Comment by brian-brazil** [comment]
Any parameters would go via the configuration file, as the urls would get too crazy otherwise.

Right now you'd have to use the tcp module, but I'd accept a PR to add generic proxy functionality. This should probably also consider the possibility of socks proxies for tcp etc.

**Comment by lausser** [comment]
Would this one be the right way to go? 
[https://github.com/lausser/blackbox_exporter/commit/9a04f098bac0872adfeb89497f34454c78b7e379](url)
Tested with http- and socks-proxies, seems fine so far. When you say "generic proxy functionality", would this mean, that copying the socks part to tcp.go and introducing the proxy-config-settinh for tcp is enough?

**Comment by brian-brazil** [comment]
That's the basic idea. Prometheus also has a proxy option, so this logic and the naming should be shared.

**Comment by poblin-orange** [comment]
Any update on proxy support ?

**Comment by pj42** [comment]
I couldn't get the HTTP_PROXY environment variables to be used by blackbox_exporter myself even though Jean-Daniel's opening comment says that he was able to use them?

I managed to fix this for myself by adding http.ProxyFromEnvironment into client.Transport in http.go, i.e. line 125 now reads:

        client.Transport = &http.Transport{
                TLSClientConfig: tlsconfig,
                Dial:            dial,
                Proxy:           http.ProxyFromEnvironment,
        }

**Comment by Jean-Daniel** [comment]
@pj42 In fact, I never tried to use HTTP_PROXY. This was just an hypothetical workaround suggestion.
I'm using a patched version that support proxy configuration. My patch is tailored for my specific need and is not generic enough to become a PR though. That'w why I never proposed it.

**Comment by pj42** [comment]
Ok well support for HTTP_PROXY (and NO_PROXY) now working well for me. Commit is here: 

https://github.com/pj42/blackbox_exporter/commit/a07d586a96faa257d2ef1b59feda1855e387222e

**Comment by pj42** [comment]
My pull request for this now merged in the main code-base.

https://github.com/prometheus/blackbox_exporter/commit/1b3a6db3c07f29b59a17a2c09b4703db3e6a3f06

Can now do:

HTTP_PROXY="http://proxy-host:8080" NO_PROXY=".mydomain" ./blackbox_exporter

Enjoy :-)

**Comment by tux21b** [comment]
I have needed a similar setting and created https://github.com/prometheus/blackbox_exporter/pull/129 . Feel free to continue from there or let me know if I should change something.

**Comment by pj42** [comment]
Hey.

This pull request is not necessary, http_proxy support has been added to blackbox_exporter since v0.4.0

See notes at top of https://github.com/prometheus/blackbox_exporter/releases/tag/v0.4.0

[FEATURE] HTTP support taking proxy from enviroment

Cheers,
 Paul.

**Comment by tux21b** [comment]
@pj42 This pull requests builds on the functionality from the v0.4.0 branch and adds an additional `http_proxy` setting to the http probe config to specify a proxy server that takes precedence over the environment variables if specified.

My current use-cases requires me to monitor most of the services directly (no proxy) as well as several proxy servers (different proxy settings).

**Comment by pj42** [comment]
Ah ok then yes makes sense if you require more than one different proxy server to be used by a single running blackbox exporter.

**Comment by brian-brazil** [comment]
This was just added.
