### ISSUE TITLE
Don't try ipv6 if there is no ipv6 available

### ISSUE THREAD

**Issue by ptman** [prometheus/blackbox_exporter#342]
### Host operating system: output of `uname -a`
https://hub.docker.com/r/prom/blackbox-exporter/

### blackbox_exporter version: output of `blackbox_exporter -version`
```
blackbox_exporter, version 0.12.0 (branch: HEAD, revision: 4a22506cf0cf139d9b2f9cde099f0012d9fcabde)
  build user:       root@634195974c8e
  build date:       20180227-11:50:29
  go version:       go1.10
```

### What is the blackbox.yml module config.
The default.

### What logging output did you get from adding `&debug=true` to the probe URL?
    ts=2018-07-21T10:55:17.532698702Z caller=icmp.go:139 module=icmp target=::1 level=warn msg="Error writing to socket" err="write ip6 ::->::1: sendto: cannot assign requested address"

### What did you do that produced an error?

By default docker doesn't enable ipv6 for containers. The default for preferred_ip_protocol is 'ip6'. If the environment which blackbox exporter runs in doesn't have any ipv6 address, even ::1, it really shouldn't even try to connect via ipv6.

### What did you expect to see?

    probe_success 1

### What did you see instead?

    probe_success 0

**Comment by brian-brazil** [comment]
Magic behaviour can be confusing, so we always consistently prefer ipv6. If you want to do v4, you need to configure it.

**Comment by SuperQ** [comment]
The reason this report was filed was due to the target being resolved was `localhost` from /etc/hosts, which on their system resolves to `::1`. Since /etc/hosts does not resolve both A and AAAA results, there's no v4 to fall back to.

**Comment by brian-brazil** [comment]
I'm not quite following, the only thing we can do in this case is fail as the v6 probe that was requested cannot work. If you had requested a v4 probe it'd work in this, and I have verified this previously.

**Comment by ptman** [comment]
I didn't start by trying localhost. I also tried hosts on the open Internet with both A and AAAA records. The software should recognize when ipv6 has no chance of working and try ipv4 instead. I seems that docker by default sets sysctl net.ipv6.conf.all.disable_ipv6 = 1. Or maybe just the default docker config should have preferred_ip_protocol ip4, but that would be more of a patch than a fix.

**Comment by SuperQ** [comment]
If you state in the config, preferred ip6, and ip6 fails, I would say this is working as intended.

**Comment by ptman** [comment]
Do you see why the default config, which prefers ipv6, combined with docker, which by default disables ipv6, results in a less than stellar user experience?

**Comment by brian-brazil** [comment]
The defaults should not vary based on the detected environment, that'd be
confusing and make support more difficult as different configs would do
different things.

**Comment by ptman** [comment]
@brian-brazil And by defaults do you mean the defaults built into the binary? Or those in the packaged config file: https://github.com/prometheus/blackbox_exporter/blob/master/Dockerfile#L5 ?

**Comment by brian-brazil** [comment]
Both.

**Comment by brian-brazil** [comment]
I don't think there's anything we can practically do here.
