### ISSUE TITLE
how to edit the black_exporter's dashboard of grafana by xx-dashboard.json or who have the ready-made dashboard?

### ISSUE THREAD

**Issue by jiuchongxiao** [prometheus/blackbox_exporter#343]
i can get the metrics as below:
![image](https://user-images.githubusercontent.com/13093730/43073164-21affaec-8eab-11e8-840a-13a44a63413a.png)

i want to get the qps metrics and response time metrics and the 90% 95% metrics

**Comment by SuperQ** [comment]
That is [Whitebox monitoring](https://insights.sei.cmu.edu/devops/2016/08/whitebox-monitoring-with-prometheus.html). It will require instrumenting the application in some way.

For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
