### ISSUE TITLE
Multiple ping packets option for ICMP probe

### ISSUE THREAD

**Issue by veksh** [prometheus/blackbox_exporter#355]
Currently ICMP probe is sending out just one packet. It would be nice to specify a number of packets to send (in sequence) and measure packet loss (number of replies received) plus maybe min/max/avg RTT times, like `ping -c <number>` does. That would allow to measure link quality with greater detail and avoid triggering false "link down" alarms on loaded links.

**Comment by brian-brazil** [comment]
Dupe of #115
