### ISSUE TITLE
FR: support "role: pod" for deployments without explicit Service 

### ISSUE THREAD

**Issue by dilyevsky** [prometheus/blackbox_exporter#359]
I have a bunch of various deployments that just do some data pipelining and so don't have any services attached to them since they don't serve any traffic. They do however export /metrics and I would like to scrape them using Prometheus Operator.

It's not a big deal I guess but it seems silly having to add Service (that is not even used because Prometheus goes to Endpoints directly) just for metrics collection. Can "role: pod" from `kubernetes_sd_configs` be supported in addition to Endpoints? I could take this on of that's in line with the overall design vision.

**Comment by brian-brazil** [comment]
I think you've got the wrong repo, and meant to file this against the Prometheus Operator.

**Comment by dilyevsky** [comment]
doh, sorry about that. too many tabs...
