### ISSUE TITLE
Restrict usage of the exporter to a single host (the one running prometheus)

### ISSUE THREAD

**Issue by idevai** [prometheus/blackbox_exporter#361]
Is there any feature that allows restricting access to the exporter to a specific host? Eg I'd like to ensure that only the host running prometheus can access the exporter. Is there any built in feature (be it IP or certificate based), or is that fully up to the environment (eg outside reverse proxy)?

Thank you.

**Comment by SuperQ** [comment]
You can bind the exporter to localhost.
```
blackbox_exporter --web.listen-address=localhost:9115
```

For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by idevai** [comment]
Thanks a lot!
