### ISSUE TITLE
docker image seems to be bypassing hosts file

### ISSUE THREAD

**Issue by briffle** [prometheus/blackbox_exporter#366]
### Host operating system: output of `uname -a`
docker 17.06.2-ce
### blackbox_exporter version: output of `blackbox_exporter -version`
v0.12.0

### What did you do that produced an error?
I have a website that virtualhosts, that is also behind my firewall, along with prometheus/blackbox-exporter.  Since my firewall does not support hairpinning, I override the external DNS with an /etc/hosts entry.  When creating the docker image, I specify: --add-host=www.example.com:10.1.1.1  This adds the entry to the /etc/hosts inside the docker image. (I have confirmed its in there).  I can exec into a shell in the blackbox-exporter docker image, and ping and wget, and they work correctly.  However, the exporter grabs its external DNS address every time, and tries to connect, timing out.  Sites I am monitoring outside our firewall are working fine.

### What did you expect to see?
I expected the exporter to use the hosts file to lookup the internal IP address

### What did you see instead?
```
ts=2018-09-27T13:24:39.146840792Z caller=utils.go:65 module=http_2xx target=https://www.example.com
 level=info msg="Resolved target address" ip=<external_ip>
ts=2018-09-27T13:24:39.146904637Z caller=http.go:282 module=http_2xx target=https://www.example.com
 level=info msg="Making HTTP request" url=https://[<external-ip>] host=www.example.com
ts=2018-09-27T13:24:48.579849553Z caller=http.go:297 module=http_2xx target=www.example.com
 level=error msg="Error for HTTP request" err="Get https://[<external-ip>]: context deadline exceeded"
```

How can I force the exporter to overload the ip address?

**Comment by SuperQ** [comment]
This is probably due to `/etc/nsswitch.conf`. I think there was an open issue for that somewhere.

**Comment by SuperQ** [comment]
Our docker image does not include an `/etc/nsswitch.conf` by default. It does not automatically inherit the one from the host.

**Comment by SuperQ** [comment]
Golang does not use the same resolver methods as busybox, so they will not have the same results.

**Comment by briffle** [comment]
looks like PR #327

**Comment by briffle** [comment]
As a work around, it appears I can modify my docker run command to include:
`-v /etc/nsswitch.conf:/etc/nsswitch.conf`

This seems to allow it to work, until that pull request can be merged. Thanks for the tip!
