### ISSUE TITLE
can't connect to google.com?

### ISSUE THREAD

**Issue by maxandersen** [prometheus/blackbox_exporter#368]
I'm trying to understand why google.com probe fails ?

`http://localhost:9115/probe?target=google.com&module=http_2xx&debug=true` gives me:

With debug I get:

```
Logs for the probe:
ts=2018-10-01T11:57:50.1938443Z caller=main.go:116 module=http_2xx target=google.com level=info msg="Beginning probe" probe=http timeout_seconds=9.5
ts=2018-10-01T11:57:50.1971228Z caller=utils.go:42 module=http_2xx target=google.com level=info msg="Resolving target address" preferred_ip_protocol=ip6
ts=2018-10-01T11:57:50.2071952Z caller=utils.go:65 module=http_2xx target=google.com level=info msg="Resolved target address" ip=2a00:1450:400a:802::200e
ts=2018-10-01T11:57:50.2073305Z caller=http.go:282 module=http_2xx target=google.com level=info msg="Making HTTP request" url=http://[2a00:1450:400a:802::200e] host=google.com
ts=2018-10-01T11:57:50.2091326Z caller=http.go:297 module=http_2xx target=google.com level=error msg="Error for HTTP request" err="Get http://[2a00:1450:400a:802::200e]: dial tcp [2a00:1450:400a:802::200e]:80: connect: cannot assign requested address"
ts=2018-10-01T11:57:50.2101423Z caller=http.go:354 module=http_2xx target=google.com level=info msg="Response timings for roundtrip" roundtrip=0 start=2018-10-01T11:57:50.2077534Z dnsDone=2018-10-01T11:57:50.2077534Z connectDone=2018-10-01T11:57:50.2081815Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=2018-10-01T11:57:50.2087778Z
ts=2018-10-01T11:57:50.2107075Z caller=main.go:129 module=http_2xx target=google.com level=error msg="Probe failed" duration_seconds=0.0165147
```

doing some other host works fine. what is special about google.com ?

**Comment by brian-brazil** [comment]
Your system doesn't have a working ipv6 setup, and the blackbox exporter uses an ipv6 address if one is available.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by maxandersen** [comment]
noted - makes sense - fyi, this was when running in OSX docker and I didn't think it would be ip6 related as other pings worked fine. I'll follow up on prometheus-user list if other issues. thanks.
