### ISSUE TITLE
[Feature Request] Configuration without prometheus dependency

### ISSUE THREAD

**Issue by DenisBiondic** [prometheus/blackbox_exporter#374]
For the blackbox exporter to work, one has to provide targets through Prometheus config. Wouldn't it be a better architectural approach that the blackbox exporter can be configured directly with targets, thus removing the "dependency" on Prometheus itself? This would also work better with prometheus-operator out of the box, since simple ServiceMonitor would work.

**Comment by SuperQ** [comment]
No, the blackbox_exporter is a stateless proxy. Prometheus configures targets to monitor, this is by design.

There is no dependency on Prometheus. Any monitoring system can use the blackbox_exporter via the `/probe` interface.

**Comment by DenisBiondic** [comment]
OK, so this also means blackbox exporter will only check the endpoints depending on how often promethues calls the probe path, right (scrape interval)? 

Perhaps it is a silly question because I don't know the inner working of blackbox exporter, but wouldn't it provide some value that blackbox exporter works standalone, probing the configured endpoints every x configured time span, decoupled from prometheus scrape interval? (would also cover the scenario where prometheus is down, but exporter would continue probing the targets, right?)

**Comment by SuperQ** [comment]
Yes, the probes are based on the scrape interval in Prometheus. The design goal is that Prometheus is the monitoring system, doing all of the metrics collection, and in the case of blackbox, the probes. It tracks the state, allowing for all calculations to be done on the data stored in the internal TSDB.

Prometheus targets are all intended to not need to track any state, except "now".

For high availability, it's intended that more than one Prometheus server is run.

From a real-time monitoring perspective, blackbox probing is more of a backup / end-to-end test, compared to real application metrics. It's not statistically useful compared to application metrics. Imagine you get 100 requests per second, blackbox probing every 10 seconds is only one in every 600 requests. Or 0.16%. It gets worse as the scale grows.

**Comment by DenisBiondic** [comment]
A scenario where we want to deploy blackbox exporter is monitoring of internal 3rd party systems, which are not under our control (legacy stuff exposed over VPN to on-prem DC), which we want to prove that is not so stable as they say it is ;) For this reason, we also don't want to probe every 10 seconds or so, but more like once per second. 

As to point about "now" and "prometheus tracks the state", I kind of get that, I mean, I imagined this to work by simply exposing metrics of counter type, something like probe_success_total and probe_failure_total, using labels to give more info about failures for example; or additionally histograms could be used.

**Comment by DenisBiondic** [comment]
As for the prometheus scrape, I would not want to affect the prometheus performance with a exporter relevant logic.

As for the custom prober, I think we will try to build something in this direction. 

In any case, thank you very much for the open and cool discussion.

**Comment by SuperQ** [comment]
For performance, it depends on what exactly you're trying to observe. 1 second scrapes are not a performance problem for Prometheus, and are used in places where we're trying to get visibility into spiking data. For example, I have an issue where we notice a traffic spike for the first few seconds of every minute. In order to observe how bad this is, we had to adjust the scrape interval to 5s to see a bit more resolution.

**Comment by DenisBiondic** [comment]
Anyways, exact requirements which I needed are possible with https://cloudprober.org/
