### ISSUE TITLE
Where I could see my ouput/error? 

### ISSUE THREAD

**Issue by tharunap91** [prometheus/blackbox_exporter#378]
### Host operating system: output of `uname -a`
Linux 2.6.32-696.30.1.el6.x86_64 #1 SMP Fri May 18 11:50:44 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.12.0 (branch: HEAD, revision: 4a22506cf0cf139d9b2f9cde099f0012d9fcabde)
  build user:       root@634195974c8e
  build date:       20180227-11:50:29
  go version:       go1.10

### What is the blackbox.yml module config.
modules:
  http_2xx_example:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      headers:
        Host: https://my-site
        Accept-Language: en-US

### What is the prometheus.yml scrape config.
It is not configured
### What logging output did you get from adding `&debug=true` to the probe URL?
level=info ts=2018-10-18T05:45:04.199289848Z caller=main.go:213 msg="Starting blackbox_exporter" version="(version=0.12.0, branch=HEAD, revision=4a22506cf0cf139d9b2f9cde099f0012d9fcabde)"
level=info ts=2018-10-18T05:45:04.199754625Z caller=main.go:220 msg="Loaded config file"
level=info ts=2018-10-18T05:45:04.199907364Z caller=main.go:324 msg="Listening on address" address=:9115

### What did you do that produced an error?
No error is shown
### What did you expect to see?
Metric of my site
### What did you see instead?
When I execute this coomand  "curl localhost:9115/metrics"
# TYPE process_open_fds gauge
process_open_fds 7
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 6.295552e+06
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.53984230626e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.5187968e+07

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by aomi** [comment]
I believe you will not see the metrics under /metrics as these are the metrics for blackbox_exporter itself. ```localhost:9115/probe?target=https://my-site&module=http_2xx_example``` will yield the result you are looking for.

**Comment by tharunap91** [comment]
@aomi Thanks for the reply.. I have executed in the way that you have suggested.. 
Now, I am getting the error like below:

blackbox_exporter-0.12.0.linux-amd64 $ Unknown module "http_2xx"

**Comment by tharunap91** [comment]
I have used this command to :
$ curl -k localhost:9115/probe?target=https://my-site/&module=http_2xx_example
output:
blackbox_exporter-0.12.0.linux-amd64 $ Unknown module "http_2xx"

Could you please guide me..

**Comment by marco-m** [comment]
@SuperQ it looks like this can be closed ?
