### ISSUE TITLE
Negative Probe Duration

### ISSUE THREAD

**Issue by TianleChew** [prometheus/blackbox_exporter#38]
Hi there,

I have been scraping and monitoring a number of target urls for a while now and on 19 April 2016, a couple of them reflected negative probe duration (seconds). This happened for a brief period of 10 seconds around 5:47 PM. May i know if this is normal?

Thanks in advance

**Comment by grobie** [comment]
This does not sound right. What module did you use for the probing. Maybe also post your (sanitized) config.

**Comment by caskey** [comment]
You also might want to check if a clock shift occurred on the underlying
host. Naïve time sync attempts that shift clocks backward by any amount are
generally a bad thing.

**Comment by TianleChew** [comment]
Hi @grobie & @caskey,

Thank you for your replies! I checked the logs and found the following, indicating a time change very close to the negative probe duration occurrence:

    Apr 19 17:46:58 xxx systemd[29852]: Time has been changed
    Apr 19 17:46:58 xxx systemd[1836]: Time has been changed
    Apr 19 17:46:58 xxx systemd[547]: Time has been changed
    Apr 19 17:46:58 xxx systemd-timesyncd[263]: Synchronized to time server xx.xx.xx.xx:xx (xx.xx.xx.xx).
    Apr 19 17:46:58 xxx systemd[1]: Time has been changed

Thanks again for all the help!
Cheers
