### ISSUE TITLE
wrong target upon 308  redirect

### ISSUE THREAD

**Issue by nickytd** [prometheus/blackbox_exporter#384]
http_2xx:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: [200,301,308]  # Defaults to 2xx
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_matches_regexp:
        - "Could not connect to database"
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4" # defaults to "ip6"

On target http://URL:80 there 308 permanent redirect 
< HTTP/1.1 308 Permanent Redirect
< Server: nginx/1.15.3
however the following request is on 
msg="Received redirect" url=https://mykube:80/
which is wrong

**Comment by brian-brazil** [comment]
Can you share the debug output please?

**Comment by brian-brazil** [comment]
That looks like an incorrect redirect from the server, which the blackbox exporter is correctly detecting.

**Comment by nickytd** [comment]
No, that is why I attached the curl showing the response from the server. Take a look at the curl above

**Comment by brian-brazil** [comment]
Those are not the same request.

**Comment by nickytd** [comment]
These are the same http://mykube:80, The port is there.

**Comment by nickytd** [comment]
:) the server is Nginx and the response is a valid http response you can simulate it with an ingress I can share a deployment spec if interested. It can be reproduced easily on Minikube

**Comment by brian-brazil** [comment]
It's a valid response, but it's not the correct response. The blackbox exporter is only doing exactly what the webserver told it to do, redirect to https://mykube:80/
