### ISSUE TITLE
make fails: `go: cannot find main module root; see 'go help modules'`

### ISSUE THREAD

**Issue by discordianfish** [prometheus/blackbox_exporter#389]
Looks like this has go module support but it's not being used. When removing vendor/, the builds fail (both promu as well as `go build`)

But even without touching vendor, `make` doesn't seem to work:

```
$ make
>> checking code style
tmpModule=$(mktemp -d 2>&1) && \
mkdir -p ${tmpModule}/staticcheck && \
cd "${tmpModule}"/staticcheck && \
GO111MODULE=on go mod init example.com/staticcheck && \
GO111MODULE=on GOOS= GOARCH= go get -u honnef.co/go/tools/cmd/staticcheck@next && \
rm -rf ${tmpModule};
go: cannot find main module root; see 'go help modules'
Makefile.common:193: recipe for target '/home/fish/dev/go/bin/staticcheck' failed
make: *** [/home/fish/dev/go/bin/staticcheck] Error 1
```

**Comment by discordianfish** [comment]
Ok, the `go build` stuff works when settting `GO111MODULE=on` but `make` fails either way.

**Comment by SuperQ** [comment]
@discordianfish Are you running `make` inside or outside your `GOPATH`?

You might want to `rm -rf ${GOPATH}/src/honnef.co/go/tools`.

**Comment by brian-brazil** [comment]
All the Go builds are synced up now, so this shouldn't be a problem.
