### ISSUE TITLE
Feature request: ability to specify HTTP probe POST body content as on-disk file

### ISSUE THREAD

**Issue by emmanuel** [prometheus/blackbox_exporter#391]
Blackbox exporter config allows specifying POST body for HTTP probe as an in-line string in the config file. I have a circumstance where I want to probe with some large body sizes, and there is a significant memory impact of treating those bodies as inline strings.

I propose adding a `BodyPath` parameter to the HTTP prober, that will be used to open a file on disk and use the content of that file as the body of the probe's requests. Something like this:

```
type HTTPProbe struct {
	// Defaults to 2xx.
	ValidStatusCodes       []int             `yaml:"valid_status_codes,omitempty"`
...
	Body                   string            `yaml:"body,omitempty"`
	BodyPath               string            `yaml:"body_path,omitempty"`
	HTTPClientConfig       config.HTTPClientConfig `yaml:"http_client_config,inline"`
}
```

**Comment by brian-brazil** [comment]
How big is the data you're sending?

**Comment by emmanuel** [comment]
1.6MiB, so far. 

Also, I have multiple endpoints I'm scraping with the same bodies (with different HTTP parameters of other sorts), so the same data is parsed into memory as multiple copies of this large string. The current (in-line string) config option compels this duplication. Plus (and more essentially), YAML is just not a good medium for values of that size.

**Comment by Turgon37** [comment]
Hello I'm also looking for this feature @emmanuel have any time to works on this ?

Thanks in advance

**Comment by birmogave87** [comment]
i am looking for something like this also Feature Request: Is there a way to scrape "Probe Logs" #586
