### ISSUE TITLE
Build Breaks with Go 1.11.4

### ISSUE THREAD

**Issue by Vaelatern** [prometheus/blackbox_exporter#395]
Builds fail on the latest release of blackbox_exporter (`0.31.0`) on a checksum mismatch (for `github.com/prometheus/procfs@v0.0.0-20170703101242-e645f4e5aaa8`)
This is due to: https://github.com/golang/go/issues/29278#issuecomment-447537558

My apologies for not saying more, it seems pretty self-evident that there is a problem, to me.

**Comment by brian-brazil** [comment]
@simonpasquier
