### ISSUE TITLE
Log levels above `debug` do not work

### ISSUE THREAD

**Issue by zerkms** [prometheus/blackbox_exporter#399]
### Host operating system: output of `uname -a`
`Linux worker-1 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

### blackbox_exporter version: output of `blackbox_exporter -version`

```
blackbox_exporter, version 0.13.0 (branch: HEAD, revision: 1cfb7512daa7e100abb32037996c8f805990d813)
  build user:       root@7b171fc53a0a
  build date:       20181204-15:06:48
  go version:       go1.11.2
```
It looks like at the moment everything is logged with the `level=debug`:

an actual log obtained with `--log.level=debug`
```
Dec 21 01:04:38 worker-1 blackbox_exporter[6083]: ts=2018-12-21T01:04:38.703876756Z caller=main.go:176 module=... target=... level=debug msg="Validating Additional RRs"
```

While in source code it looks like it should be `info`

```
level.Info(logger).Log("msg", "Validating Additional RRs")
```

So at this moment it looks like one either sets up `--log.level=debug` and gets tons of too detailed info, or sets `--log.level=info` and gets nothing (since all records are logged as `debug`).

**Comment by brian-brazil** [comment]
Yes, it's as expected. Per-probe information is debug level, as it's not about the exporter overall.

**Comment by zerkms** [comment]
What's the purpose of having different level log messages in probes then?

**Comment by brian-brazil** [comment]
It shows up when you look at the logs for just that probe via http.

**Comment by zerkms** [comment]
Yep, but why they are different log levels if they are only visible on `debug=true`?

**Comment by zerkms** [comment]
Yep, but `debug` is too low, `info` would be enough, if it output anything

**Comment by brian-brazil** [comment]
A probe failing is not an application-level issue though, the exporter is working exactly as designed. If you want this level of detail you need to enable debug logging.

**Comment by zerkms** [comment]
It's not convenient: if you have thousands of targets you simply cannot afford logging everything on debug level.

I'm running a tiny infrastructure, it's not obvious how this exporter is supposed to be run in a more serious one, given that there is no tools to inspect problems.

If you think that's how it should be done, oh well.

**Comment by AndresPineros** [comment]
A logging system that jumps from "log nothing" to "log everything" doesn't seem well designed.

Is it really hard to have 3 levels?
- Log application level issues
- Log target level issues
- Log everything

This would help people figure out stuff much faster. Just because the logging system was designed one way doesn't mean it is properly designed.
