### ISSUE TITLE
 module=http_2xx target=http://prometheus:9100 level=error msg="Error for HTTP request" err="Get http://10.221.103.141:9100: context deadline exceeded"

### ISSUE THREAD

**Issue by 249510573** [prometheus/blackbox_exporter#400]
URL：http://localhost::9115/probe?target=http://prometheus:9100&module=http_2xx&debug=true

when i request the url， blackbox-exporter log Error as follow：

Logs for the probe:
ts=2018-12-21T03:39:23.412441716Z caller=main.go:116 module=http_2xx target=http://prometheus:9100 level=info msg="Beginning probe" probe=http timeout_seconds=-290
ts=2018-12-21T03:39:23.412876493Z caller=utils.go:42 module=http_2xx target=http://prometheus:9100 level=info msg="Resolving target address" preferred_ip_protocol=ip4
ts=2018-12-21T03:39:23.413083177Z caller=utils.go:65 module=http_2xx target=http://prometheus:9100 level=info msg="Resolved target address" ip=10.221.103.141
ts=2018-12-21T03:39:23.413163999Z caller=http.go:282 module=http_2xx target=http://prometheus:9100 level=info msg="Making HTTP request" url=http://10.221.103.141:9100 host=prometheus:9100
ts=2018-12-21T03:39:23.413324492Z caller=http.go:297 module=http_2xx target=http://prometheus:9100 level=error msg="Error for HTTP request" err="Get http://10.221.103.141:9100: context deadline exceeded"
ts=2018-12-21T03:39:23.413379932Z caller=http.go:354 module=http_2xx target=http://prometheus:9100 level=info msg="Response timings for roundtrip" roundtrip=0 start=0001-01-01T00:00:00Z dnsDone=0001-01-01T00:00:00Z connectDone=0001-01-01T00:00:00Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=2018-12-21T11:39:23.41331185+08:00
ts=2018-12-21T03:39:23.413467785Z caller=main.go:129 module=http_2xx target=http://prometheus:9100 level=error msg="Probe failed" duration_seconds=0.000787927

blackbox.yml:
modules:
  http_2xx:
    prober: http
    timeout: 300s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: [200]
      method: GET
      preferred_ip_protocol: "ip4"
  http_post_2xx: # http post 监测模块
    prober: http
    timeout: 300s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      method: POST
      preferred_ip_protocol: "ip4"
  tcp_connect:
    prober: tcp
    timeout: 60s
  icmp:
    prober: icmp
    timeout: 10s
    icmp:
      preferred_ip_protocol: "ip4"
  dcs_results:
    prober: http
    timeout: 5s
    http:
      fail_if_not_matches_regexp:
      - "load_font"

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
