### ISSUE TITLE
http_prober issue with Host header

### ISSUE THREAD

**Issue by kylixtan** [prometheus/blackbox_exporter#401]
output from command, 
curl "http://localhost:9115/probe?module=http_2xx&target=https://pypi.org:443&debug=true"
......
ts=2018-12-24T03:22:07.550647031Z caller=main.go:118 module=http_2xx target=https://pypi.org:443 level=info msg="Beginning probe" probe=http timeout_seconds=9.5
ts=2018-12-24T03:22:07.550766431Z caller=utils.go:42 module=http_2xx target=https://pypi.org:443 level=info msg="Resolving target address" preferred_ip_protocol=ip6
ts=2018-12-24T03:22:07.552020227Z caller=utils.go:65 module=http_2xx target=https://pypi.org:443 level=info msg="Resolved target address" ip=2a04:4e42::223
ts=2018-12-24T03:22:07.552054827Z caller=http.go:281 module=http_2xx target=https://pypi.org:443 level=info msg="Making HTTP request" url=https://[2a04:4e42::223]:443 host=pypi.org:443
....

you could seee the part of last line, "host=pypi.org:443".  that will cause issue when you use host match on your load balancer. 

OS:
ubuntu 16.04.1
blackbox_exporter:
    blackbox_exporter --version
        blackbox_exporter, version 0.13.0 (branch: HEAD, revision:      1cfb7512daa7e100abb32037996c8f805990d813)
  build user:       root@7b171fc53a0a
  build date:       20181204-15:06:48
  go version:       go1.11.2

**Comment by kylixtan** [comment]
Host should always be host without port, the port part should be split from it by the exporter. I think

**Comment by brian-brazil** [comment]
The RFCs require that both work.

**Comment by zht1246** [comment]
I have the same problem
