### ISSUE TITLE
probe http port on other service. 

### ISSUE THREAD

**Issue by Erictsu1947** [prometheus/blackbox_exporter#405]
### Host operating system: output of `uname -a`
Linux bridge 4.4.0-140-generic #166~14.04.1-Ubuntu SMP Sat Nov 17 01:52:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.13.0 (branch: HEAD, revision: 1cfb7512daa7e100abb32037996c8f805990d813)
  build user:       root@7b171fc53a0a
  build date:       20181204-15:06:48
  go version:       go1.11.2

### What is the blackbox.yml module config.

modules:
  http_2xx:
    prober: http
    http:
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  ping:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"

### What is the prometheus.yml scrape config.
  - job_name: 'service_available_data'
    scrape_interval: 15s
    metrics_path: /probe
    proxy_url: 'http://service0:9115'
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - '127.0.0.1:17001'
        - '127.0.0.1:17002'
        - '127.0.0.1:17003'
        - '127.0.0.1:17004'
        - '127.0.0.1:17005'
        - '127.0.0.1:17006'
        - '127.0.0.1:17007'
        - '127.0.0.1:17008'
        - '127.0.0.1:17009'
        - '127.0.0.1:17010'
        - '127.0.0.1:17011'

    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:\d+)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__address__]
        regex: (.*):(\d+)
        target_label: __address__
        replacement: ${1}:$2
      - source_labels: [__address__]
        regex: (.*):(\d+)(.*$)?
        target_label: __address__
        replacement: ${1}:$2
      - source_labels: [__param_target]
        regex: '(.*)'
        target_label: 'node'
        replacement: '${1}'
      - source_labels: [__address__]
        regex: '(.*)\:\d+'
        target_label:  'host'
        replacement:   '$1'
      - source_labels: [__address__]
        regex: '(.*)\:\d+'
        target_label:  'name'
        replacement:   '$1'
      - source_labels: [__address__]
        target_label:  'environment'
        replacement:   'prod'

### What did you expect to see?

I deploy prometheus on a server named prometheus-001.

I also have three server which named like server-001,server-002, server-003. 
Every server running some web serivce bind on localhost, listen port just from 17000 to 17011.

It's there any method to probe http port stats on three web server  from prometheus-001?

I try to run blackbox_exporter for each server, then to collect info with prometheus.

But I didn't find a config field to config balckbox_exporter url.

thanks a lot for your help.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
