### ISSUE TITLE
Feature Request: Metrics for TCP health (retransmissions, etc.)

### ISSUE THREAD

**Issue by gshively11** [prometheus/blackbox_exporter#406]
This looks like a great utility! We'd love to use it to monitor the connectivity/availability of our services from an external location. We recently got bit by a TCP retransmission issue due to some faulty network hardware between our user base and our services. It took us a while to track it down.

Our thought is that in addition to the useful metrics that blackbox_exporter already collects, it could be sniffing the packets sent out by the TCP prober to check for retransmissions and other protocol-related issues. Does this sound like something blackbox_exporter could do?

**Comment by brian-brazil** [comment]
That's require sniffing the network, which is not something we can do with standard permissions. An issue like that should show up in the existing latency metrics though.

**Comment by gshively11** [comment]
Let me take a closer look at the existing metrics, I haven't dug in yet. Would having an optional argument to enable the sniffing be acceptable?  Or do you want that kept outside of blackbox_exporter entirely?

**Comment by SuperQ** [comment]
You might want to look at the `netstat` metrics exported by the [node_exporter](https://github.com/prometheus/node_exporter). For example, `node_netstat_Tcp_RetransSegs`, and `node_netstat_TcpExt_TCPSynRetrans` (coming in 0.18.0 or with a flag change).

**Comment by brian-brazil** [comment]
I don't think that belongs here, and as @SuperQ says the machine level metrics are available.

**Comment by gshively11** [comment]
Machine level is a little too coarse for our use case.  We want to get metrics on a single endpoint/connection.  Thanks for the thought though.  I might take a stab at writing a TcpHealthProbe for our personal use.

**Comment by SuperQ** [comment]
I don't think the kernel provides that data in the TCP socket API.

**Comment by gshively11** [comment]
It doesn't, you'd have to bring in something like https://godoc.org/github.com/google/gopacket

**Comment by brian-brazil** [comment]
This seems out of scope, the blackbox exporter works at layers above this.
