### ISSUE TITLE
Add additional information labels to probe_ssl_earliest_cert_expiry metric

### ISSUE THREAD

**Issue by tdabasinskas** [prometheus/blackbox_exporter#410]
Hello,

Currently `probe_ssl_earliest_cert_expiry` metric has no labels. Would it make sense to extend this metric to include the following labels?

- Subject Common Name (`CN`)
- DNS names (`DNS`)
- Subject Organization (`O`)
- Subject Organization Unit (`OU`)
- Subjec E-mail Address (`E`)

The first two would allow to easily see which exact certificate from the chain is expiring (currently, the metric returns the one which is about to expire first, but there's no way to know which one is this).

The remaining ones would help with the alerting, as it would be possible to know to which receiver the alerts about expiring certificates should be routed to.

I can do a PR if you think that makes sense.

**Comment by tdabasinskas** [comment]
Hi @brian-brazil,
Do you have any input on this?

**Comment by brian-brazil** [comment]
It doesn't make sense to add these labels. The purpose of alerting like this is to let you know there's a problem, it's fine for you to have to use additional tools to debug further rather than trying to turn your metrics system into your only debugging tool.

**Comment by tdabasinskas** [comment]
Hi @brian-brazil,

Thanks for the comment.

Even I do fully agree alerting should not become a debugging tool, I don't think this is the case here.

`CN` and `DNS` are crucial information for alerts about expiring certificates. Without them, it's not possible to identify the actual impact, as certificate which is about to expire might include additional names (defined via `DNS`) that will be affected as well.

On the other hand `E` and `OU` fields would help with the proper alert routing: I can automatically alert the actual owner of the certificate, instead of trying to hardcode that information manually somewhere within an alert itself.

**Comment by brian-brazil** [comment]
Your instance label should already cover that, and the rest is a matter of target labels.

**Comment by tdabasinskas** [comment]
Can you please elaborate a bit how exactly this should be covered by the instance label? As for the target labels, I'm still not sure hard-coding additional labels on the target definition is better than retrieving them automatically. If we would about to follow this logic, that would mean the certificate expiration date should be added as a static target label instead of automatically extracted by the exporter, wouldn't it?

**Comment by brian-brazil** [comment]
Target label taxonomy is beyond the scope of the blackbox exporter, as this applies to all exporters.

> that would mean the certificate expiration date should be added as a static target label instead of automatically extracted by the exporter, isn't that correct?

Exporters can't add target labels, and it wouldn't be useful in this case.

**Comment by tdabasinskas** [comment]
OK, so, in short, if there's a PR adding mentioned labels to this exact metric, it wouldn't get merged?

**Comment by brian-brazil** [comment]
No, it wouldn't. That'd be a breaking change at the least.

**Comment by tdabasinskas** [comment]
OK, I guess you know better.
