### ISSUE TITLE
alerts and targets show different results

### ISSUE THREAD

**Issue by yongsr** [prometheus/blackbox_exporter#420]
### Host operating system: output of `uname -a`
Centos 7.6 
Kernel 3.10.0-957.1.3.el7.x86_64 

### blackbox_exporter version: output of `blackbox_exporter -version`

0.13

### What is the blackbox.yml module config.
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: ip4
  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      preferred_ip_protocol: ip4
  tcp_connect:
   prober: tcp
   timeout: 5s
   tcp:
     preferred_ip_protocol: ip4
  icmp:
   prober: icmp
   timeout: 5s
   icmp:
     preferred_ip_protocol: ip4

### What is the prometheus.yml scrape config.
# my global config
global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - alert.rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
  
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
    - targets: ['localhost:9100']
    - targets: ['ip-address:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
    - targets: 
       - http://localhost:8080/
       - http://www.abc.com:80
       - https://www.abc.com:443
       - http://stage.abc.com:8055
       - https://stage.abc.com:8081
       - http://hahaha.hhahahahaha.com:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

### What logging output did you get from adding `&debug=true` to the probe URL?
more error under alerts instead of log

### What did you do that produced an error?
systemctl start prometheus.service

### What did you expect to see?
those server with wrong port and wrong url should be down

### What did you see instead?
Those servers with wrong ports  and  url are up

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
