### ISSUE TITLE
Localhost as a probe target

### ISSUE THREAD

**Issue by jeremybb** [prometheus/blackbox_exporter#421]
### Host operating system: output of `uname -a`
Linux

### What logging output did you get from adding `&debug=true` to the probe URL?
Reading data from connecting to services that may be firewalled off from the outside displayed in eg. level=error msg="Error for HTTP request" err="Get http://[::1]:nn: net/http: HTTP/1.x transport connection broken: malformed HTTP status code \"xxxxxxxxxxxxxxxx\""

### What did you do that produced an error?
http://host/probe?target=localhost:**[n-nnnnn]**&module=http_2xx&debug=true

### What did you expect to see?
Not the ability to iteratively port scan localhost by checking for if "connection refused" is returned or not and also read some data sent back from potentially sensitive services firewalled from outside connections

### What did you see instead?
Scanning the probe target localhost/127.0.0.1/::1 disabled by default, perhaps? I haven't been able to think of a reason why it would be ok to allow it. Leaking this data could be considered risky from a security perspective in some scenarios when deploying Blackbox.

**Comment by brian-brazil** [comment]
Some users do probe localhost, and you will only be able to send requests that are configured in the config. Generally the blackbox exporter will let you do this to any address it can talk to.

**Comment by jeremybb** [comment]
Hmm understood, but do you think a simple config option to enable/disable this behavior would be valuable?

**Comment by brian-brazil** [comment]
We're kinda getting into authorisation there, why would we limit it to just localhost?

**Comment by jeremybb** [comment]
Good point!

Still withstanding, the ability to scan/read data from services that may be only localhost (or other hosts internal to the network) and not exposed to the broader network is allowing a remote user to gain information they wouldn't normally have access to.

I agree the risks to this may be more or less depending on the deployment scenario, but if nothing else it's an interesting effect by design. Maybe an option for authentication so only trusted users can execute probes is the more reasonable mitigation, but that's a bit bigger change.

**Comment by brian-brazil** [comment]
This is covered by our security doc, which makes it clear that they can be made to request anything: https://prometheus.io/docs/operating/security/

Features which would make this exporter a full open proxy are not accepted.

**Comment by jeremybb** [comment]
Solid documentation, thanks for putting the time into considering the angles. Hadn't came across that page yet, was mostly exploring configuration docs. Appreciate your time here!
