### ISSUE TITLE
probe_ssl_earliest_cert_expiry data disappears when certificate has expired

### ISSUE THREAD

**Issue by andrewjboyd** [prometheus/blackbox_exporter#423]
found an outdated SSL cert on www.peugeot.com.cn to test this scenario, but the logs come out looking like this:

`Logs for the probe:
ts=2019-02-26T06:32:52.213419998Z caller=main.go:116 module=http_2xx target=https://www.peugeot.com.cn/ level=info msg="Beginning probe" probe=http timeout_seconds=4.5
ts=2019-02-26T06:32:52.213518597Z caller=utils.go:42 module=http_2xx target=https://www.peugeot.com.cn/ level=info msg="Resolving target address" preferred_ip_protocol=ip4
ts=2019-02-26T06:32:52.215509177Z caller=utils.go:65 module=http_2xx target=https://www.peugeot.com.cn/ level=info msg="Resolved target address" ip=210.51.191.57
ts=2019-02-26T06:32:52.215542877Z caller=http.go:282 module=http_2xx target=https://www.peugeot.com.cn/ level=info msg="Making HTTP request" url=https://[210.51.191.57]/ host=www.peugeot.com.cn
ts=2019-02-26T06:32:52.700380516Z caller=http.go:297 module=http_2xx target=https://www.peugeot.com.cn/ level=error msg="Error for HTTP request" err="Get https://[210.51.191.57]/: x509: certificate has expired or is not yet valid"
ts=2019-02-26T06:32:52.700409416Z caller=http.go:354 module=http_2xx target=https://www.peugeot.com.cn/ level=info msg="Response timings for roundtrip" roundtrip=0 start=2019-02-26T06:32:52.215619276Z dnsDone=2019-02-26T06:32:52.215619276Z connectDone=2019-02-26T06:32:52.45569392Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=2019-02-26T06:32:52.700373916Z
ts=2019-02-26T06:32:52.700433116Z caller=main.go:129 module=http_2xx target=https://www.peugeot.com.cn/ level=error msg="Probe failed" duration_seconds=0.486985118

Metrics that would have been returned:
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.00199658
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.486985118
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length 0
# HELP probe_http_duration_seconds Duration of http request by phase, summed over all redirects
# TYPE probe_http_duration_seconds gauge
probe_http_duration_seconds{phase="connect"} 0
probe_http_duration_seconds{phase="processing"} 0
probe_http_duration_seconds{phase="resolve"} 0.00199658
probe_http_duration_seconds{phase="tls"} 0
probe_http_duration_seconds{phase="transfer"} 0
# HELP probe_http_redirects The number of redirects
# TYPE probe_http_redirects gauge
probe_http_redirects 0
# HELP probe_http_ssl Indicates if SSL was used for the final redirect
# TYPE probe_http_ssl gauge
probe_http_ssl 0
# HELP probe_http_status_code Response HTTP status code
# TYPE probe_http_status_code gauge
probe_http_status_code 0
# HELP probe_http_version Returns the version of HTTP of the probe response
# TYPE probe_http_version gauge
probe_http_version 0
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0

Module configuration:
prober: http
timeout: 5s
http:
  preferred_ip_protocol: ip4`

I have an alert setup based on probe_ssl_earliest_cert_expiry which isn't firing off, but it's telling me the site is down which isn't quite correct

**Comment by brian-brazil** [comment]
The Go http code doesn't give us the TLS information when the connection fails, and the site is down.

You may find badssl.com useful.

**Comment by andrewjboyd** [comment]
Thanks @brian-brazil that site is awesome!  The site itself isn't down though

**Comment by brian-brazil** [comment]
It is down, the TLS cert isn't valid.

**Comment by andrewjboyd** [comment]
That sucks, I could get it to work in C#, so I'll figure out an alternative with it.  Thanks for your help

**Comment by andrewjboyd** [comment]
Just saw this article (I haven't played with go), but it appears you are able to get details similar to how I achieved it in C#, https://stackoverflow.com/questions/12122159/how-to-do-a-https-request-with-bad-certificate

**Comment by brian-brazil** [comment]
That'd break the check for regular usage, but that is available as an option in the config file.
