### ISSUE TITLE
http_probe - resolve via IP

### ISSUE THREAD

**Issue by fialamarek** [prometheus/blackbox_exporter#425]
I'm using blackbox exporter and http_probe to monitor websites of my customers and I want to monitor only websites on my servers. So I would like to have an option on http_probe to specify IP address of server where url is hosted -> resolve via IP, not DNS.

In other words I would like to monitor:
```
wget http://123.123.123.123 --header "Host: website.com"
```
instead of:
```
wget website.com
```
Is it posible to add IP parameter to http_probe?

**Comment by brian-brazil** [comment]
Sounds like you want to add a Host header, which is supported.

**Comment by fialamarek** [comment]
Thank you. It works ;-)
