### ISSUE TITLE
Feature_request : http probe for size of returned page

### ISSUE THREAD

**Issue by xkilian** [prometheus/blackbox_exporter#426]
We have a use case where an http API responds with data. The size of the data varies and is correlated with a business process.
There are cases where the API responds but returns no data or unexepected amounts of data. A regex based check can be used for the first case, but having the size of the page or the size of the returned data/payload would be more informative.

Request: Have the http probe return the number of bytes in the http body or page.
Related: If implementing this, it would make sense to look at the #351 : md5 request as they are closely related. (If the decision is to implement)

**Comment by brian-brazil** [comment]
We should already have the content length as a metric

**Comment by xkilian** [comment]
probe_content_length is always -1

One of my probes returns data as binary : xgoogle/protobuf
One of the probes returns data as plain HTML with some javascript

Other metrics are ok, http_version=1.1, status_code = 200, probe_success = 1, http_redirects = 0
The nagios check_http has no problem with either of these http requests and displays the content length correctly.

**Comment by BenoitKnecht** [comment]
Is this a duplicate of #337 then?

**Comment by xkilian** [comment]
Yup, just read through the original. This is a duplicate and can be closed in favor of tracking in #337 .
