### ISSUE TITLE
Is it possible to support HTTP body response?

### ISSUE THREAD

**Issue by dkutetsky** [prometheus/blackbox_exporter#427]
Is it possible to return health-check HTTP body response to the Prometheus?
It could be helpful to track probe_success 0/1 together with HTTP content response.

**Comment by brian-brazil** [comment]
No, that'd be too big for a metric and it's very event logging. You can apply regexes to it though.

**Comment by dkutetsky** [comment]
Thanks for the quick response. Is it possible to use regex in blackbox exporter to track response payload or you recommend another tool/exporter?

**Comment by brian-brazil** [comment]
You'd need another tool for this, you could even do a small shell script in a cronjob.

**Comment by Accuratiorem** [comment]
> No, that'd be too big for a metric and it's very event logging. You can apply regexes to it though.

can you give me a regex example to check the body of http page and fail if it isn't correct?

I'm trying this one in the blackbox config.yml:
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      headers:
        Content-Type: application/json
      body: '{}'
      fail_if_body_not_matches_regexp:
        - '\"status|resultCode\"\:\"pass|SUCCESS|ok\"'

But it doesn't check the body, as for one web page it is showing Success check while the page doesn't have any of these strings, like status or resultCode

**Comment by sgargel** [comment]
> fail_if_body_not_matches_regexp:
> - '"status|resultCode":"pass|SUCCESS|ok"'
> 
> But it doesn't check the body, as for one web page it is showing Success check while the page doesn't have any of these strings, like status or resultCode

@Accuratiorem have you solved with `fail_if_body_not_matches_regexp` ? I've the same issue.

**Comment by EsoPhoenix** [comment]
I do not understand if fail_if_body_not_matches_regexp is able to parse the complete answer to validate or not the call
