### ISSUE TITLE
docker build fails to copy blackbox_exporter binary

### ISSUE THREAD

**Issue by jerrac** [prometheus/blackbox_exporter#429]
### Host operating system: output of `uname -a`
Linux hostname 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.13.0 (branch: master, revision: c453ee35c89a54c61490fe0e072f82f828a92ca2)
  build user:      username@hostname
  build date:       20190307-19:24:59
  go version:       go1.12

### What is the blackbox.yml module config.
The default.
### What is the prometheus.yml scrape config.
Not applicable to this issue.
### What logging output did you get from adding `&debug=true` to the probe URL?
Not applicable to this issue.
### What did you do that produced an error?
Tried to build the Docker image that I could push to our internal GitLab registry.
### What did you expect to see?
A successfully built Docker image.
### What did you see instead?
```bash
$ ~/dev/godev/src/gitlabinstance/blackbox_exporter   master  make
>> checking code style
>> running staticcheck
chmod +x /home/username/dev/godev/bin/staticcheck
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
GO111MODULE=on /home/username/dev/godev/bin/staticcheck -ignore "" ./...
>> running check for unused/missing packages in go.mod
GO111MODULE=on go mod tidy
>> running check for unused packages in vendor/
GO111MODULE=on go mod vendor
>> building binaries
GO111MODULE=on /home/username/dev/godev/bin/promu build --prefix /home/username/dev/godev/src/gitlabinstance/blackbox_exporter
 >   blackblox_exporter
>> running all tests
GO111MODULE=on go test -race  -mod=vendor ./...
ok      github.com/prometheus/blackbox_exporter (cached)
ok      github.com/prometheus/blackbox_exporter/config  (cached)
ok      github.com/prometheus/blackbox_exporter/prober  (cached)

$ ~/dev/godev/src/gitlabinstance/blackbox_exporter   master  docker build --no-cache -t gitlabinstance:8443/blackblox_exporter:latest .      
Sending build context to Docker daemon  23.52MB
Step 1/7 : FROM        quay.io/prometheus/busybox:latest
 ---> 98053401add9
Step 2/7 : MAINTAINER  The Prometheus Authors <prometheus-developers@googlegroups.com>
 ---> Running in 6aa57f48fd5a
Removing intermediate container 6aa57f48fd5a
 ---> 4baee87722e8
Step 3/7 : COPY blackbox_exporter  /bin/blackbox_exporter
COPY failed: stat /var/lib/docker/tmp/docker-builder948855567/blackbox_exporter: no such file or directory
```

https://github.com/prometheus/blackbox_exporter/issues/305 reports a similar issue. Though, apparently, the user didn't build blackbox_exporter first. Which I have done, so the `blackbox_exporter` file does exist in the root of the project.

I did try restarting docker to see if that would help. 

`.dockerignore` does not contain anything that should cause blackbox_exporter to be ignored. 

File permissions are fine.

All the generic "COPY failed" issues I found when searching boiled down to users not copying directories properly, `.dockerignore` blocking it, or the file being outside the docker context. None of which should apply to here. 

Am I just missing something? Is there something about the `quay.io/prometheus/busybox:latest` image that just doesn't work for general use (might be implied by https://github.com/prometheus/blackbox_exporter/issues/305#issuecomment-374208675)? If so, how are users supposed to deploy blackbox_exporter in production? There's no mention of a public, official, image. 

Thanks in advance.

**Comment by jerrac** [comment]
Ok, after running into weird file not found errors, I figured out that the binary make generates is named blackb**l**ox_exporter instead of blackbox_exporter. Note the extra l.

After copying `blackblox_exporter` to `blackbox_exporter`, the docker image builds successfully.

So the bug here is that the make command is generating the wrong filename.

**Comment by brian-brazil** [comment]
That's doing the right thing for me, I suspect you've edited the file locally.

**Comment by jerrac** [comment]
Ok, so I noticed that I had named my Gitlab instances clone of the project blackblox_exporter, with the l.

How does make determine what to call the binary? 

The only changes to the files are that I pushed what I checked out from here, into a new project on our GitLab instance. The repo is at c453ee35c89a54c61490fe0e072f82f828a92ca2, and git status only shows the misnamed binary make generated.

**Comment by brian-brazil** [comment]
That's how Go works.

I've just done a release, and all is working as normal.

**Comment by jerrac** [comment]
So, go names the binary based on the repo name? Interesting.

**Comment by brian-brazil** [comment]
Directory name.

**Comment by jerrac** [comment]
I just triple checked. My directory name is `blackbox_exporter`. The file make outputs is `blackblox_exporter`, with the 'l'. 

Ah well, I think this is just something odd going on with my setup, plus me not knowing go. I'm still wondering how I missed the releases tab and thought I needed to build it myself... :\
