### ISSUE TITLE
http status code is 0

### ISSUE THREAD

**Issue by alexju88** [prometheus/blackbox_exporter#431]
Does blackbox_exporter only recognize famous SSL CA ? my website can be visisted by internet , I can also curl it from server, but the blackbox_exporter show status code as 0, not 200, why ?

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
