### ISSUE TITLE
couldn't load packages due to errors

### ISSUE THREAD

**Issue by conseev** [prometheus/blackbox_exporter#433]
Hello,

When I run make it gives this:

----
# make
>> checking code style
>> running staticcheck
chmod +x /root/go/bin/staticcheck
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
GO111MODULE=on /root/go/bin/staticcheck -ignore "" ./...
/usr/lib/golang/src/runtime/internal/sys/arch_wasm.go:8:2: ArchFamily redeclared in this block
couldn't load packages due to errors: runtime/internal/sys, internal/cpu, runtime/internal/atomic and 1 more
make: *** [common-staticcheck] Error 1
----

What is the solution for this?

Thanks!

**Comment by brian-brazil** [comment]
That doesn't look like a blackbox exporter issue, more a Go problem of some form.

**Comment by conseev** [comment]
What does that error mean? Is there some binary that's architecture incompatible from the packages make downloads?

[root@metrics blackbox_exporter]# make
>> checking code style
>> running staticcheck
chmod +x /root/go/bin/staticcheck
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/prometheus/procfs v0.0.0-20170703101242-e645f4e5aaa8
go: finding github.com/alecthomas/repr v0.0.0-20181024024818-d37bc2a10ba1
go: finding github.com/alecthomas/assert v0.0.0-20170929043011-405dbfeb8e38
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/go-kit/kit v0.0.0-20170917202734-0d313fb5fb3a
go: finding github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
go: finding github.com/golang/protobuf v0.0.0-20170919002109-ae59567b9aab
go: finding golang.org/x/sync v0.0.0-20181108010431-42b317875d0f
go: finding golang.org/x/crypto v0.0.0-20171231215028-0fcca4842a8d
go: finding github.com/go-stack/stack v1.6.0
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/go-logfmt/logfmt v0.3.0
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/beorn7/perks v0.0.0-20160804104726-4c0e84591b9a
go: finding golang.org/x/sys v0.0.0-20181122145206-62eef0e2fa9b
go: finding github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
go: finding github.com/sergi/go-diff v1.0.0
go: finding github.com/mattn/go-isatty v0.0.4
go: finding github.com/gogo/protobuf v1.1.1
go: finding github.com/prometheus/client_model v0.0.0-20170216185247-6f3806018612
go: finding golang.org/x/net v0.0.0-20171102191033-01c190206fbd
go: finding github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
go: finding github.com/alecthomas/colour v0.0.0-20160524082231-60882d9e2721
go: finding github.com/pkg/errors v0.0.0-20170910134614-2b3a18b5f0fb
go: finding gopkg.in/alecthomas/kingpin.v2 v2.2.5
go: finding github.com/prometheus/common v0.0.0-20180110214958-89604d197083
go: finding github.com/prometheus/client_golang v0.9.0
go: finding github.com/miekg/dns v1.0.1
go: finding gopkg.in/yaml.v2 v2.2.1
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: downloading github.com/go-kit/kit v0.0.0-20170917202734-0d313fb5fb3a
go: downloading github.com/prometheus/common v0.0.0-20180110214958-89604d197083
go: downloading github.com/prometheus/client_golang v0.9.0
go: downloading golang.org/x/net v0.0.0-20171102191033-01c190206fbd
go: downloading github.com/miekg/dns v1.0.1
go: downloading gopkg.in/yaml.v2 v2.2.1
go: downloading github.com/golang/protobuf v0.0.0-20170919002109-ae59567b9aab
go: downloading github.com/prometheus/client_model v0.0.0-20170216185247-6f3806018612
go: downloading github.com/pkg/errors v0.0.0-20170910134614-2b3a18b5f0fb
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/prometheus/procfs v0.0.0-20170703101242-e645f4e5aaa8
go: downloading github.com/beorn7/perks v0.0.0-20160804104726-4c0e84591b9a
go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.5
go: downloading github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
go: downloading github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
go: downloading golang.org/x/crypto v0.0.0-20171231215028-0fcca4842a8d
go: downloading github.com/go-logfmt/logfmt v0.3.0
go: downloading github.com/go-stack/stack v1.6.0

**Comment by conseev** [comment]
This does seem to be related particularly to this makefile as https://github.com/foomo/pagespeed_exporter also uses Go and compiles on the same server. So it is not that the Go install itself is broken.

**Comment by conseev** [comment]
I resolved the issue by executing this on the server:

curl -s https://packagecloud.io/install/repositories/prometheus-rpm/release/script.rpm.sh | sudo bash
yum install blackbox_exporter
# rpm -ql blackbox_exporter
/etc/default/blackbox_exporter
/etc/prometheus/blackbox.yml
/usr/bin/blackbox_exporter
/usr/lib/systemd/system/blackbox_exporter.service
/var/lib/prometheus

**Comment by auge02-git** [comment]
how can i finish this problem?
