### ISSUE TITLE
feature - consul service discovery

### ISSUE THREAD

**Issue by pahoughton-sf** [prometheus/blackbox_exporter#434]
I'm planning to add the following http_probe module keys to support consul service discovery.

```yml
# The HTTP scheme the probe will use.
[ scheme: <string> | default = "http" ]

# The HTTP endpoint that will be probed
[ endpoint: <string> | default ""]
```

These keys will then be used to build the probe url from address:port as used by most prometheus jobs and provided by most prometheus service discovery methods, such as consul.

This url build funtionallity will be enabled via a new __param_addr.  Current full url functionality is unchanged via the __param_target.

The http_probe will build the full url from 'scheme:://addr/endpoint'

**Comment by brian-brazil** [comment]
You already pass the full URL as a target, you don't need to add this.

**Comment by pahoughton-sf** [comment]
The point is consul service discovery passes the address (host:port).  I'm using consul to provide the list of nodes to run a specific blackbox module check.  The check is for a specific url response on all nodes.
```yml

scheme: http
endpoint: api/v1/object?param=val

# prometheus.yml
- consul_sd_configs:
    services: myapisvc

```
consul service discovery only provides host:port. Blackbox exporter is the 'odd man out' that expects full end points in the service discovery section of the config.  This feature provides the flexibility to use both approaches.

Thanks for helping me clarify my intent :)

**Comment by brian-brazil** [comment]
This is already all supported, it's a matter of relabelling.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by baiyibing123** [comment]
> 关键是领事服务发现会通过地址（host：port）。我正在使用领事提供运行特定黑盒模块检查的节点列表。该检查是针对所有节点上的特定URL响应。
> 
> ```yaml
> 方案：http
> 端点：api / v1 / object？param = val 
> 
> ＃ prometheus.yml 
> - consul_sd_configs：
>     服务：myapisvc
> ```
> 
> 领事服务发现仅提供host：port。黑盒出口商是“奇怪的人”，期望在配置的服务发现部分中获得完整的端点。此功能提供了使用两种方法的灵活性。
> 
> 感谢您帮助我阐明意图：)

I had the same problem: How to add the URL when in suspense registration, such as 127.0.0.1:8000/ Health

> The point is consul service discovery passes the address (host:port). I'm using consul to provide the list of nodes to run a specific blackbox module check. The check is for a specific url response on all nodes.
> 
> ```yaml
> scheme: http
> endpoint: api/v1/object?param=val
> 
> # prometheus.yml
> - consul_sd_configs:
>     services: myapisvc
> ```
> 
> consul service discovery only provides host:port. Blackbox exporter is the 'odd man out' that expects full end points in the service discovery section of the config. This feature provides the flexibility to use both approaches.
> 
> Thanks for helping me clarify my intent :)

I had the same problem: How to add the URL when in suspense registration, such as 127.0.0.1:8000/ Health
