### ISSUE TITLE
Add "probe_ssl_cert_expiry" to have expiration date of the actual certificate as in Chrome/openssl (not the earliest expiration date as we have now in "probe_ssl_earliest_cert_expiry" metric)

### ISSUE THREAD

**Issue by dkutetsky** [prometheus/blackbox_exporter#442]
Related to the issue - https://github.com/prometheus/blackbox_exporter/issues/340

**Comment by brian-brazil** [comment]
Did you mean to make a PR?

**Comment by dkutetsky** [comment]
Actually, it was a feature request, not sure how it should be marked properly.

**Comment by brian-brazil** [comment]
This is a duplicate then.

**Comment by pir8g33k** [comment]
so any solution on this it seems we have the same issue 

@brian Brazil it seems the same issue i saw on repo, any other solution how to display the actual information of certificate expiration date ? we need this info as well as we monitor the remaining days of the ssl certificate
https://github.com/prometheus/blackbox_exporter/issues/340
https://github.com/prometheus/blackbox_exporter/pull/483
https://github.com/prometheus/blackbox_exporter/issues/442

**Comment by dkutetsky** [comment]
Hi @pir8g33k ,
You can use [fork with our fix](https://github.com/greg-solutions/blackbox_exporter/tree/feature/extend_cert_expire_data).

**Comment by pir8g33k** [comment]
> Hi @pir8g33k ,
> You can use [fork with our fix](https://github.com/greg-solutions/blackbox_exporter/tree/feature/extend_cert_expire_data).

Alright thank you so much @dkutetsky
