### ISSUE TITLE
“probe_ssl_earliest_cert_expiry” is missing in Linux version blackbox_exporter-0.14.0.linux-amd64

### ISSUE THREAD

**Issue by abovas0321** [prometheus/blackbox_exporter#443]
I have configured  blackbox_exporter-0.14.0.linux-amd64 version in linux box and couldn't find “probe_ssl_earliest_cert_expiry” in prometheus .  Could you please let me know which version I can find it.

**Comment by abovas0321** [comment]
This issue is fixed. I added the below lines and it worked 
   http:
      tls_config:
        insecure_skip_verify: true

**Comment by ashki1** [comment]
Hello
can you please tell me how did you fix this. I would like to see the full config for blackbox and prometheus. The one that you mentioned above did not work for me.

Thanks!
