### ISSUE TITLE
Add arg ping feature

### ISSUE THREAD

**Issue by efficks** [prometheus/blackbox_exporter#445]
I need to scan mobile devices on a network. These devices often go into sleep mode and in this mode, the PING is not possible to save batteries. Devices are still connected on the wifi and arp ping still works.
So, can we plan to add an arp ping in blackbox_exporter? I can try to do the merge request if it's a feature you planned to add.
If it's not in blackbox_exporter, I will make my own python script ;-)

**Comment by brian-brazil** [comment]
Prometheus is focused on v4/v6 rather than deeper down when it comes to SD and the like, so I think this might be a bit niche to add here. Your own exporter is probably the way to go here.

**Comment by efficks** [comment]
@brian-brazil Thank you. You can close the issue. I will create my own exporter.
