### ISSUE TITLE
dont_fragment is always enabled in ICMP probe

### ISSUE THREAD

**Issue by s1sfa** [prometheus/blackbox_exporter#453]
I was doing some tcpdump to check out how the operation of the TOS fork works. I noticed that DF is always set. I rolled back my blackbox_exporter to the master and rebuilt it and I see that Do Not Fragment is still always set. 
Even if I add the dont_fragment: false option DF bit is still set in the header.

I tested using IPv4 dont_fragment not specified and dont_fragment set to false

**Comment by brian-brazil** [comment]
I can't reproduce this, there's no DF flag on my machine in the request.

**Comment by s1sfa** [comment]
How did you test?

I've tested on two systems now. One is some old laptop running Ubuntu 18.04.1 LTS. The second is raspberry pi Raspbian GNU/Linux 9.4 (stretch).  

Here is a copy of .cap file I got from TCPDUMP(https://cloudup.com/cD5qIUVHklY). You can see that do not frag is set on out, but is not on the in. 

Here is my ICMP config from blackbox:
  icmp:
    prober: icmp
    icmp:
        ip_protocol_fallback: true


blackbox version on PI:
./blackbox_exporter --version
blackbox_exporter, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.11

laptop ubuntu, i think this is the latest binary
sudo ./blackbox_exporter --version
[sudo] password for chris:
blackbox_exporter, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.11.5

**Comment by brian-brazil** [comment]
I ran it on a 16.04 machine and looked at tcpdump.

**Comment by brian-brazil** [comment]
This seems likely to be something on your machine (MTU probing maybe?), if you manage to find a bug in the blackbox exporter that's actually it please let us know.
