### ISSUE TITLE
[feature] Expose SSL certificate fingerprint

### ISSUE THREAD

**Issue by marco-m** [prometheus/blackbox_exporter#455]
[template stolen from [Concurse project](https://github.com/concourse/concourse/tree/master/.github/ISSUE_TEMPLATE)]

## What challenge are you facing?

When my home Internet connectivity is down, my CPE router wants to be "smart": it impersonates the HTTP or HTTPS server of any on-going connection, just to display a silly HTML page telling me that the Internet connection is down.

This means that if I use the `http_probe`, I can get false positives: it seems that the probe is successful (Internet up), while it is my CPE router faking the response. To obviate this, I can set the configuration `fail_if_not_ssl: true`. This, together with `probe_success` makes the situation better, but I still don't know what was the failure.

## What would make this better?

If the `http_probe` exposed the SSL certificate fingerprint (maybe under a configuration switch?), then I could know exactly what is going on, and the blackbox_exporter could be used also to detect certain cases of MITM attacks.

## Are you interested in implementing this yourself?

Yes!

**Comment by brian-brazil** [comment]
Have you considered a regex on the body? Also, how is this not causing a to
failure?

**Comment by marco-m** [comment]
Hello Brian,

this is causing a failure, as I wrote:

> ... I can set the configuration fail_if_not_ssl: true. This, together with probe_success makes the situation better, but I still don't know what was the failure.

To be more explicit: with the current blackbox_exporter, `fail_if_not_ssl: true` and `probe_success` I will get a failure when my router wants to be smart. BUT, that is a generic failure, I don't know if a given failure is due to my router doing impersonation or to any other reason.

My proposal of the fingerprint makes it possible to know the reason of the failure. Or am I missing something?

In my understanding, the regex on the body would not work because I pass to the same http_probe many different web sites, they have nothing in common I can regex (again, unless I am missing something).

**Comment by brian-brazil** [comment]
You can check that the result does not match a certain regex.

**Comment by marco-m** [comment]
Ahhh, now I understand!
