### ISSUE TITLE
Nessus security issues

### ISSUE THREAD

**Issue by reachlin** [prometheus/blackbox_exporter#456]
We found the following issues on the blackbox server by Nessus:
- CGI Generic Command Execution (time-based). It may be possible to run arbitrary code on the remote web server.
- CGI Generic SQL Injection (blind). A CGI application hosted on the remote web server is potentially prone to SQL injection attack.
- CGI Generic SQL Injection (blind, time based). A CGI application hosted on the remote web server is potentially prone to SQL injection attack.

**Comment by SuperQ** [comment]
These appear to be false positives.

* There is no `exec()` functionality in the blackbox_exporter.
* There is no "SQL" functionality in the blackbox_exporter.

**Comment by brian-brazil** [comment]
Per information in the other issue, these are false positives. If you believe you'd found a security issue, please provide more exact details.
