### ISSUE TITLE
[Feature request] probe_http_status_code should be histogram

### ISSUE THREAD

**Issue by nutchalum** [prometheus/blackbox_exporter#471]
It'd be good to have `probe_http_status_code` as a histogram instead of counter.
or at least `probe_http_status_code`should be labeled with status code like `2xx`, `3xx`.

Please reconsider your decision,
Thank you.

**Comment by SuperQ** [comment]
`probe_http_status_code` is not a counter, it is a gauge value of the numeric status code.

**Comment by brian-brazil** [comment]
Agreed, this doesn't make sense.
