### ISSUE TITLE
Question: putting query params into target

### ISSUE THREAD

**Issue by bbkgh** [prometheus/blackbox_exporter#480]
Hi. How can i test a target that has query params (& sign) itself?
something like this commands:
curl 'http://localhost:9115/probe?module=http_2xx&debug=true&target=https://google.com&x=3&y=4'

**Comment by bbkgh** [comment]
We can escape target url.
in python:
urllib.quote(target_url, safe='')

**Comment by brian-brazil** [comment]
Prometheus will handle this for you when you're providing URL params.
