### ISSUE TITLE
[Feature request] Multipacket ping

### ISSUE THREAD

**Issue by xwatav** [prometheus/blackbox_exporter#481]
I've checked blackbox exporter operation with Wireshark, and found that the exporter creates single icmp echo requests. Would you consider adding multiple packets to a single probe, so it reports back a ratio that for example says 2/3 ping OK. Number of packets might be configurable. E.g. N=[1, 3, 5, ...] N defaults to 1, so it's backward compatible.

**Comment by SuperQ** [comment]
Dupe of https://github.com/prometheus/blackbox_exporter/issues/115
