### ISSUE TITLE
Offset should not be applied for explicitly set timeout

### ISSUE THREAD

**Issue by tdabasinskas** [prometheus/blackbox_exporter#491]
As per the following code, blackbox_exporter always applies `--timeout-offset` (defaulting to `0.5s`) to the timeout:

https://github.com/prometheus/blackbox_exporter/blob/dc53582740bcf20f1a618c806745a91c2d894345/main.go#L75-L92

There's a problem with this setting in the following cases:
- `--timeout-offset=0`: Prometheus might fail to scrape blackbox_exporter as the timeout (when combined with the network latency) might exceed Prometheus scrape timeout (that's the reason it's not `0` by default).
- `--timeout-offset=0.5`: it's not possible to have HTTP modules that expect response faster than `0.5` (as `timeout: 500ms` effectively becomes `timeout: 0ms`).

Would it be possible to apply the offset (`timeoutSeconds -= *timeoutOffset `) *only* when there's no explicitly defined timeout for a module? Meaning, that if the user explicitly set `timeout` field (which, as per the conditions, must be more than 0 and less than Prometheus scrape timeout) for some specific module, we can assume the user knows what he's doing and we use this timeout as is (without applying any offset).

An alternative can also be having per-module `timeout-offset` property, which allows the module to override not only the default time but default offset as well.

I can do a PR if agreed.

**Comment by brian-brazil** [comment]
> only when there's no explicitly defined timeout for a module? 

We can do that, presuming the header-offset is still a limit.

**Comment by tdabasinskas** [comment]
By `header-offset` you mean `X-Prometheus-Scrape-Timeout-Seconds`? If so, yes, that would still be the upper limit.

**Comment by brian-brazil** [comment]
Yes
