### ISSUE TITLE
Support for blackbox-probing XMPP services

### ISSUE THREAD

**Issue by horazont** [prometheus/blackbox_exporter#495]
This is a feature request.

Currently, there is no way to blackbox-probe [XMPP](https://tools.ietf.org/html/rfc6120) services with blackbox_exporter. This is because the XMPP protocol is not line-based, so the TCP prober cannot be used, and there are no specific probers for XMPP.

I have started to write my own [XMPP blackbox exporter](https://github.com/horazont/prometheus-xmpp-blackbox-exporter). This is in its very early stages; I plan to add the features mentioned in the readme in the next few weeks.

Would the blackbox_exporter team be interested in adding this to blackbox_exporter itself? I copied some of the structure of the blackbox_exporter to make it as easy to integrate as possible. I would be happy to rebase this into the blackbox exporter. The probe is based on the [mellium.im/xmpp](https://github.com/mellium/xmpp) package, maintained by a member of the XMPP community.

**Comment by brian-brazil** [comment]
A separate exporter is probably best, XMPP isn't as base a protocol as the others we support.

**Comment by horazont** [comment]
Alright, thanks. I allocated a port number for my exporter and I’ll continue to develop it independently.
