### ISSUE TITLE
Redirects through SSO with tokens

### ISSUE THREAD

**Issue by MarvelPhx** [prometheus/blackbox_exporter#497]
### Host operating system: output of `uname -a`
Linux 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.14.0 (branch: HEAD, revision: bba7ef76193948a333a5868a1ab38b864f7d968a)
  build user:       root@63d11aa5b6c6
  build date:       20190315-13:32:31
  go version:       go1.11.5

### What is the blackbox.yml module config.
modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ipv4"
      ip_protocol_fallback: false
      tls_config:
        insecure_skip_verify: true

### What is the prometheus.yml scrape config.
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: ['http_2xx']
    static_configs:
    - targets: ['https://mysite.com/test']

### What logging output did you get from adding `&debug=true` to the probe URL?
Multiple redirects to SSO and stopping at login. Without any supplied credentials (as any new users would see), should receive a new token that is then used to move on to the next page.

### What did you do that produced an error?
Not an error, but without being able to store the SSO token and use it on the next redirect, it stops with a 200 OK at the SSO login page.

### What did you expect to see?
If I curl with 'curl -s -k -L --ntlm -c cookies.txt "https://mysite.com/test"', it successfully grabs the SSO token and uses it to continue on and load the final page. If loaded from a browser, the SSO intercept is invisible for new users.

### What did you see instead?
It stops at the SSO login page and reports *that* page as 200 OK, which is not an accurate measure of the real page behind SSO.

**Comment by brian-brazil** [comment]
What type of token is this? Cookies should be preserved across requests, NTLM is not supported though.

**Comment by brian-brazil** [comment]
No response, so presuming it's an issue on their end.
