### ISSUE TITLE
Instance shown as "up" although status code 403 (module http_2xx)

### ISSUE THREAD

**Issue by svenmueller** [prometheus/blackbox_exporter#50]
Hi,

I'm using the latest Docker image of blackbox for probing targets. I'm having a target probe (module `http_2xx`, config as in https://github.com/prometheus/blackbox_exporter/blob/master/blackbox.yml) where the server returns status code `403` (due to IP resctriction), but the target instance is still shown as "up".I would expect status "down" since i'm using the defaul config for module `http_2xx` which checks for status code 200-300.

When looking at the value of `probe_http_status_code` for this instance, it shows `403`.

Any idea why the instance is still shown as "up"?

Cheers Sven

**Comment by brian-brazil** [comment]
You're looking for the `probe_success` metric.

If we used `up` then you'd lose all the other metrics when a probe failed.

**Comment by svenmueller** [comment]
Thx for the super fast answer 👍
