### ISSUE TITLE
Force use of HTTPS via Proxy

### ISSUE THREAD

**Issue by kirkeide** [prometheus/blackbox_exporter#503]
We're trying to probe a set of targets (all SSL/TSL only) via a proxy.  The module configuration looks like this:

  http_proxy_tls:
    prober: http
    timeout: 5s
    http:
      method: GET
      proxy_url: http://proxy.company.com:3128
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: true

The scrape targets are a static list:
  - job_name: "blackbox_exporter:http_sfp_tls"
    scrape_interval: 15m
    scrape_timeout: 15s
    metrics_path: /probe
    params:
      module: [ http_proxy_tls ]
    static_configs:
      - targets:
        - target1.company.com:443
        - target2.there.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

The issue is that there seems to be no way to force https (tls/ssl) connections to the targets.  As the configuration is, all the probes fail with 502 since the request via the proxy turns into 'http://target1.company.com:443' (no SSL/https) and these sites do not have a http redirect to https.  If I add https:// to the targets (in the static config list), the dns lookup fails (it looks to try to resolve 'https://target1.company.com' as the hostname, method as all).

Can a flag be added to the http module (such as use_https=(true|false)) to force https?

**Comment by kirkeide** [comment]
@fetep

**Comment by brian-brazil** [comment]
Prefixing with https:// should work.

**Comment by kirkeide** [comment]
It doesn't (at least via the proxy)

**Comment by kirkeide** [comment]
I'll run my test again and post the output shortly.

**Comment by kirkeide** [comment]
Ran the tests again and also tried using CONNECT for the method.  The first one is just connecting with curl via the proxy.

######################
###
### Connection to target with curl to show we can get there via proxy

 curl -v --insecure --proxy http://proxy.company.com:3128 https://target1.company.com:443
* Rebuilt URL to: https://target1.company.com:443/
*   Trying 10.x.y.102...
* TCP_NODELAY set
* Connected to proxy.company.com (10.x.y.102) port 3128 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to target1.company.com:443
> CONNECT target1.company.com:443 HTTP/1.1
> Host: target1.company.com:443
> User-Agent: curl/7.61.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: [REMOVED]
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: [REMOVED]
*  start date: Mar  6 00:00:00 2018 GMT
*  expire date: Mar 10 12:00:00 2020 GMT
*  issuer: C=US; [REMOVED]
*  SSL certificate verify ok.
> GET / HTTP/1.1


###########################
###
### No https:// in target via blackbox_exporter

[user@host ~]$ curl -v --insecure 'http://localhost:9115/probe?target=target1.company.com:443&module=http_proxy_tls&debug=true'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9115 (#0)
> GET /probe?target=target1.company.com:443&module=http_proxy_tls&debug=true HTTP/1.1
> Host: localhost:9115
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Mon, 29 Jul 2019 16:34:40 GMT
< Transfer-Encoding: chunked
<
Logs for the probe:
ts=2019-07-29T16:34:40.645508129Z caller=main.go:118 module=http_proxy_tls target=target1.company.com:443 level=info msg="Beginning probe" probe=http timeout_seconds=4.5
ts=2019-07-29T16:34:40.645641354Z caller=utils.go:42 module=http_proxy_tls target=target1.company.com:443 level=info msg="Resolving target address" ip_protocol=ip6
ts=2019-07-29T16:34:40.686315921Z caller=utils.go:55 module=http_proxy_tls target=target1.company.com:443 level=warn msg="Resolution with IP protocol failed, attempting fallback protocol" fallback_protocol=ip4 err="address target1.company.com: no suitable address found"
ts=2019-07-29T16:34:40.686648364Z caller=utils.go:75 module=http_proxy_tls target=target1.company.com:443 level=info msg="Resolved target address" ip=x.y.z.156
ts=2019-07-29T16:34:40.686702883Z caller=http.go:349 module=http_proxy_tls target=target1.company.com:443 level=info msg="Making HTTP request" url=http://x.y.z.156:443 host=target1.company.com:443
ts=2019-07-29T16:34:40.729866037Z caller=http.go:368 module=http_proxy_tls target=target1.company.com:443 level=info msg="Received HTTP response" status_code=502
ts=2019-07-29T16:34:40.729916101Z caller=http.go:383 module=http_proxy_tls target=target1.company.com:443 level=info msg="Invalid HTTP response status code, wanted 2xx" status_code=502
ts=2019-07-29T16:34:40.73000524Z caller=http.go:450 module=http_proxy_tls target=target1.company.com:443 level=info msg="Response timings for roundtrip" roundtrip=0 start=2019-07-29T16:34:40.686760434Z dnsDone=2019-07-29T16:34:40.688435885Z connectDone=2019-07-29T16:34:40.689904156Z gotConn=2019-07-29T16:34:40.689917822Z responseStart=2019-07-29T16:34:40.729815788Z end=2019-07-29T16:34:40.729996706Z
ts=2019-07-29T16:34:40.730050871Z caller=main.go:131 module=http_proxy_tls target=target1.company.com:443 level=error msg="Probe failed" duration_seconds=0.084480638



Metrics that would have been returned:
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.04099123
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.084480638
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length 3682
# HELP probe_http_duration_seconds Duration of http request by phase, summed over all redirects
# TYPE probe_http_duration_seconds gauge
probe_http_duration_seconds{phase="connect"} 0.001482112
probe_http_duration_seconds{phase="processing"} 0.0398978
probe_http_duration_seconds{phase="resolve"} 0.04099123
probe_http_duration_seconds{phase="tls"} 0
probe_http_duration_seconds{phase="transfer"} 0.000180918
# HELP probe_http_redirects The number of redirects
# TYPE probe_http_redirects gauge
probe_http_redirects 0
# HELP probe_http_ssl Indicates if SSL was used for the final redirect
# TYPE probe_http_ssl gauge
probe_http_ssl 0
# HELP probe_http_status_code Response HTTP status code
# TYPE probe_http_status_code gauge
probe_http_status_code 502
# HELP probe_http_version Returns the version of HTTP of the probe response
# TYPE probe_http_version gauge
probe_http_version 1.1
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0



Module configuration:
prober: http
timeout: 5s
http:
  ip_protocol_fallback: true
  method: GET
  proxy_url: http://proxy.company.com:3128
  tls_config:
    insecure_skip_verify: true
tcp:
  ip_protocol_fallback: true
icmp:
  ip_protocol_fallback: true
dns:
  ip_protocol_fallback: true
* Connection #0 to host localhost left intact
[user@host ~]$

################################################
####
#### Add https:// to target via blackbox_exporter

[user@host ~]$ curl -v --insecure 'http://localhost:9115/probe?target=https://target.company.com:443&module=http_proxy_tls&debug=true'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9115 (#0)
> GET /probe?target=https://target1.company.com:443&module=http_proxy_tls&debug=true HTTP/1.1
> Host: localhost:9115
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Mon, 29 Jul 2019 16:36:22 GMT
< Transfer-Encoding: chunked
<
Logs for the probe:
ts=2019-07-29T16:36:22.374600325Z caller=main.go:118 module=http_proxy_tls target=https://target1.company.com:443 level=info msg="Beginning probe" probe=http timeout_seconds=4.5
ts=2019-07-29T16:36:22.374705668Z caller=utils.go:42 module=http_proxy_tls target=https://target1.company.com:443 level=info msg="Resolving target address" ip_protocol=ip6
ts=2019-07-29T16:36:22.402365622Z caller=utils.go:55 module=http_proxy_tls target=https://target1.company.com:443 level=warn msg="Resolution with IP protocol failed, attempting fallback protocol" fallback_protocol=ip4 err="address target1.company.com: no suitable address found"
ts=2019-07-29T16:36:22.402583688Z caller=utils.go:75 module=http_proxy_tls target=https://target1.company.com:443 level=info msg="Resolved target address" ip=x.y.z.156
ts=2019-07-29T16:36:22.402619248Z caller=http.go:349 module=http_proxy_tls target=https://target1.company.com:443 level=info msg="Making HTTP request" url=https://x.y.z.156:443 host=target1.company.com:443
ts=2019-07-29T16:36:22.545074435Z caller=http.go:364 module=http_proxy_tls target=https://target1.company.com:443 level=error msg="Error for HTTP request" err="Get https://x.y.z.156:443: Forbidden"
ts=2019-07-29T16:36:22.545110995Z caller=http.go:450 module=http_proxy_tls target=https://target1.company.com:443 level=info msg="Response timings for roundtrip" roundtrip=0 start=2019-07-29T16:36:22.40266302Z dnsDone=2019-07-29T16:36:22.402891536Z connectDone=2019-07-29T16:36:22.403775197Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=0001-01-01T00:00:00Z
ts=2019-07-29T16:36:22.545143555Z caller=main.go:131 module=http_proxy_tls target=https://target1.company.com:443 level=error msg="Probe failed" duration_seconds=0.170494703



Metrics that would have been returned:
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.027864958
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.170494703
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length 0
# HELP probe_http_duration_seconds Duration of http request by phase, summed over all redirects
# TYPE probe_http_duration_seconds gauge
probe_http_duration_seconds{phase="connect"} 0
probe_http_duration_seconds{phase="processing"} 0
probe_http_duration_seconds{phase="resolve"} 0.027864958
probe_http_duration_seconds{phase="tls"} 0
probe_http_duration_seconds{phase="transfer"} 0
# HELP probe_http_redirects The number of redirects
# TYPE probe_http_redirects gauge
probe_http_redirects 0
# HELP probe_http_ssl Indicates if SSL was used for the final redirect
# TYPE probe_http_ssl gauge
probe_http_ssl 0
# HELP probe_http_status_code Response HTTP status code
# TYPE probe_http_status_code gauge
probe_http_status_code 0
# HELP probe_http_version Returns the version of HTTP of the probe response
# TYPE probe_http_version gauge
probe_http_version 0
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0



Module configuration:
prober: http
timeout: 5s
http:
  ip_protocol_fallback: true
  method: GET
  proxy_url: http://proxy.company.com:3128
  tls_config:
    insecure_skip_verify: true
tcp:
  ip_protocol_fallback: true
icmp:
  ip_protocol_fallback: true
dns:
  ip_protocol_fallback: true
* Connection #0 to host localhost left intact
[ec2-user@ip-10-207-40-133 ~]$



##########################
###
### Try using CONNECT in module


Module configuration:
prober: http
timeout: 5s
http:
  ip_protocol_fallback: true
  fail_if_not_ssl: true
  method: CONNECT
  proxy_url: http://proxy.company.com:3128
  tls_config:
    insecure_skip_verify: true
tcp:
  ip_protocol_fallback: true
icmp:
  ip_protocol_fallback: true
dns:
  ip_protocol_fallback: true

### With https:// in target (CONNECT is malformed)
[user@host ~]$ curl -v --insecure 'http://localhost:9115/probe?target=https://target1.company.com:443&module=http_proxy_tls&debug=true'

*snip*
ts=2019-07-29T17:16:54.499419184Z caller=http.go:364 module=http_proxy_tls target=https://target1.company.com:443 level=error msg="Error for HTTP request" err="Connect https://x.y.z.156:443: Forbidden"

### Without https:// in target (No SSL)
[user@host ~]$ curl -v --insecure 'http://localhost:9115/probe?target=target1.company.com:443&module=http_proxy_tls&debug=true'

*snip*
ts=2019-07-29T17:18:28.342086336Z caller=http.go:349 module=http_proxy_tls target=target1.company.com:443 level=info msg="Making HTTP request" url=http://x.y.z.156:443 host=target1.company.com:443
ts=2019-07-29T17:18:28.345105762Z caller=http.go:368 module=http_proxy_tls target=target1.company.com:443 level=info msg="Received HTTP response" status_code=403
ts=2019-07-29T17:18:28.345123115Z caller=http.go:383 module=http_proxy_tls target=target1.company.com:443 level=info msg="Invalid HTTP response status code, wanted 2xx" status_code=403
ts=2019-07-29T17:18:28.345168216Z caller=http.go:450 module=http_proxy_tls target=target1.company.com:443 level=info msg="Response timings for roundtrip" roundtrip=0 start=2019-07-29T17:18:28.34212644Z dnsDone=2019-07-29T17:18:28.342345247Z connectDone=2019-07-29T17:18:28.343345894Z gotConn=2019-07-29T17:18:28.343353589Z responseStart=2019-07-29T17:18:28.345072387Z end=2019-07-29T17:18:28.345162988Z
ts=2019-07-29T17:18:28.345189593Z caller=http.go:499 module=http_proxy_tls target=target1.company.com:443 level=error msg="Final request was not over SSL"
ts=2019-07-29T17:18:28.345200095Z caller=main.go:131 module=http_proxy_tls target=target1.company.com:443 level=error msg="Probe failed" duration_seconds=0.003730098

**Comment by kirkeide** [comment]
Sorry about the horrible markup from the cut-n-paste of my text...  Not sure how to make it plain text.

**Comment by brian-brazil** [comment]
>  level=error msg="Error for HTTP request" err="Get https://x.y.z.156:443: Forbidden"

It looks like something isn't liking your request, this isn't a blackbox exporter issue.

**Comment by kirkeide** [comment]
Why does it work with curl via the proxy then?  And the appropriate method for SSL/TLS via the proxy would be CONNECT, no?

**Comment by brian-brazil** [comment]
Curl is performing a different request.

**Comment by kirkeide** [comment]
Correct.  curl is doing 'CONNECT target1.company.com:443' and starts TLS since the final destination is https I'm assuming.  blackbox exporter will use CONNECT as the method, but doesn't start TLS it seems (last example above).

I also tried including 'https://' in the target name, but I'm pretty sure 'CONNECT https://target1.company.com:443' is not a valid connect request.

**Comment by carlosflorencio** [comment]
Hi, can this be due to http2?

**Comment by StrawberryJuice** [comment]
It seems that the issue is that the SNI header is not sent when making an request.

This issue is not specifically related to the usage of an HTTP forwarding proxy it seems.
However you will encounter this issue when you have restricted access to the internet due too ACLs on specific domains. By default the blackbox exporter is making requests directly to the resolved IP-address of the domain without setting the SNI header if the `server_name` is not defined in the configuration according to code.

Could you add/ append the configuration below to your configuration and try again?
`
tls_config:
  server_name: example.com
`

**Comment by ulrichSchreiner** [comment]
hi,

i have exact the same problem. my workaround is to use `http` as the protocol and trust the target's to do a redirect to `https`. this works. 

but giving a `https` URL with a proxy does not work.

**Comment by Nurlan199206** [comment]
blackbox exporter not working via proxy for me too.

**Comment by Scapal** [comment]
Same here blackbox exporter with an http proxy and an https target doesn't work

```
prober: http
http:
    ip_protocol_fallback: true
    proxy_url: http://proxy._________.com:10080
    tls_config:
        insecure_skip_verify: true
```

```
ts=2019-11-21T15:59:48.019214632Z caller=http.go:318 module=proxy_http_2xx target=https://www._____.biz level=info msg="Resolved target address" ip=1x.xxx.xxx.147
ts=2019-11-21T15:59:48.019349727Z caller=client.go:250 module=proxy_http_2xx target=https://www._____.biz level=info msg="Making HTTP request" url=https://1x.xxx.xxx.147 host=www.______.biz
ts=2019-11-21T15:59:48.045136023Z caller=main.go:119 module=proxy_http_2xx target=https://www._____.biz level=error msg="Error for HTTP request" err="Get https://1x.xxx.xxx.147: Proxy Authentication 
```

But the following Go code does work and returns HTTP status 200:

```
func main() {
	proxyString := "http://proxy._____.com:10080"
	proxyURL, _ := url.Parse(proxyString)

	tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		Proxy:           http.ProxyURL(proxyURL),
	}

	client := &http.Client{}
	client.Transport = tr

	request, err := http.NewRequest("GET", "https://www.______.biz", nil)
	
	resp, err := client.Do(request)

	if err != nil {
		log.Fatalln(err)
		return
	}
	defer resp.Body.Close()

	log.Printf("HTTP Status: %s\n", resp.Status)
}
```

**Comment by Scapal** [comment]
For me the problem was that the target hostname is resolved locally instead of letting the proxy do it. 
I've created a new issue: module HTTP: hostname resolved locally even when using a proxy #553

**Comment by brian-brazil** [comment]
Have you looked at running the blackbox exporter behind the proxy?

**Comment by Scapal** [comment]
Not an option as I want to be in the same conditions as the local users.

**Comment by brian-brazil** [comment]
Reading through again, the original issue is a usage question which isn't a problem on our end. Any other usage questions should be brought up on the mailing list.

**Comment by liuzheng** [comment]
I have the same issue, and after some coding,finaly,  I found the solution.
```
  https_via_proxy:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      fail_if_ssl: false
      fail_if_not_ssl: true
      headers:
        Host: www.example.com
      tls_config:
        server_name: www.example.com
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      ip_protocol_fallback: false  # no fallback to "ip6"
      proxy_url:     "http://some.proxy.com:3128"
```

as my test, this will be work
```
      headers:
        Host: www.example.com
      tls_config:
        server_name: www.example.com
        insecure_skip_verify: true
```
