### ISSUE TITLE
The COUNT_HANDSHAKE_ERRORS parameter of mysql is constantly increased through blackbox_exporter monitoring mysql's port 3306.

### ISSUE THREAD

**Issue by kerry8865** [prometheus/blackbox_exporter#505]
1. After using blackbox_exporter to monitor mysql TCP 3306 port for a period of time, it is found that a large amount of "2019-08-03T03: 08:10.303437z 132454 [Note] Got an error reading communication packets" error log in mysql.Mysqlr port 3306 appears when you are connected to mysqlr port through the mysql customer port from the host where blackbox_exporter is installed:
"Host is blocked because of many connection errors;Unblock with 'mysqladmin flush - hosts"
2. After elimination, the COUNT_HANDSHAKE_ERRORS parameter of mysql is no longer increased after the blackbox_exporter is in charge of monitoring port 3306.
3. Please help to confirm that the use of blackbox_exporter to monitor mysql TCP 3306 port leads to the increase of COUNT_HANDSHAKE_ERRORS parameter value?

1. 在使用blackbox_exporter监控mysql tcp 3306端口一段时间后，发现mysql出现大量的“2019-08-03T03:08:10.303437Z 132454 [Note] Got an error reading communication packets” 错误日志，从安装blackbox_exporter应用的主机上通过mysql客户端口连接mysqlr 3306端口时出现：
“Host is blocked because of many connection errors; unblock with ‘mysqladmin flush-hosts”
2. 通过排查后，把blackbox_exporter监控3306端口去除后mysql的COUNT_HANDSHAKE_ERRORS参数值不再增加。
3. 请帮忙确认，使用blackbox_exporter监控mysql tcp 3306端口，会导致COUNT_HANDSHAKE_ERRORS参数值不断增加的原因？

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
