### ISSUE TITLE
Allow arbitrary proxy configuration for probes

### ISSUE THREAD

**Issue by sanbornick** [prometheus/blackbox_exporter#508]
Currently proxy configuration is global. To test various egress paths from a complex network one may need the ability to configure arbitrary proxy settings for specific probes or groups of probes.

**Comment by brian-brazil** [comment]
Proxy configuration is per-module, so you should already be able to this for HTTP.

**Comment by sanbornick** [comment]
You are so very right, my apologies. I should learn to read.
