### ISSUE TITLE
Running "make test" locally exits with code 2

### ISSUE THREAD

**Issue by snebel29** [prometheus/blackbox_exporter#516]
### Host operating system
```text
Linux snebel29-linux 5.0.0-27-generic #28~18.04.1-Ubuntu SMP Thu Aug 22 03:00:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
### blackbox_exporter version
```text
$ ./blackbox_exporter --version
blackbox_exporter, version 0.14.0 (branch: master, revision: ce8e9952a074768995cb67de0bc31bb43c1ec7c1)
  build user:       snebel29@snebel29-linux
  build date:       20190904-17:01:53
  go version:       go1.12.6
```

### What is the blackbox.yml module config.
N/A

### What is the prometheus.yml scrape config.
N/A

### What logging output did you get from adding `&debug=true` to the probe URL?
N/A

### What did you do that produced an error?
```console
$ make test
```
### What did you expect to see?
By default in master branch, I would expect the test suite to run and report success/failures for every test case

### What did you see instead?
```console
$ make test
>> running all tests
GO111MODULE=on go test -race  -mod=vendor ./...
go test: mod flag may be set only once
run "go help test" or "go help testflag" for more information
Makefile.common:151: recipe for target 'common-test' failed
make: *** [common-test] Error 2
```

**Comment by snebel29** [comment]
Please, disregard this Issue there was a problem with my local variables environment that I've failed to see initially :disappointed:

**Comment by tamanjoku** [comment]
Hi @snebel29 what was the problem with you local environment variables?

**Comment by snebel29** [comment]
If I remember correctly my IDE Goland was setting -mod vendor flag again on top of the flags being set on the make file...

**Comment by tamanjoku** [comment]
Do you know where I can disable this?

**Comment by snebel29** [comment]
I believe settings>Go>Go Modules(vgo)
