### ISSUE TITLE
Support for --web.external-url and --web.route-prefix in 0.15.0 is incomplete

### ISSUE THREAD

**Issue by siebenmann** [prometheus/blackbox_exporter#519]
### Host operating system: output of `uname -a`
Linux hawkwind.cs 5.2.11-200.fc30.x86_64 #1 SMP Thu Aug 29 12:43:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.15.0 (branch: HEAD, revision: 3f726a8a4489ea84a7163e37ba337f9b8332da63)
  build user:       root@3280fda7d3fc
  build date:       20190911-12:52:20
  go version:       go1.12.9

### The problem

If you run Blackbox with the new --web.external-url and --web.route-prefix options to try to operate it behind a reverse proxy, Blackbox's front page HTML still produces incorrect absolute links for the links to logs for probes, instead of either relative links or correct absolute links that use the external URL you set.

Looking at the code in commit 252a878a2c0e4b5961f04c765ca969224a8e0150, I think it should be prefixing these links with `*externalURL` instead of `*routePrefix` or simply leaving them as relative links. As I understand the settings, --web.route-prefix is the prefix that Blackbox sees in the requests from the front-end server, while --web.external-url is the external address, so visible URLs should always be generated using the latter (while being matched through the former).

### What did you do that produced an error?

Run `blackbox_exporter --config.file blackbox.yml --web.external-url=https://example.org/blackbox/ --web.route-prefix=/`, make a probe (eg `curl "localhost:9115/probe?module=http_2xx&target=https://google.com/"`), and then look at the HTML for Blackbox's front page. In the HTML, logs for probes will be linked as eg `<a href='/logs?id=0'>Logs</a>`, which is an incorrect external URL (it should be `/blackbox/logs?id=0`, even without the host).

**Comment by brian-brazil** [comment]
The links are meant to be all relative. Would you like to send a PR?

**Comment by snebel29** [comment]
I'm sorry to hear that @siebenmann , as you already noticed the following [line](https://github.com/prometheus/blackbox_exporter/blob/252a878a2c0e4b5961f04c765ca969224a8e0150/main.go#L327) missed the update back to relative path.

Once I get home I will triple check everything and post the test scenarios to ensure this is working as expected, adding testing for that area may have helped.
