### ISSUE TITLE
Unexpected 403 when probing for 200

### ISSUE THREAD

**Issue by krkahn** [prometheus/blackbox_exporter#526]
### Host operating system: output of `uname -a`
Linux host 5.2.9-200.fc30.x86_64 #1 SMP Fri Aug 16 21:37:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.14.0

### What is the blackbox.yml module config.
modules:
  http_2xx_ignore_redirects:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      tls_config:
        insecure_skip_verify: true
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      preferred_ip_protocol: "ip4"

  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
### What is the prometheus.yml scrape config.
  - job_name: 'http_endpoints'
    metrics_path: /probe
    file_sd_configs:
      - files:
        - "/etc/prometheus/http_endpoints.yml"
    params:
      module: [http_2xx_ignore_redirects]  # Look for a HTTP 200 response.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.

### What logging output did you get from adding `&debug=true` to the probe URL?
Logs for the probe:
Logs for the probe:
ts=2019-09-18T18:30:21.688812643Z caller=main.go:118 module=http_2xx_ignore_redirects target=http://example.com level=info msg="Beginning probe" probe=http timeout_seconds=9.5
ts=2019-09-18T18:30:21.688912506Z caller=utils.go:42 module=http_2xx_ignore_redirects target=http://example.com level=info msg="Resolving target address" ip_protocol=ip4
ts=2019-09-18T18:30:21.689602603Z caller=utils.go:75 module=http_2xx_ignore_redirects target=http://example.com level=info msg="Resolved target address" ip=example
ts=2019-09-18T18:30:21.689636355Z caller=http.go:349 module=http_2xx_ignore_redirects target=http://example.com level=info msg="Making HTTP request" url=http://[example] host=example.com
ts=2019-09-18T18:30:21.80994788Z caller=http.go:305 module=http_2xx_ignore_redirects target=http://example.com level=info msg="Received redirect" url=https://www.example.com/
ts=2019-09-18T18:30:21.83852554Z caller=http.go:368 module=http_2xx_ignore_redirects target=http://example.com level=info msg="Received HTTP response" status_code=403
ts=2019-09-18T18:30:21.838552726Z caller=http.go:383 module=http_2xx_ignore_redirects target=http://example.com level=info msg="Invalid HTTP response status code, wanted 2xx" status_code=403
ts=2019-09-18T18:30:21.838617998Z caller=http.go:450 module=http_2xx_ignore_redirects target=http://example.com level=info msg="Response timings for roundtrip" roundtrip=0 start=2019-09-18T14:30:21.689684132-04:00 dnsDone=2019-09-18T14:30:21.689684132-04:00 connectDone=2019-09-18T14:30:21.749121322-04:00 gotConn=2019-09-18T14:30:21.749126152-04:00 responseStart=2019-09-18T14:30:21.809901157-04:00 end=0001-01-01T00:00:00Z
ts=2019-09-18T18:30:21.838647464Z caller=http.go:450 module=http_2xx_ignore_redirects target=http://example.com level=info msg="Response timings for roundtrip" roundtrip=1 start=2019-09-18T14:30:21.810062399-04:00 dnsDone=2019-09-18T14:30:21.811200235-04:00 connectDone=2019-09-18T14:30:21.816577902-04:00 gotConn=2019-09-18T14:30:21.832788219-04:00 responseStart=2019-09-18T14:30:21.838496346-04:00 end=2019-09-18T14:30:21.838612259-04:00
ts=2019-09-18T18:30:21.838672952Z caller=main.go:131 module=http_2xx_ignore_redirects target=http://example.com level=error msg="Probe failed" duration_seconds=0.149828363

### What did you do that produced an error?
Probed for HTTP 200 using blackbox exporter. All other hosts work fine, this returns a 403 which (somewhat) jives with the output of curl -vs, but not curl -kIL.

### What did you expect to see?
probe_success 1 and a 200 value. 

### What did you see instead?
probe_sucess 0 and a 403 value.

curl -kIL host returns the expected output. 
curl -vs host -H 'HOST:' > /dev/null returns a 400.

Sorry - on further review this looks a lot like: https://github.com/prometheus/blackbox_exporter/issues/237

**Comment by krkahn** [comment]
Closing this. Repeat issue and I've already worked around it - sorry for the spam.

**Comment by soflane** [comment]
What was your workaround @krkahn ? 
I'm getting this error too
