### ISSUE TITLE
Bearer Token does not work with Openstack Endpoints

### ISSUE THREAD

**Issue by dariuszsq** [prometheus/blackbox_exporter#528]
Team,

Looks bearer token is not working with Openstack API Endpoints. In order to take information from API i need to use header like that:
headers:
          Host: xxxxx.net
          Content-Type: application/json
          X-Auth-Token: <secret>

This solution is fine but anyone can use token as this is showing in plain text on black-box exporter configuration website

Can you please check ?
Thanks

**Comment by brian-brazil** [comment]
That's not a bearer token, we can't support every possible non-standard auth method I'm afraid.
