### ISSUE TITLE
Question regarding probing remote instances having basic auth

### ISSUE THREAD

**Issue by svenmueller** [prometheus/blackbox_exporter#53]
Hi,

Some of our instances (e.g. staging servers) are protected using BASIC AUTH. Is there a way using blackbox-exporter to probe those servers (e.g. using module `http_2xx`)

Thx in Advance,
Sven

**Comment by brian-brazil** [comment]
You can pass in headers with the http module, which would let you do basic auth.

**Comment by brian-brazil** [comment]
Yes, you'd need a module config per different set of credentials.

I'd suggest looking into having a monitoring set of credentials that works across targets.

**Comment by svenmueller** [comment]
Yes, that would be one way of limiting the amount of required modules.

Btw, thx for your awesome work here (and all other Prometheus related project). I really appreciate it!

Cheers Sven
