### ISSUE TITLE
whether the blackbox_exporter can limit the times of request ?

### ISSUE THREAD

**Issue by i6448038** [prometheus/blackbox_exporter#531]
It is easly know the blackbox_exporter agent is just a http server in the deployed machine，anybody can visit the server in any time，so，somebody can attack the host machine with large number of requests. Should we do something to prevent it?

**Comment by brian-brazil** [comment]
https://prometheus.io/docs/operating/security/#denial-of-service

If a malicious party can get to the blackbox exporter, you likely have much bigger problems.

**Comment by i6448038** [comment]
@brian-brazil you mean I can forbid malicious users to visit  the blackbox exporter with the help of prometheus?

**Comment by snebel29** [comment]
Your blackbox exporter should be deployed in a secured and trusted network,
Additionally you could secure the access by exposing it through a reverse
proxy that requires authentication.

**Comment by brian-brazil** [comment]
This question was answered.
