### ISSUE TITLE
Request: Websocket support

### ISSUE THREAD

**Issue by ddorgan** [prometheus/blackbox_exporter#536]
Is there any plan to implement websocket support with the blackbox exporter? This would be super useful for some web applications which do all their RPC calls over websockets.

**Comment by brian-brazil** [comment]
That's not something that is planned, I'd suggest a custom exporter for more specific protocols like that.

**Comment by ddorgan** [comment]
Ok and thanks for the prompt reply!

**Comment by thevops** [comment]
It'd be nice to reconsider adding WebSocket support to Blackbox. The popularity of this protocol is growing.
What do you think?
