### ISSUE TITLE
When using regex on the body, only one url succeeds

### ISSUE THREAD

**Issue by raptile** [prometheus/blackbox_exporter#547]
Because the regex in the config is used for all the hosts, only one endpoint succeeds.
When you want to get metrics from multiple services it should be possible to perform regex on the body per host so all the checks will pass

prometheus.yml
  - job_name: 'siteA'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
    - targets:
      - http://siteal:80
  - job_name: 'siteB'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
    - targets:
      - http://siteb:80
  - job_name: 'siteC'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
    - targets:
      - http://sitec:80
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115

cutom config:
<..>
      fail_if_body_not_matches_regexp:
      - "this is the body from site B"
<..>

Only the probe for site B succeeds.
Site A and C fails because the body does not match "this is the body from site B"

Am i doing it wrong and in case i am not, is it possible to add a config per site?

Thanks in advance for the reply

**Comment by brian-brazil** [comment]
If you want to perform different tests, you'll need different modules. I'd suggest having one module that will work for any of the sites, as that's enough for a basic smoke test.
