### ISSUE TITLE
Support NTLM Authentication for HTTP probes

### ISSUE THREAD

**Issue by thewilli** [prometheus/blackbox_exporter#549]
Please consider adding support for NTLM authentication, e.g. with [this library](https://github.com/Azure/go-ntlmssp). It would help to especially probe Microsoft-based products which do not allow basic auth or anonymous access.

**Comment by brian-brazil** [comment]
I'm not sure we want to go down the route of supporting NTLM everywhere, and that library doesn't seem to even cover everything.

**Comment by thewilli** [comment]
> I'm not sure we want to go down the route of supporting NTLM everywhere

Well, why *shouldn't* it be supported? This is a great solution for probing HTTP-based resources. If you draw a line here, it would require another solution with an otherwise similar feature set, i.e. reinventing the wheel.

Sure, it's nice to have a clean and lean codebase, but I'm not asking to implement [RFC 2324](https://tools.ietf.org/html/rfc2324), and NTLM is most times the easiest way to authenticate against public endpoints of Microsoft products (e.g. Exchange Web Services). I do clearly see a benefit here.

So would you accept a PR?

**Comment by brian-brazil** [comment]
We can't practically support every possible bespoke auth mechanism that every company comes up with. Requests for NTLM have been very sparse, so it seems to me it's not worth the maintenance effort - particularly for something that noone on prometheus-team is likely familiar with.

> RFC 2324

The blackbox exporter should support that already.

**Comment by thewilli** [comment]
> We can't practically support every possible bespoke auth mechanism that every company comes up with.

True. But this isn't some strange mechanism no one actually uses. Yes, it's stupid, and I'd prefer not to rely on it either. But it's (unfortunately) widely used and the less painful alternative to Kerberos from an implementer's point of view.

> Requests for NTLM have been very sparse

Might not actually reflect what's needed. Not all people raise their voice if they're missing a feature.

> so it seems to me it's not worth the maintenance effort

The library itself is maintained by MS and OSS contributors. As for the implementation in the exporter's codebase - well, shouldn't be too much effort, is it?

**Comment by brian-brazil** [comment]
> Not all people raise their voice if they're missing a feature.

Oh they do. We've had more requests for non-standard bearer token auth than we've had for NTLM.

> As for the implementation in the exporter's codebase - well, shouldn't be too much effort, is it?

The relevant code is shared by many projects, including Prometheus scraping.

**Comment by thewilli** [comment]
Okay, let's keep this brief. Will you accept or reject a PR if I added basic NTLM support using the mentioned library?

**Comment by brian-brazil** [comment]
I'll reject it.
