### ISSUE TITLE
Add failed/success probe counters into the metrics

### ISSUE THREAD

**Issue by vpr-ossteam** [prometheus/blackbox_exporter#550]
### Host operating system: output of `uname -a`

Linux blackbox 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.14.0 (branch: HEAD, revision: bba7ef76193948a333a5868a1ab38b864f7d968a)
  build user:       root@63d11aa5b6c6
  build date:       20190315-13:32:31
  go version:       go1.11.5

### What is the blackbox.yml module config.

n/a

### What is the prometheus.yml scrape config.

n/a

### What logging output did you get from adding `&debug=true` to the probe URL?

n/a

### What did you do that produced an error?

This is feature-request. No errors.

### What did you expect to see?

We want to have metric which shows how many times probe has been failed/succeeded. This will help to understand when we have issue with channel to our probe server.

### What did you see instead?

In current version of blackbox expoter we see these metrics (go metrics has excluded):

`
curl -sSL http://localhost:9115/metrics | grep -vE '^(#|go|process)'
blackbox_exporter_build_info{branch="HEAD",goversion="go1.11.5",revision="bba7ef76193948a333a5868a1ab38b864f7d968a",version="0.14.0"} 1
blackbox_exporter_config_last_reload_success_timestamp_seconds 1.5703642612404559e+09
blackbox_exporter_config_last_reload_successful 1
promhttp_metric_handler_requests_in_flight 1
promhttp_metric_handler_requests_total{code="200"} 183700
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
`

**Comment by SuperQ** [comment]
Something like `probes_failed_total{module="foo"}`? Technically you can this by looking at `avg_over_time(probe_success[X])`, but I could see how this might be useful for monitoring the exporter overall.

**Comment by brian-brazil** [comment]
This seems like something already covered by `up`, as that plus `probe_success` is going to catch any systemic issue.

**Comment by n0guest** [comment]
> This seems like something already covered by `up`, as that plus `probe_success` is going to catch any systemic issue.

In our case, for example, one instance of blackbox_exporter could be used by many different Prometheis (we're using those exporters as geo-distributed network sensors). But each of Prometheis will see only their own `probe_success` on used modules. And we're looking for a way to detect some, as you said, systemic issue. The same how "sockets leak" could be monitored via `process_open_fds` or `process_resident_memory_bytes`. Just using `up` or synthetic targets and their `probe_success` won't help. 

So, is there other way to catch "per module problems"? Because I checked all available metrics from 0.16.0 and I can't find a way to catch upcoming problems early. For example in one datacenter our blackbox_exporter got locked out from using 25/tcp for no reason. In other case we had some strange random issues only with probes via IPv6. And it took some additional time to at least detect and confirm the problem.

I understand, that you don't want to add some strange rarely used features and end up with "bloated" code, which still will need some support and maintenance. But is it so different from `promhttp_metric_handler_requests_total` which also shows failures of processing incoming requests? It's just a "per-module-counter", that's all. At least as I can see it.

Would like to hear your thoughts in it, Brian. 
Thank you.

**Comment by brian-brazil** [comment]
There could be many many modules, which could be a cardinality issue. Existing alerting should already catch a module failing, as all the probes will fail too.

**Comment by n0guest** [comment]
> There could be many many modules, which could be a cardinality issue.

Ok, I see what you mean. But I really doubt, that someone in a sane state of mind would create few millions of modules and would hope for a miracle like "it should work just fine". If someone wants to shoot oneself in the foot, this person just can't be stopped by any measures. But it's just IMHO.

> Existing alerting should already catch a module failing, as all the probes will fail too.

Could you, please, clarify more on this? What exactly do you mean under "existing alerting"? Right now we have alerts on metrics related to availability, resources usage, etc. And we definitely would have many alerts like "target is unreachable" in case of something systematic. But in this scenario it's clearly visible only in "all checks are ok" or "all checks are failing" states (i.e. more like boolean - working/broken). 

What I'm trying to say, is to how to catch something like "more than N percent of checks on this module are failing"? And investigate and/or fix it before it became a problem? The closest analogy, that I can think of it's an "error budget" when handling traffic.

**Comment by SuperQ** [comment]
Something like `avg by (job) (probe_success) * 100 < 80` would alert on less than 80% of a blackbox job failing (so, one module)

**Comment by n0guest** [comment]
> Something like `avg by (job) (probe_success) * 100 < 80` would alert on less than 80% of a blackbox job failing (so, one module)

Thank you for example. 

But as I was saying, we have some Prometheis, which are using blackbox_exporters for probes and your solution will fit in for them. But we also have few instances of Prometheis aside, which are used like "meta-monitoring". And those meta-Prometheis aren't using blackbox_exporters for probes, they're just monitoring basic metrics of blackbox_exporters themselves. 

So, I'm looking for a solution to early detect problems at work of all monitored blackbox_exporters (based on metrics, collected by meta-Prometheis). The only way, that I see right now, is to manually add a probe for each module on those meta-Prometheis. But honestly, it looks like an overhead from my point of view. But there is even more - one day will end at "someone forgot to and another synthetic target just to monitor another declared module".

And again, I understand, that my case probably more or less rare. But as you said previously:

> ... but I could see how **this might be useful for monitoring the exporter overall.**

This exactly what I'm looking for right now.

**Comment by brian-brazil** [comment]
I remain confused as to what you're trying to do here. Either the problem is sufficient to trigger your existing alerting on probe failures, or it doesn't matter because it's not having an impact.

**Comment by n0guest** [comment]
> I remain confused as to what you're trying to do here. Either the problem is sufficient to trigger your existing alerting on probe failures, or it doesn't matter because it's not having an impact.

Sorry for that and thank you for your patience. I'll try one more time. Right now only Prometheus, which uses "probes" have information about "they're failing or not". But another Prometheus, which I previously named as "meta", only collects basic metrics from the same blackbox_exporter. And those metrics, collected by "meta", don't have enough information to write an alert rule "there is definitely something wrong with this module on this exporter, you should check it". 

Relatively speaking, the first Prometheus is managed by Team A. When the second Prometheus and blackbox_exporter are managed by Team S. So, in this scenario Team A, just a client of services, provided and supported by Team S (aka "Internal Support"). And as I wrote before, we're looking for a way to detect problems early without having a necessity in form of "adding synthetic probes for each declared module". And having metrics like `probes_failed_total{module="foo"}` collected the same way as `process_resident_memory_bytes` or `process_open_fds` we should be able to do it.

I hope this time I described it clear enough ;)

**Comment by brian-brazil** [comment]
That seems very niche, and is technically not a problem with the exporter as it's still working as intended. I'd suggest looking to setup something via probe_success/up.

**Comment by n0guest** [comment]
> That seems very niche

I thought so, but we hoped that `probes_failed_total` could be useful not only for us.

> I'd suggest looking to setup something via probe_success/up.

Ok, we'll try to "cook up" something. Thanks for your comments.
