### ISSUE TITLE
Allow running external program to get probe results

### ISSUE THREAD

**Issue by yuvipanda** [prometheus/blackbox_exporter#56]
blackbox_exporter would just start a configured process for a module, and return its output as the result of the probe. This would allow it to be very extensible, without needing to bloat the codebase.

It's also possible that this should be written as a separate exporter and not as a feature of blackbox_exporter, but it will be very useful either way.

**Comment by brian-brazil** [comment]
This would be better written as a separate exporter, or depending on what you're doing use the node exporter textfile collector.

The blackbox exporter is meant to handle "standard" probes, and to keep complexity manageable I want to avoid things like forking scripts or other complex logic.

**Comment by yuvipanda** [comment]
(We talked over this on IRC, and I concur)
