### ISSUE TITLE
If DNS returns an ipv6 address, blackbox assumes it should be used even if no ipv6 interface exists

### ISSUE THREAD

**Issue by jrdemasi** [prometheus/blackbox_exporter#567]
### Host operating system: output of `uname -a`
Linux 5.4.3-arch1-1 #1 SMP PREEMPT Fri, 13 Dec 2019 09:39:02 +0000 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.16.0 (branch: HEAD, revision: 991f89846ae10db22a3933356a7d196642fcb9a9)

### What is the blackbox.yml module config.
Default

### What logging output did you get from adding `&debug=true` to the probe URL?
Logs for the probe:
ts=2020-01-08T17:00:12.670766762Z caller=main.go:304 module=http_2xx target=https://google.com level=info msg="Beginning probe" probe=http timeout_seconds=119.5
ts=2020-01-08T17:00:12.670883647Z caller=http.go:318 module=http_2xx target=https://google.com level=info msg="Resolving target address" ip_protocol=ip6
ts=2020-01-08T17:00:12.671438925Z caller=http.go:318 module=http_2xx target=https://google.com level=info msg="Resolved target address" ip=2607:f8b0:400f:800::200e
ts=2020-01-08T17:00:12.671477336Z caller=client.go:250 module=http_2xx target=https://google.com level=info msg="Making HTTP request" url=https://[2607:f8b0:400f:800::200e] host=google.com
ts=2020-01-08T17:00:12.671554347Z caller=main.go:119 module=http_2xx target=https://google.com level=error msg="Error for HTTP request" err="Get https://[2607:f8b0:400f:800::200e]: dial tcp [2607:f8b0:400f:800::200e]:443: connect: network is unreachable"
ts=2020-01-08T17:00:12.671571635Z caller=main.go:119 module=http_2xx target=https://google.com level=info msg="Response timings for roundtrip" roundtrip=0 start=2020-01-08T10:00:12.671525014-07:00 dnsDone=2020-01-08T10:00:12.671525014-07:00 connectDone=2020-01-08T10:00:12.671542349-07:00 gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=0001-01-01T00:00:00Z
ts=2020-01-08T17:00:12.671589042Z caller=main.go:304 module=http_2xx target=https://google.com level=error msg="Probe failed" duration_seconds=0.000791284

### What did you do that produced an error?
Input a domain that has ipv6 available on a network with ipv6 resolvers, but on a machine with no ipv6 functionality

### What did you expect to see?
ipv4 should still be used

### What did you see instead?
ipv6 gets used even though it's unavailable locally

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
