### ISSUE TITLE
Allow post body into query parameter to override http module body

### ISSUE THREAD

**Issue by xujl1062** [prometheus/blackbox_exporter#568]
I have the same request，and added the following sections to the main.go(138) 
```
body := params.Get("body")
if body != "" {
    module.HTTP.Body = body
}
```
then, We can fetch post body from the prometheus sd_config by relabel func

_Originally posted by @xujl1062 in https://github.com/prometheus/blackbox_exporter/issues/380#issuecomment-572354476_

**Comment by brian-brazil** [comment]
By design only the module and target come from the the URL, everything else is in the module config. Otherwise we'd end up as an open proxy, and it'd be very complicated to manage.
