### ISSUE TITLE
Feature request: tls_config - Leaf certificate pinning

### ISSUE THREAD

**Issue by udhos** [prometheus/blackbox_exporter#570]
TLS probe should have an option to accept only specificied leaf certificates from the target.

**Comment by brian-brazil** [comment]
We only implement standard TLS stuff, as among other things this code is shared with Prometheus. If you want to test more niche aspects of TLS, I'd suggest writing your own exporter.

**Comment by udhos** [comment]
Please find this sketch for the type of certificate pinning I am looking:

https://gist.github.com/zmanian/6199b20707941ebaaf70

Do you think it is out of scope for blackbox_exporter?

**Comment by SuperQ** [comment]
@udhos What would need to be done for this is to add the fingerprint support to the [common upstream TLSConfig](https://github.com/prometheus/common/blob/629b6ff9b3aafafba54ab96663903fde9544f037/config/http_config.go#L327-L339) code.

**Comment by brian-brazil** [comment]
Yes, that's out of scope. If you need to test a non-standard HTTP client, then you should do a test with that code rather than a generic http testing like the blackbox exporter.

**Comment by brian-brazil** [comment]
This doesn't belong in the blackbox exporter, however the ssl_exporter may already allow for this.
