### ISSUE TITLE
Using custom DNS resolvers for http_probe probe

### ISSUE THREAD

**Issue by tdabasinskas** [prometheus/blackbox_exporter#577]
We have some cases where we need to resolve the IP address of the target being probed via `http_probe` using different DNS revolver then the ones being set on the host.

Would it be possible to support something like `dns_resolver` parameter for all probes (except `dns_probes`), which would allow specifying a custom IP of a DNS resolver, which would thenbe used to resolve the target name to IP?

If I understand correctly, it would basically mean passing custom dialer to the [`&net.Resolver{}` inititialization](https://github.com/prometheus/blackbox_exporter/blob/master/prober/utils.go#L59). I can do a PR if you think that's something that could be accepted.

**Comment by brian-brazil** [comment]
Having a non-unified DNS setup sounds a bit niche, this sounds more like a case for file_sd on the Prometheus end.

**Comment by tdabasinskas** [comment]
Thanks for the reply.

The use case we have is that we have services that are resolved internally to internal IP addresses and are resolved to external IP addresses from public revolvers - common practice called `split-brain DNS`.

We would like to have different modules, which would allow us to monitor the same endpoint both internally, as well as from the outside, which in turn would allow us to compare the latencies and monitor the differences in behavior.

Not sure how this could be achieved via file_sd. The only options we can think of if having multiple deployments (something we would like to avoid) of the exporter with different `resolv.conf` configuration or using IPs instead of DNS name (which would prefer not to do, as it reduces the things that we monitor).

**Comment by brian-brazil** [comment]
If you've different network/DNS setups, then running multiple exporters sounds like a sane approach to me.

> Not sure how this could be achieved via file_sd.

Do the resolution before the target is put in file_sd.

**Comment by tdabasinskas** [comment]
Got it, yet I'm not sure I follow the reasoning behind increasing infrastructure complexity and costs in favor of configuration improvements. If we are not using Docker, it would mean that we need a completely separate server just for this case, because the exporter can only use what's defined in `resolv.conf`.

Since it seems a quite simple change, which does not break any existing functionally (if no `dns_resolver` parameter is set, the behavior would not change), I'm not sure why we couldn't do it. It seems it's not that different to something like `preferred_ip_protocol`, which also kinda indicate the way we would try to reach the endpoint. In addition there's `probe_dns_lookup_time_seconds` metric for `http_probe`, so it kinda would be nice if we could use it to compare these latencies using different revolvers.

**Comment by brian-brazil** [comment]
The burden of those with complex setups should be on those with such setups, it's not sane to try to support every non-standard setup.

**Comment by davinkevin** [comment]
I have the exact same use-case and will deploy two containers/pods with different DNS configuration to solve that issue.
