### ISSUE TITLE
Add SSL labs probe

### ISSUE THREAD

**Issue by omerlh** [prometheus/blackbox_exporter#578]
Add an option to test a target using [SSL Labs](https://www.ssllabs.com/), that can detect a lot of TLS issues (for example, weak certificates). The probe should return the grade that SSL Labs provides.

**Comment by brian-brazil** [comment]
That sounds like more a case for a custom exporter.

**Comment by omerlh** [comment]
Someone was faster and already wrote it: https://github.com/anas-aso/ssllabs_exporter
