### ISSUE TITLE
[suggestion] Omitting metrics if not success

### ISSUE THREAD

**Issue by zerkms** [prometheus/blackbox_exporter#579]
At the moment if the http probe fails `probe_success=0` - the exporter still exports

```
probe_http_duration_seconds{phase="connect"} 0
probe_http_duration_seconds{phase="processing"} 0
probe_http_duration_seconds{phase="resolve"} 0
probe_http_duration_seconds{phase="tls"} 0
probe_http_duration_seconds{phase="transfer"} 0
```

Which is a lie - none of those phases completed in a blazing fast 0 seconds.

Why this is a problem: if you perform any analytics over those metrics (eg percentiles, or min) it would be skewed.

Suggestion: what if the exporter does not export metrics it could not really scrape instead of exporting zero values?

**Comment by brian-brazil** [comment]
That a probe failed doesn't mean that the HTTP request failed, the status code could have been wrong for example.

**Comment by zerkms** [comment]
@brian-brazil that's right, but imagine the following query:

`min_over_time(probe_http_duration_seconds{phase="connect"}[1h])` which semantically means: "the quickest tcp connect over period", practically it would return `0` though, which is wrong.

My core point here is - if a particular metric was not actually scraped (for whatever reason: be it a transport error, or http status code error, or any other error) - the complete metric must be removed from the response, not the zero value returned as it's now.

**Comment by brian-brazil** [comment]
The TCP connection time doesn't become invalid because a subsequent HTTP request failed, this isn't sane in general.

**Comment by zerkms** [comment]
@bbigras 

> The TCP connection time doesn't become invalid because a subsequent HTTP request failed, this isn't sane in general.

That's NOT what I said.

I probably am terrible at explaining, but I will try once again.

If **a particular metric** was not actually scraped **for whatever reason** - it **must not be** exported, at all, since `0` is a lie.

Returning to my initial example:

```
probe_http_duration_seconds{phase="connect"} 0
probe_http_duration_seconds{phase="processing"} 0
probe_http_duration_seconds{phase="resolve"} 0
probe_http_duration_seconds{phase="tls"} 0
probe_http_duration_seconds{phase="transfer"} 0
```

Here are the metrics exported for a target with not-existing DNS address. Do you think those zeroes make any sense?

**Comment by SuperQ** [comment]
@brian-brazil I think the point is that exposing TCP connection duration isn't valid if we fail early, for example at URL parsing or DNS lookup.

Currently we init all the label values far too early in the setup of the probe. This results in invalid (0) results for data when we haven't even reached the connect phase of the probe.

**Comment by houstonheat** [comment]
Hi, faced the same confusing situation:
https://groups.google.com/u/1/g/prometheus-users/c/NbyDxdk05K4

The metrics return the value 0, but phases, in principle, did not start processing at all (except dns lookup). It would be much clearer if the phases that did not actually occur for the query were not present in the results but I'm not sure how this compares to the best practices for writing exporters.
```
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.003334816
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 5.000336144
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length 0
# HELP probe_http_duration_seconds Duration of http request by phase, summed over all redirects
# TYPE probe_http_duration_seconds gauge
probe_http_duration_seconds{phase="connect"} 0
probe_http_duration_seconds{phase="processing"} 0
probe_http_duration_seconds{phase="resolve"} 0.003334816
probe_http_duration_seconds{phase="tls"} 0
probe_http_duration_seconds{phase="transfer"} 0
# HELP probe_http_ssl Indicates if SSL was used for the final redirect
# TYPE probe_http_ssl gauge
probe_http_ssl 0
...
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0
```

**Comment by IMAGNUMI** [comment]
How can i get metric probe_http_duration_seconds "time now" and " 24h previous"?

**Comment by zerkms** [comment]
@IMAGNUMI https://prometheus.io/docs/prometheus/latest/querying/basics/#offset-modifier
