### ISSUE TITLE
prometheus blackbox with basic auth config is returning 401 error code

### ISSUE THREAD

**Issue by isshwar** [prometheus/blackbox_exporter#583]
### Host operating system: output of `uname -a`
Darwin MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0:
running prometheus and  blackbox exporter as docker container on mac machine.

### blackbox_exporter version: output of `blackbox_exporter -version`

v0.16.0
docker pull prom/blackbox-exporter:v0.16.0

### What is the blackbox.yml module config.
modules:
  http_2basicauth_test:
    prober: http
    timeout: 15s
    http:
      preferred_ip_protocol: "ip4"
      method: POST
      headers:
        Host: "<host url >"
      basic_auth:
        username: "username"
        password: "password"

### What is the prometheus.yml scrape config.
- job_name: 'blackbox-http-feedback'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /probe 
    basic_auth:
      username: "username"
      password: "password"
    params:
      module: [http_2basicauth_test]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://example.com # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: host.docker.internal:9115  # The blackbox exporter's real hostname:port.

### What logging output did you get from adding `&debug=true` to the probe URL?
ts=2020-03-16T13:06:31.0024605Z caller=main.go:119 module=http_2basicauth_test target=https://example.com level=info msg="Received HTTP response" status_code=401
ts=2020-03-16T13:06:31.0025366Z caller=main.go:119 module=http_2basicauth_test target=https://example.com level=info msg="Invalid HTTP response status code, wanted 2xx" status_code=401
### What did you do that produced an error?
I am able to probe the endpoints that doesn't require basic auth, but there are few endpoints that are to basic auth'ed to scrape. but these endpoints are giving 401 error code.
### What did you expect to see?
successful probe.
### What did you see instead?
401 error code and probe unsuccessful

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
