### ISSUE TITLE
[Feature Request] Secure Path Parameters / Env Vars

### ISSUE THREAD

**Issue by chris-parker-za** [prometheus/blackbox_exporter#585]
I have a use case where I need to probe an HTTP endpoint, however, the URL contains a sensitive API key. I'd ideally not like to configure this in Prometheus. The blackbox exporter contains other secure bits of information such as Basic Auth usernames and password. Is there a possibility of adding functionality that can, via the config file, inject secrets into a placeholder into the target? 

Current situation:
```
target=some.securesite.com/supersecret_apikey=1asfdh2487d?foo=bar
```
Future situation : 
```
target=some.securesite.com/supersecret_apikey=%supersecretkey%?foo=bar
```
Taking this one step further, secrets of this nature can and do change. At a minimum, would some kind of environment variable reading logic be possible in the config? In a Kubernetes environment, configs are often loaded into a running container as KV environment variable pairs by tools such as Helm (my use case). This solves the security gap that a container or tool doesn't have API keys, username and passwords baked into yaml files.

**Comment by brian-brazil** [comment]
It's not generally secure to have secrets in URLs at all as e.g. they tend to be logged, and there's no plans for any munging of targets from Prometheus.
I can only suggest to look at more standard auth mechanisms such as basic auth, or use a non-valuable key that only has enough permissions for monitoring to work.

**Comment by chris-parker-za** [comment]
I agree with you, however, my team does not own these API's. They are API's for government services. Thanks for your feedback though, we'll make these changes in our own fork then 👍
