### ISSUE TITLE
Documentation missing: Howto set exporters port?

### ISSUE THREAD

**Issue by anthraxn8b** [prometheus/blackbox_exporter#588]
Hi! THX for the exporter!!!

You write "Blackbox exporter is configured [...] and command-line flags (such as [...] what port to listen on [...]" in your documentation.
I really tried hard but could not find information about howto set a different port the exporter is listening on... :-)

THX in advance!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by anthraxn8b** [comment]
Maybe - but it's still an issue if the documantion misses this information that is offered at another position in the documentation - or don't you aggree here?
If I would have found out the information by myself I would have created a pull request for a documentation change ;-)

**Comment by brian-brazil** [comment]
How to view the flags is documented, and this is the same as all the other Prometheus Go binaries.

**Comment by anthraxn8b** [comment]
This is possible - in most cases - I guess.
I automatically download and deploy a version not runnable on my local os.
So politely asking the command line for help leads to addionally downloading an executable suiteable for my os through my companies firewall where the download url first has to be whitelisted.
So I would appreciate a documentation in the readme ;-)
