### ISSUE TITLE
Probe failed with http/2 valid version

### ISSUE THREAD

**Issue by paracetamol32** [prometheus/blackbox_exporter#596]
Configuration: blackbox_exporter-0.16.0.windows-amd64
Config file with thie entry:
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/2"]

check url: http://localhost:9115/probe?target=https://http2.pro&module=http_2xx&debug=true

Result debug:

Logs for the probe:
ts=2020-04-11T11:23:52.9416524Z caller=main.go:304 module=http_2xx target=https://http2.pro level=info msg="Beginning probe" probe=http timeout_seconds=5
ts=2020-04-11T11:23:52.9416524Z caller=http.go:318 module=http_2xx target=https://http2.pro level=info msg="Resolving target address" ip_protocol=ip6
ts=2020-04-11T11:23:52.9426513Z caller=http.go:318 module=http_2xx target=https://http2.pro level=info msg="Resolved target address" ip=8.9.5.7
ts=2020-04-11T11:23:52.9426513Z caller=client.go:250 module=http_2xx target=https://http2.pro level=info msg="Making HTTP request" url=https://8.9.5.7 host=http2.pro
ts=2020-04-11T11:23:53.239651Z caller=main.go:119 module=http_2xx target=https://http2.pro level=info msg="Received HTTP response" status_code=200
ts=2020-04-11T11:23:53.240652Z caller=main.go:119 module=http_2xx target=https://http2.pro level=error msg="Invalid HTTP version number" version=1.1
ts=2020-04-11T11:23:53.240652Z caller=main.go:119 module=http_2xx target=https://http2.pro level=info msg="Response timings for roundtrip" roundtrip=0 start=2020-04-11T13:23:52.9426513+02:00 dnsDone=2020-04-11T13:23:52.9426513+02:00 connectDone=2020-04-11T13:23:53.0386606+02:00 gotConn=2020-04-11T13:23:53.1406515+02:00 responseStart=2020-04-11T13:23:53.239651+02:00 end=2020-04-11T13:23:53.240652+02:00
ts=2020-04-11T11:23:53.240652Z caller=main.go:304 module=http_2xx target=https://http2.pro level=error msg="Probe failed" duration_seconds=0.2989996

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
