### ISSUE TITLE
Feature request: hide /config endpoint

### ISSUE THREAD

**Issue by jimsheldon** [prometheus/blackbox_exporter#599]
Hello!  

Currently, any source that can send traffic to blackbox can also retrieve `/config`.

Since the blackbox config can contain potentially sensitive tokens/passwords, it would be nice to be able to hide or disable the `/config` endpoint.

Thanks!

**Comment by brian-brazil** [comment]
The config endpoint should not contain any secrets, if it does that would either be a bug on our part or a configuration error on yours. Hiding useful debugging information from one place would also not remove it from others, such as the debug mode of probes and logs.

**Comment by jimsheldon** [comment]
Thanks for the response.

I would love to be wrong here, but the `/config` endpoint just displays the configuration yaml, which can contain bearer tokens, API tokens, passwords, etc.

If there is a way to keep that sort of thing out of the config, I would love to know!

**Comment by brian-brazil** [comment]
All secrets as are hidden on that and other endpoints, see https://prometheus.io/docs/operating/security/#secrets

**Comment by jimsheldon** [comment]
Somehow we missed that there is a separate `bearer_token` variable, we had been setting the headers manually which still appear in the config.  We will move to using `bearer_token`.

Sorry for not reading the documentation properly, thanks for the help!
