### ISSUE TITLE
detect revoked ssl certs

### ISSUE THREAD

**Issue by scottweston** [prometheus/blackbox_exporter#6]
```
$ curl 'http://127.0.0.1:9115/probe?target=https://revoked.grc.com/&module=http_2xx'
probe_ssl_earliest_cert_expiry 1492961872.000000
probe_http_status_code 200
probe_http_content_length -1
probe_http_redirects 0
probe_http_ssl 1
probe_duration_seconds 0.246233
probe_success 1
```

**Comment by brian-brazil** [comment]
I think this would be something better done by a dedicated exporter, as it's not directly related to blackbox probing of a service itself.

**Comment by JDA88** [comment]
I agree this would be very usefull and logical to have in the `tls_config` section.

Can someone re-open this issue?

**Comment by autokilla47** [comment]
+1
it would be very useful to have such a check!
