### ISSUE TITLE
icmp prober measurement includes DNS lookup time

### ISSUE THREAD

**Issue by stapelberg** [prometheus/blackbox_exporter#60]
See https://groups.google.com/forum/#!topic/prometheus-developers/XrTeEkb1WAU for context.

**Comment by SuperQ** [comment]
I think this may be an issue for all probes.

**Comment by RichiH** [comment]
JFTR, I think it makes sense to keep track of DNS resolve timing; this is a useful metric. Not sure if this should be its own job distinct from all the others. This duplicates effort, but keeps timeseries count from growing in an arguably useless manner.

As long as we're contemplating changes, the behaviour that any response time for icmp_probe which is higher than the timeout is an implicit failure makes analyzing things icky, forces one to use error-prone (for some users) extra query strings, and breaks down completely when timeouts are changed over time.

No idea about guarantees within the exporters, but changing too much might make a new module worthwhile so as to not break old configs.

**Comment by SuperQ** [comment]
Recording `prober_dns_lookup_time_seconds` any time we use `net.ResolveIPAddr()` seems like the right thing to do.

**Comment by aparcar** [comment]
I try to measure ping time to distant antennas, so ping time should be as representative as possible.
Is there an easy way to cache the dns in blackbox_exporter or subtract `prober_dns_lookup_time_seconds`

**Comment by SuperQ** [comment]
@aparcar Once we have the metric, it will be as simple as subtracting the the two metrics.
