### ISSUE TITLE
x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by mira20** [prometheus/blackbox_exporter#600]
Hello, i try to configure blackbox with Prometheus for the monitoring of HTTP, HTTPS application, but when i try curl, i get "probe_success 0 " : 

# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.000597015
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.012103193
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length 0
# HELP probe_http_duration_seconds Duration of http request by phase, summed over all redirects
# TYPE probe_http_duration_seconds gauge
probe_http_duration_seconds{phase="connect"} 0
probe_http_duration_seconds{phase="processing"} 0
probe_http_duration_seconds{phase="resolve"} 0.000597015
probe_http_duration_seconds{phase="tls"} 0
probe_http_duration_seconds{phase="transfer"} 0
# HELP probe_http_redirects The number of redirects
# TYPE probe_http_redirects gauge
probe_http_redirects 0
# HELP probe_http_ssl Indicates if SSL was used for the final redirect
# TYPE probe_http_ssl gauge
probe_http_ssl 0
# HELP probe_http_status_code Response HTTP status code
# TYPE probe_http_status_code gauge
probe_http_status_code 0
# HELP probe_http_version Returns the version of HTTP of the probe response
# TYPE probe_http_version gauge
probe_http_version 0
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0 

my Blackbox.yml configuration : 
modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.0", "HTTP/1.1", "HTTP/2"]
      valid_status_codes: [] 
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false  

with curl debug : 

Logs for the probe:
ts=2020-04-16T10:04:01.453471937Z caller=main.go:118 module=http_2xx target=https://applicationName:port/ level=info msg="Beginning probe" probe=http timeout_seconds=9.5
ts=2020-04-16T10:04:01.453565009Z caller=utils.go:42 module=http_2xx target=https://applicationName:port/ level=info msg="Resolving target address" ip_protocol=ip4
ts=2020-04-16T10:04:01.454092043Z caller=utils.go:75 module=http_2xx target=https://applicationName:port/ level=info msg="Resolved target address" ip=ipaddress
ts=2020-04-16T10:04:01.454125263Z caller=http.go:349 module=http_2xx target=https://applicationName:port/ level=info msg="Making HTTP request" url=https://ipaddress:port/ host=applicationName:port/
ts=2020-04-16T10:04:01.464877041Z caller=http.go:364 module=http_2xx target=https://applicationName:port/ level=error msg="Error for HTTP request" err="Get https://ipaddress:port/: x509: certificate signed by unknown authority"
ts=2020-04-16T10:04:01.464904152Z caller=http.go:450 module=http_2xx target=https://applicationName:port/ level=info msg="Response timings for roundtrip" roundtrip=0 start=2020-04-16T10:04:01.454178431Z dnsDone=2020-04-16T10:04:01.454178431Z connectDone=2020-04-16T10:04:01.454534045Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=0001-01-01T00:00:00Z
ts=2020-04-16T10:04:01.464924149Z caller=main.go:131 module=http_2xx target=https://applicationName:port/ level=error msg="Probe failed" duration_seconds=0.0114166

what i am missing ?
Thanks

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by 0xVox** [comment]
Respectfully disagree when this is the top result for anyone googling similar issues, and your link is broken.

**Comment by brian-brazil** [comment]
The link works, and this is not the place to request support.

**Comment by SuperQ** [comment]
If you're having trouble with the link, try https://prometheus.io/community/
