### ISSUE TITLE
example of the metrics that are returned

### ISSUE THREAD

**Issue by ghostsquad** [prometheus/blackbox_exporter#601]
Could an example of the metrics that are returned be provided somewhere? maybe also link in the README?

**Comment by matclab** [comment]
Also see #166 and PR #663.

**Comment by ghostsquad** [comment]
ah.. from #166 the very tired argument of "we don't need docs, just read the code". Documentation is like sex. Even bad documentation is better than nothing.

**Comment by reegnz** [comment]
Examples, documentation, tutorials... The argument is always 'Just read the code dummy, why isn't that enough? Duplication BAD! DRY GOOD!'.

**Comment by ghostsquad** [comment]
Made an argument to reopen the PR and continue the path of providing metrics documentation here https://github.com/prometheus/blackbox_exporter/pull/663?ts=4#issuecomment-658853584

**Comment by electron0zero** [comment]
closing this in favour of https://github.com/prometheus/blackbox_exporter/issues/856, please comment in https://github.com/prometheus/blackbox_exporter/issues/856 if you would like to discuss this issue.
