### ISSUE TITLE
Blackbox exporter slows k8s network

### ISSUE THREAD

**Issue by samson-arita** [prometheus/blackbox_exporter#604]
### Host operating system: output of `uname -a`
K8s
### blackbox_exporter version: output of `blackbox_exporter -version`

helm install 
### What is the blackbox.yml module config.
helm charts for blackbox-exporter
### What is the prometheus.yml scrape config.
I have listed numerous IPs and endpoints targets (hundreds) on the scrape config
    - job_name: blackbox-http_2xx
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - https://www.example.com/
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc:9115

### What logging output did you get from adding `&debug=true` to the probe URL?
No error
### What did you do that produced an error?
No error was produced
### What did you expect to see?
I expected the network to work normally

### What did you see instead?
The network slowed significantly to the extent I couldn't connect to the remote endpoints being monitored in the first place

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
