### ISSUE TITLE
log time

### ISSUE THREAD

**Issue by kellysan** [prometheus/blackbox_exporter#606]
### Host operating system: output of `uname -a`
Darwin TonySan.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

### blackbox_exporter version: output of `blackbox_exporter -version`

1.6

### What did you expect to see?
 This program is very unfriendly to non-time zone users, print out logs are UTC time, this can be based on the system time zone to choose the time to print logs
### What did you see instead?
I want to see that the log output format can be output according to system time

**Comment by brian-brazil** [comment]
Prometheus in general uses UTC everywhere to avoid timezone confusion and complexity, there's no plans to change this.
