### ISSUE TITLE
[PR][blackbox_exporter] params

### ISSUE THREAD

**Issue by fchiorascu** [prometheus/blackbox_exporter#608]
Manual action:
curl -i -X PUT "https://xxxxx" -L -T "test.txt" -k -u user

How I can integrate into prometheus.yml the URL and test.txt like for curl.
There is no possibility to have single URL = a) + b) if this was possible 
a). url="https://xxxxx" 
b). test.txt

### What did you expect to see?
params:
something to add external actions/files besides URL.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by fchiorascu** [comment]
@brian-brazil I understand this and thank you. But there was a feature request action from my side if you can take into consideration. :)

**Comment by brian-brazil** [comment]
The post does not contain a coherent feature request that I can see, only use of existing features.

**Comment by fchiorascu** [comment]
The feature will be to add for blackbox_exporter modules a section where we can have additional arguments outside URL or inside prometheus.yml targets. 

Not all the URL used as target cand contain the user/password/actions inside, some of the cases need to have as an external argument of the URL.

IF this details are not clear or pertinent then kindly close this issue.

**Comment by brian-brazil** [comment]
Any configuration beyond the target URL needs to come from the module configuration, and there's no plans to change that.
