### ISSUE TITLE
Make the gauge help text configurable

### ISSUE THREAD

**Issue by kaiyou** [prometheus/blackbox_exporter#612]
I am trying to design a largely generic monitoring system based on Prometheus, Grafana and Alertmanager. The core idea would be that every exporter has to export a standard `probe_status` gauge reporting the check status, labelled with a service identifier.

Then, generic multi-value grafana widgets and alertmanager rules can be used to check for overall status and group information by service. To improve this a bit further, I am thinking of using the Prometheus help text (instead of indexed labels) to propagate information about the meaning of the monitoring check (i.e. a full text sentence explaining what is being checked) and display a list of currently failing checks.

Prometheus fully support using custom help texts of course. Grafana has an open issue about making them available to widgets: https://github.com/grafana/grafana/issues/21749

**Comment by brian-brazil** [comment]
I'm confused by this request. Help text describes what a metric means for direct consumption by a human, and as it describes code it's not something that should vary let alone be configurable.

I think you're looking to build a check-based monitoring system, which Prometheus is not. I'd suggest asking usage questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).
