### ISSUE TITLE
probe_http_version returns 1.1 and NOT 2

### ISSUE THREAD

**Issue by mubeennakade** [prometheus/blackbox_exporter#617]
### Host operating system: output of `uname -a`

Linux 4.19.3-300.fc29.x86_64 #1 SMP Wed Nov 21 15:27:25 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.16.0 (branch: HEAD, revision: 991f89846ae10db22a3933356a7d196642fcb9a9)
  build user:       root@64f600555645
  build date:       20191111-16:27:24
  go version:       go1.13.4

### What is the blackbox.yml module config.

modules:
  http_2xx:
    prober: http
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp

### What is the prometheus.yml scrape config.

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://example.com    # Target to probe with http.
      relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.

### What did you expect to see?

probe_http_version{instance="https://example.com",job="blackbox"}   2

### What did you see instead?

probe_http_version{instance="https://example.com",job="blackbox"}   1.1

PS: Can you please add feature to get http version a 2 ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by SuperQ** [comment]
This seems like an issue to me. The blackbox_exporter doesn't currently support HTTP/2.

**Comment by brian-brazil** [comment]
There's insufficient information in the report to indicate a bug, we don't know that the relevant server even supports HTTP/2.

**Comment by SuperQ** [comment]
I tested a simple default blackbox config against `https://www.google.com`.

Curl works:
````
$ curl -s --http2 -o /dev/null https://www.google.com -D -
HTTP/2 200 
date: Mon, 11 May 2020 09:55:58 GMT
...
```

blackbox_exporter doesn't:
```
$ curl -s 'http://localhost:9115/probe?target=www.google.com&module=http_2xx' | grep probe_http_version
# HELP probe_http_version Returns the version of HTTP of the probe response
```
# TYPE probe_http_version gauge
probe_http_version 1.1
```

**Comment by mjtrangoni** [comment]
@brian-brazil @SuperQ first of all, thanks for this exporter! 
I have a webserver who advertise, `ALPN/HTTP2 h2, http/1.1 (offered)`, but only http/1.1 works. Is there any possibility of allowing a downgrade somehow the version, or is it outside of the scope of this project?
See,
```bash
$ curl -vvv  https://XXX
[...]
* ALPN, offering h2
* ALPN, offering http/1.1
[...]
* HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 13)
* Downgrades to HTTP/1.1!
[...]
* Connection #1 to host XXX left intact
```

On the exporter side I am getting this error,
```bash
target=XXX level=debug msg="Error for HTTP request" err="Get \"XXX\": stream error: stream ID 1; HTTP_1_1_REQUIRED"
```
I was digging a little bit in the code, and there is no way of forcing a HTTP version or enable the version downgrade on `prometheus/common` library.

**Comment by brian-brazil** [comment]
That sounds out of scope, this isn't something a user should be configuring in Prometheus and friends.
