### ISSUE TITLE
field fail_if_not_matches_regexp not found in type config.plain

### ISSUE THREAD

**Issue by bljusruk** [prometheus/blackbox_exporter#620]
### Host operating system: output of `uname -a`
It's golang:1.14-alpine. It's alpine version of the Go base image. Alpine is a tiny Linux distribution designed specifically for docker containers.

### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.16.0 (branch: master, revision: 36b75845788c22cd33511f5c61a6ea6df4cc8f16)
  build user:       mirov@localhost.localdomain
  build date:       20200513-07:27:43
  go version:       go1.13.3
### What is the blackbox.yml module config.
![blackbox](https://user-images.githubusercontent.com/52827396/81785691-dedf4680-94fe-11ea-93a3-8dfb2a8643a6.png)

### What did you do that produced an error?
I built blackbox_exporter in Docker image. For the build I cloned the latest version of blackbox_exporter repository to the alpine linux within the docker image. The build was successful, but when I start blackbox_exporter from the image (docker run -it -p 9115 bbex:latest) I got the following error:

level=info ts=2020-05-12T14:05:44.396Z caller=main.go:212 msg="Starting blackbox_exporter" version="(version=0.16.0, branch=master, revision=36b75845788c22cd33511f5c61a6ea6df4cc8f16)"
level=info ts=2020-05-12T14:05:44.396Z caller=main.go:213 msg="Build context" (gogo1.14.2,userroot@1855291a76a9,date20200512-13:59:26)=(MISSING)
level=error ts=2020-05-12T14:05:44.397Z caller=main.go:216 msg="Error loading config" err="error parsing config file: yaml: unmarshal errors:\n line 24: field fail_if_not_matches_regexp not found in type config.plain"

For my built version of blackbox_exporter i used the following configuration:

![config](https://user-images.githubusercontent.com/52827396/81785178-447f0300-94fe-11ea-866a-c561ac6d3275.png)

This configuration I used before with an old version of blackbox_exporter (blackbox_exporter-0.12.0) which I downloaded from https://prometheus.io/download/ site.

Now when I build blackbox_exporter from the latest version of the code I have the error above. Should I replace the configuration with the one currently available in blackbox.yml file?

### What did you expect to see?
I expected to see blackbox_exporter started with no errors.
### What did you see instead?
I saw the error about missing field in config.plain:

level=info ts=2020-05-12T14:05:44.396Z caller=main.go:212 msg="Starting blackbox_exporter" version="(version=0.16.0, branch=master, revision=36b75845788c22cd33511f5c61a6ea6df4cc8f16)"
level=info ts=2020-05-12T14:05:44.396Z caller=main.go:213 msg="Build context" (gogo1.14.2,userroot@1855291a76a9,date20200512-13:59:26)=(MISSING)
level=error ts=2020-05-12T14:05:44.397Z caller=main.go:216 msg="Error loading config" err="error parsing config file: yaml: unmarshal errors:\n line 24: field fail_if_not_matches_regexp not found in type config.plain"

**Comment by bljusruk** [comment]
Hm, now I see that the HTTPProbe struct does not have FailIfNotMatchesRegexp member. Currently it's only in DNSRRValidator struct. I think I'll ust remove the field fail_if_not_matches_regexp from my configuration.

**Comment by brian-brazil** [comment]
I'd suggest checking the docs: https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md

**Comment by bljusruk** [comment]
@brian-brazil Thanks, Brian. Found it in the file you recommended. Please close this.
