### ISSUE TITLE
probe_http_version returns 1.1/context deadline exceeded

### ISSUE THREAD

**Issue by dmytroshokha** [prometheus/blackbox_exporter#623]
### Host operating system: output of `uname -a`
Linux docker-01 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
### blackbox_exporter version: output of `blackbox_exporter -version`
master

### What is the blackbox.yml module config.
modules:
  http_2xx:
    prober: http
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
### What is the prometheus.yml scrape config.
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: jenkins-server
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /prometheus
  scheme: http
  static_configs:
  - targets:
    - XX.XXX.XX.X:8080
- job_name: jenkins-win-build-agents
  honor_timestamps: true
  scrape_interval: 6s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - XX.XX.XX.X:9182
- job_name: jenkins-mac-build-agents
  honor_timestamps: true
  scrape_interval: 6s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - XXX.XXX.XXX.XX:9100
- job_name: jenkins-linux-build-agents
  honor_timestamps: true
  scrape_interval: 6s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - XX.XX.XX.X:9100
- job_name: snmp-full
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - XXX.XX.XX.XX:9436
- job_name: snmp
  honor_timestamps: true
  params:
    module:
    - if_mib
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /snmp
  scheme: http
  static_configs:
  - targets:
    - XX.XX.X.X
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: XXX.XX.XX.X:9116
    action: replace
- job_name: blackbox
  honor_timestamps: true
  params:
    module:
    - http_2xx
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  static_configs:
  - targets:
    - example.com
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: XXX.XX.XX.X:9115
    action: replace
### What logging output did you get from adding `&debug=true` to the probe URL?
Logs for the probe:
ts=2020-05-14T20:12:44.547023569Z caller=main.go:304 module=http_2xx target=prometheus.io level=info msg="Beginning probe" probe=http timeout_seconds=119.5
ts=2020-05-14T20:12:44.547240894Z caller=http.go:318 module=http_2xx target=prometheus.io level=info msg="Resolving target address" ip_protocol=ip6
ts=2020-05-14T20:12:44.555887158Z caller=http.go:318 module=http_2xx target=prometheus.io level=info msg="Resolved target address" ip=2606:4700:3031::6818:783c
ts=2020-05-14T20:12:44.555997751Z caller=client.go:252 module=http_2xx target=prometheus.io level=info msg="Making HTTP request" url=http://[2606:4700:3031::6818:783c] host=prometheus.io
ts=2020-05-14T20:12:44.5563389Z caller=main.go:119 module=http_2xx target=prometheus.io level=error msg="Error for HTTP request" err="Get \"http://[2606:4700:3031::6818:783c]\": dial tcp [2606:4700:3031::6818:783c]:80: connect: cannot assign requested address"
ts=2020-05-14T20:12:44.556395643Z caller=main.go:119 module=http_2xx target=prometheus.io level=info msg="Response timings for roundtrip" roundtrip=0 start=2020-05-14T20:12:44.55617559Z dnsDone=2020-05-14T20:12:44.55617559Z connectDone=2020-05-14T20:12:44.55628457Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=0001-01-01T00:00:00Z
ts=2020-05-14T20:12:44.556443869Z caller=main.go:304 module=http_2xx target=prometheus.io level=error msg="Probe failed" duration_seconds=0.009345647
### What did you expect to see?
probe_http_version 2
### What did you see instead?
host down
context deadline exceeded
probe_http_version 1.1

curl -s --http2 -o /dev/null https://www.google.com -D -
HTTP/2 200
date: Thu, 14 May 2020 20:52:57 GMT
It seems like the blackbox doesn't support HTTP/2 and it can be the same issue like #617.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
