### ISSUE TITLE
ICMP probes fail when running multiple blackbox_exporters behind NAT

### ISSUE THREAD

**Issue by hcbraun** [prometheus/blackbox_exporter#632]
### Host operating system: output of `uname -a`
`Linux 5.6.15-arch1-1 #1 SMP PREEMPT x86_64 GNU/Linux`

### blackbox_exporter version: output of `blackbox_exporter -version`
`blackbox_exporter, version 0.16.0 (branch: HEAD, revision: 991f89846ae10db22a3933356a7d196642fcb9a9)`

### What is the prometheus.yml scrape config.
Running docker image "prom/blackbox-exporter:v0.16.0" without modification

### What logging output did you get from adding `&debug=true` to the probe URL?
x

### What did you do that produced an error?
Stopped and started the container. Then send a test request.
![2020-06-03T093302](https://user-images.githubusercontent.com/1728041/83609723-2ee58200-a56e-11ea-95c2-d4dbde84319c.png)

Also tried this on 3 different machines with getting the same seq and id on all of them.

### What did you expect to see?
On startup random id and seq initialization for ICMP request

### What did you see instead?
Id and seq always start with:
ICMP echo request, id 33313, seq 39440, length 36

Like described in [https://github.com/prometheus/blackbox_exporter/issues/411](https://github.com/prometheus/blackbox_exporter/issues/411), this breaks requests behind NAT

**Comment by brian-brazil** [comment]
Hmm, looks like something is off with RNG seeding.
