### ISSUE TITLE
Feature Request: Report all expiration dates for all certificates returned from the server

### ISSUE THREAD

**Issue by opensourcebear** [prometheus/blackbox_exporter#634]
To help with confusion around expiring certificates, reporting on all certificates could help people understand which certificate is expiring soon.  Adding a distinct identifier like the Common Name of the certificate as a label could allow users to monitor certificates independently.

If users want a single data point they should be able to continue using `probe_ssl_earliest_cert_expiry`

**Comment by brian-brazil** [comment]
If you want that level of detail then I'd suggest the ssl_exporter, but I suspect what you're actually looking for is #340.
