### ISSUE TITLE
Blackbox exporter showing "Context deadline exceeded" error

### ISSUE THREAD

**Issue by girishnehte** [prometheus/blackbox_exporter#650]
Hi,

First of all I am very new to blackbox and prometheus. I am using a setup with blackbox and prometheus to probe my servers. For all the on premise servers I was getting the correct resposnes. But now I have one of my server in the aws cloud. And for that the probe http_2xx probe returns "Contextr deadline exceeded" error. Just to narrow down the root cause, I setup only blackbox exporter (without prometheus) on one of my test machine and probe my vm in aws through the url "**_http://{test machine}:9115/probe?target={url of the server in aws cloud}&module=http_2xx_**" 
In the logs I can see the below error.
**_caller=main.go:119 module=http_2xx target={server in aws} level=error msg="Error for HTTP request" err="Get \"https://{server in aws}\": context deadline exceeded"_**
Is this some known issue? which is to be fixed?

Regards,
Girish

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by girishnehte** [comment]
Hi Brian,

As I specifically mentioned, this is nothing related to prometheus. This looks like an issue with the Blackduck. Isn't it? Or do I still need to put this in prometheus mailing list as you have suggested?

Regards,
Girish
