### ISSUE TITLE
Full page download

### ISSUE THREAD

**Issue by hryamzik** [prometheus/blackbox_exporter#657]
Feature request: full page download, with all the dependencies.

It's sometimes important to be aware of issues with loading page resources, and that's complicated to monitor there resources directly, especially when addresses change on every app build. Downloading the full page seem to be the best way to solve this.

**Comment by brian-brazil** [comment]
That's out of scope for the blackbox exporter which does just simple HTTP, and does not try to be an entire web browser. I'd suggest looking at the webdriver exporter.

**Comment by hryamzik** [comment]
Thanks for pointing to this exporter but it seem to be an overkill as it uses chromedriver.

I'd expect blackbox_exporter to be able to get page like wget does, and wget doesn't depend on web drivers.

**Comment by brian-brazil** [comment]
A HTML parser is out of the scope for the blackbox exporter. It's a HTTP probe, not a web page regression test probe.

**Comment by hryamzik** [comment]
OK, I'll close this for now and either write a custom exporter or tune chrome based one. Ty.
