### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by kaihendry** [prometheus/blackbox_exporter#66]
When pulling the Docker image, how do I get an ARM version for my Raspberry PI?

`standard_init_linux.go:175: exec user process caused "exec format error"`

**Comment by juliusv** [comment]
AFAIK our Docker images are linux-amd64 only for now and Docker doesn't have any multi-arch support within one image. What people usually do is offer separate Docker images for different platforms under a different name that includes the platform / arch. We don't have that yet...

**Comment by so0k** [comment]
@kaihendry - look at Hypriot images - they've been doing a lot of great work for Docker on ARM - http://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/

**Comment by brian-brazil** [comment]
This is more a general build infrastructure request, once promu and friends support this we'll get it automatically.

**Comment by carlosflorencio** [comment]
Any updates on this? I guess we're able to have arm compatibility by now.
