### ISSUE TITLE
Feature request: gRPC support

### ISSUE THREAD

**Issue by juan-martinez-hernandez** [prometheus/blackbox_exporter#665]
Hi there,

Do you guys have plans to add support to perform probe checks to gRPC services? 

I've searched for solutions with Blackbox exporter to achieve this but no success.

**Comment by brian-brazil** [comment]
That's not planned, the blackbox exporter scope is more basic protocols like plain HTTP. I'd suggest writing your own exporter if you need this, I'm not aware of one currently existing.

**Comment by andbuitra** [comment]
Couldn't you just query it via HTTP? gRPC basically uses HTTP/2 for communication. I'm totally talking out ignorance, tho, haven't dealt with that technology too much.

**Comment by kmcminn** [comment]
grpc is primarily used for backends, this tool seems designed to probe frontends. You probably dont want to be calling your backend endpoints/rpcs with your monitoring system but instead emitting stats from within them (statsd or similar) and exposing a health endpoint for things like a deploy system or k8s liveness/readyness

**Comment by kotyara85** [comment]
@brian-brazil I can send a PR with grpc support

**Comment by brian-brazil** [comment]
That's for the offer, but I'm not willing to expand the scope of this exporter to cover that. I'd suggest starting a new exporter so that it can handle all the various gRPC use cases as they come up, which can then also be listed on the prometheus website.
