### ISSUE TITLE
Feature Request: Load config via environment variable

### ISSUE THREAD

**Issue by yegle** [prometheus/blackbox_exporter#667]
The recommended way to use blackbox_exporter's docker container is to mount the config file into the container and start the container with the mounted config.

If you are using docker-compose, each time you modify the config, you'll have to explicitly restart the docker container (as oppose to, if you can specify the config as an environment variable, you can modify the config embedded in docker-compose.yaml, and do `docker-compose up -d` to automatically restart the right container).

I think it might be better to e.g. load the config from environment variable as a base64 encoded string, instead of putting the content of the config in an environment variable as-is.

**Comment by brian-brazil** [comment]
Thank you for your suggestion. Per general Prometheus policy we only accept a particular configuration from one place, and that is a file here. In addition unlike files which we can reload at runtime, environment variables require a restart to change.

If you need this I'd suggest a bit of glue to take the envvar and write it to a file before the exporter starts.
