### ISSUE TITLE
Support HUP signal configuration reloading

### ISSUE THREAD

**Issue by SuperQ** [prometheus/blackbox_exporter#67]
It would be nice to support configuration reload via SIGHUP.

**Comment by 1stdemon** [comment]
Is where any way without restart to reload config ?

**Comment by fuhbar** [comment]
@1stdemon nope, at least what I could make sense of it. No sign for neither a signal handler nor a http route to some kind of a reload handler in the code.

**Comment by Colstuwjx** [comment]
@SuperQ  I have already implemented as #136 :)
