### ISSUE TITLE
Probing doesn't work.

### ISSUE THREAD

**Issue by manodupont** [prometheus/blackbox_exporter#675]
I can't probe. Proble status is always FAILED. I tried changing to ipv4. Still the samething

Logs for the probe:
ts=2020-08-13T08:16:41.406872052Z caller=main.go:304 module=http_2xx target=prometheus.io level=info msg="Beginning probe" probe=http timeout_seconds=119.5
ts=2020-08-13T08:16:41.407004268Z caller=http.go:323 module=http_2xx target=prometheus.io level=info msg="Resolving target address" ip_protocol=ip4
ts=2020-08-13T08:16:41.412340318Z caller=http.go:323 module=http_2xx target=prometheus.io level=info msg="Resolved target address" ip=172.67.141.23
ts=2020-08-13T08:16:41.412414104Z caller=client.go:252 module=http_2xx target=prometheus.io level=info msg="Making HTTP request" url=http://172.67.141.23 host=prometheus.io
ts=2020-08-13T08:18:40.907034378Z caller=main.go:119 module=http_2xx target=prometheus.io level=error msg="Error for HTTP request" err="Get \"http://172.67.141.23\": context deadline exceeded"
ts=2020-08-13T08:18:40.907093042Z caller=main.go:119 module=http_2xx target=prometheus.io level=info msg="Response timings for roundtrip" roundtrip=0 start=2020-08-13T08:16:41.412492615Z dnsDone=2020-08-13T08:16:41.412492615Z connectDone=0001-01-01T00:00:00Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=0001-01-01T00:00:00Z
ts=2020-08-13T08:18:40.907122359Z caller=main.go:304 module=http_2xx target=prometheus.io level=error msg="Probe failed" duration_seconds=119.500197481

My blackbox.yml config as it appears from the UI at http://xxx:9115/config

modules:
    http_2xx:
        prober: http
        http:
            preferred_ip_protocol: ipv4
            ip_protocol_fallback: true
        tcp:
            ip_protocol_fallback: true
        icmp:
            ip_protocol_fallback: true
        dns:
            ip_protocol_fallback: true
    http_post_2xx:
        prober: http
        http:
            preferred_ip_protocol: ipv4
            ip_protocol_fallback: true
            method: POST
        tcp:
            ip_protocol_fallback: true
        icmp:
            ip_protocol_fallback: true
        dns:
            ip_protocol_fallback: true
Prob

Docker image: prom/blackbox-exporter

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
