### ISSUE TITLE
 request canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by tj13** [prometheus/blackbox_exporter#68]
when using http probe module, got some warning message as below randomly. and the value of probe_duration_seconds is much higher but no failure. 
`time="2016-09-27T09:08:42Z" level=warning msg="Error for HTTP request to http://xxx/proplus/home: Get http://xxxx/proplus/home: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" source="http.go:97"`
how to trouble shoot this? any clue is welcome.

**Comment by brian-brazil** [comment]
The request timed out, the other end is likely overloaded.
