### ISSUE TITLE
Feature Request: batch scraping

### ISSUE THREAD

**Issue by hesamwls** [prometheus/blackbox_exporter#683]
As I understand, currently blackbox exporter receives and processes one endpoint at a time which is not too efficient when you have thousands of endpoints to monitor.
Is there any design decision behind this? and is there any plan to support batch processing?

**Comment by SuperQ** [comment]
The design idea is that Prometheus is your source of truth for what is being monitored. Prometheus itself is extremely efficient at managing and scheduling scrapes, thousands of targets defined in the Prometheus service discovery is no big deal.

On the exporter side, batching provides almost no advantage, as it's a multi-threaded Go process.

The design, as is, is very efficient and parallelized.

**Comment by brian-brazil** [comment]
As Ben says there's no need for this, and in addition the communication between Prometheus and the Blackbox exporter should be using persistent HTTP connections so it's about as efficient as it can be. The last time numbers were run it came out to around 1k probes per core per second which is quite sufficient.

**Comment by hesamwls** [comment]
Hey guys, thanks for your fast response. I don't think the difference is negligible since there are network calls involved and prometheus and exporter might not be running close to each other.
The other argument is that exporter is supposed to work with any other monitoring server (right?) and relying on prometheus performance is not a good design IMO.

**Comment by brian-brazil** [comment]
It's not Prometheus specific, however I don't think we should be going against general Prometheus philosophy for the sake of other monitoring systems.

**Comment by SuperQ** [comment]
Do you have any real-world data or evidence to show where you're hitting issues? Benchmarks for the problem?
