### ISSUE TITLE
non-root icmp is broken in docker

### ISSUE THREAD

**Issue by sepich** [prometheus/blackbox_exporter#689]
### blackbox_exporter version: output of `blackbox_exporter -version`
v0.17.0

### What did you do that produced an error?
Thank you for implementing of https://github.com/prometheus/blackbox_exporter/issues/147, unfortunately it is currently broken in docker:
```
docker run -d -p 9115:9115 -u 65534 --cap-add=NET_RAW prom/blackbox-exporter:v0.17.0
curl -s 'localhost:9115/probe?target=127.0.0.1&module=icmp&debug=true'
...
ts=2020-09-03T16:01:33.3109842Z caller=main.go:119 module=icmp target=127.0.0.1 level=info msg="Creating socket"
ts=2020-09-03T16:01:33.311053Z caller=main.go:119 module=icmp target=127.0.0.1 level=debug msg="Unable to do unprivileged listen on socket, will attempt privileged" err="socket: permission denied"
ts=2020-09-03T16:01:33.3111318Z caller=main.go:119 module=icmp target=127.0.0.1 level=error msg="Error listening to socket" err="listen ip4:icmp 0.0.0.0: socket: operation not permitted"
ts=2020-09-03T16:01:33.3111818Z caller=main.go:304 module=icmp target=127.0.0.1 level=error msg="Probe failed" duration_seconds=0.0005185
...
```
Because `cap` is missing in file attributes.
For linux this could be fixed like this:
```
ARG ARCH="amd64"
ARG OS="linux"

FROM alpine
ARG ARCH="amd64"
ARG OS="linux"
COPY .build/${OS}-${ARCH}/blackbox_exporter  /bin/blackbox_exporter
RUN apk add libcap && setcap cap_net_raw+ep /bin/blackbox_exporter
COPY blackbox.yml  /etc/blackbox_exporter/config.yml

EXPOSE      9115
ENTRYPOINT  [ "/bin/blackbox_exporter" ]
CMD         [ "--config.file=/etc/blackbox_exporter/config.yml" ]
```
Example image for testing:
```
docker run -d -p 9115:9115 -u 65534 --cap-add=NET_RAW sepa/blackbox-exporter:v0.17.0
curl -s 'localhost:9115/probe?target=127.0.0.1&module=icmp&debug=true'
...
ts=2020-09-03T16:07:45.9064384Z caller=main.go:119 module=icmp target=127.0.0.1 level=info msg="Creating socket"
ts=2020-09-03T16:07:45.9065393Z caller=main.go:119 module=icmp target=127.0.0.1 level=debug msg="Unable to do unprivileged listen on socket, will attempt privileged" err="socket: permission denied"
ts=2020-09-03T16:07:45.9067614Z caller=main.go:119 module=icmp target=127.0.0.1 level=info msg="Creating ICMP packet" seq=32891 id=11676
ts=2020-09-03T16:07:45.9068124Z caller=main.go:119 module=icmp target=127.0.0.1 level=info msg="Writing out packet"
...
```

**Comment by brian-brazil** [comment]
This sounds like a Docker issue rather than a blackbox exporter issue if the Linux non-root way has been setup on your end and isn't working.

Also from a general security standpoint, I don't want a privileged container by default as that's unnecessary escalation surface if you're not using ICMP.

**Comment by sepich** [comment]
Could you please elaborate on that:
>Linux non-root way has been setup on your end

Does it mean all kubernetes cluster nodes should have `net.ipv4.ping_group_range = 0 2147483647` set just to run blackbox_exporter pod? There are a lot of managed k8s solutions and such a requirement sounds funny, people would just have to build own non-upstream image.

> I don't want a privileged container by default 

Sorry, I do not understand how a setcap inside of container makes it privileged

**Comment by brian-brazil** [comment]
> Does it mean all kubernetes cluster nodes should have net.ipv4.ping_group_range = 0 2147483647 set just to run blackbox_exporter pod?

If that's the way you want icmp to be allowed work. This is a usage question which I can't really help you with, how you deploy the exporter is up to you.

> I do not understand how a setcap inside of container makes it privileged

Any use of setcap is privileged, for example NET_RAW allows snooping on everything going through the network stack.

**Comment by sepich** [comment]
> If that's the way you want icmp to be allowed work.

Could you please specify any other way of running blackbox_exporter in k8s as non-root with icmp working? I believe it really worth to document them in Readme. Sorry if i repeat myself - but starting of container with NET_RAW caps does not work now.

> Any use of setcap is privileged, for example NET_RAW allows snooping on everything going through the network stack.

Happily that is not how it works for docker/k8s. Having container with some file with attributes does not automatically grants any permissions for that container. You still need to grant this specifically via `--cap-add=NET_RAW` or
```
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_RAW
```
I'm just asking about implementing the fix in the original image, so that people do not have to build their own child images with only file attribute change.

**Comment by brian-brazil** [comment]
> I believe it really worth to document them in Readme.

It's already there: https://github.com/prometheus/blackbox_exporter#permissions

> I'm just asking about implementing the fix in the original image,

As I've indicated, while I see the use of that that's escalation surface area that should not be exposed unless the user explicitly configures it. This is something to handle in your own configuration, not within the generally available image.

**Comment by yegle** [comment]
@brian-brazil Unless the GA image also include a `setcap` command, there's really no way for the user to fix it though.

**Comment by brian-brazil** [comment]
You can pass it on the command line to docker, and if you're using K8s you can also specify this there. This would not be the secure default, so this is more a Docker usage question - so I'm going to close this off now.

**Comment by yegle** [comment]
From my understanding there are two parts of the problem
1. The binary inside the container will need to have the `cap_new_raw` capability.
2. The container itself need to have the `cap_new_raw` capability

Passing `--cap-add=NET_RAW` when creating the container alone won't work. And because there's no `setcap` inside the image, there's no way to add this capacity to the binary.

On the other hand, having the official image containing a binary with extended attribute alone does NOT pose a security risk, because you still need to explicitly grant the needed capacity to the container.

The ONLY possible way to somehow reuse the official image is:
1. Create a new image, include a setcap binary
2. Copy from the official image
3. `setcap` on the binary

Please reconsider.

**Comment by bobbywatson3** [comment]
For anyone else who gets stuck on this, here is the workaround that I used. This workaround is really not great from an end-user point of view.

```dockerfile
FROM prom/blackbox-exporter:v0.17.0 as bbe

FROM alpine:3.12.0
RUN apk update && apk add libcap
COPY --from=bbe /bin/blackbox_exporter /bin/blackbox_exporter
COPY --from=bbe /etc/blackbox_exporter/config.yml /etc/blackbox_exporter/config.yml
RUN setcap cap_net_raw+ep /bin/blackbox_exporter

EXPOSE      9115
ENTRYPOINT  [ "/bin/blackbox_exporter" ]
CMD         [ "-config.file=/etc/blackbox_exporter/config.yml" ]

**Comment by yegle** [comment]
It looks like the better solution is to use https://github.com/scionproto/docker-caps

The README contains the example to set cap on blackbox_exporter image.

**Comment by loganmc10** [comment]
I'd like to add a +1 to this. The README is deceiving since it makes it sound like giving a container CAP_NET_RAW will solve this issue.

Adding cap_net_raw to the executable isn't a security risk. Ultimately it's the OS (or container platform) that controls access to the capability
