### ISSUE TITLE
Weird log output for "Build context"

### ISSUE THREAD

**Issue by candlerb** [prometheus/blackbox_exporter#699]
This is a trivial issue with the format of log output.

### Host operating system: output of `uname -a`

```
Linux prometheus 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### blackbox_exporter version: output of `blackbox_exporter -version`

```
blackbox_exporter, version 0.18.0 (branch: HEAD, revision: 60c86e6ce5a1111f7958b06ae7a08222bb6ec839)
  build user:       root@53d72328d93f
  build date:       20201012-09:46:31
  go version:       go1.15.2
```

### What is the blackbox.yml module config.

N/A

### What is the prometheus.yml scrape config.

N/A

### What logging output did you get from adding `&debug=true` to the probe URL?

N/A

### What did you do that produced an error?

Just start blackbox exporter, and look at what it logs to stderr as it starts.

### What did you expect to see?

This is what snmp_exporter shows:

```
Oct 05 10:34:37 prometheus snmp_exporter[18259]: level=info ts=2020-10-05T10:34:37.075Z caller=main.go:150 build_context="(go=go1.14.7, user=root@387afaad41d6, date=20200831-12:07:03)"
```

Note that build_context shows sensible structured data.

### What did you see instead?

With blackbox_exporter the message is garbled:

```
12T11:14:17.773Z caller=main.go:213 msg="Build context" (gogo1.15.2,userroot@53d72328d93f,date20201012-09:46:31)=(MISSING)
```

### Notes

Looking at source code, snmp_exporter has:

```
./main.go:	level.Info(logger).Log("build_context", version.BuildContext())
```

blackbox_exporter has:

```
./main.go:	level.Info(logger).Log("msg", "Build context", version.BuildContext())
```

Perhaps `"msg"` is spurious here?

**Comment by brian-brazil** [comment]
Yeah, https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/main.go#L358 is what is should look like. Would you like to send a PR?
