### ISSUE TITLE
Blackbox Panic Errors.

### ISSUE THREAD

**Issue by Yagyansh** [prometheus/blackbox_exporter#708]
### Host operating system: output of `uname -a`
[myuser@infra-prometheus ~]# uname -a
Linux myhostname 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`

[myuser@infra-prometheus ~]# /usr/local/bin/blackbox_exporter --version
blackbox_exporter, version 0.18.0 (branch: HEAD, revision: 60c86e6ce5a1111f7958b06ae7a08222bb6ec839)
build user:       root@53d72328d93f
build date:       20201012-09:46:31
go version:       go1.15.2

### What is the blackbox.yml module config.
  http_healthcheck:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0", "HTTP/1.0"]
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4"

  http_healthcheck_es:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0", "HTTP/1.0"]
      fail_if_body_not_matches_regexp: ['green']
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4"

  http_healthcheck_ok:
    prober: http
    timeout: 10s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0", "HTTP/1.0"]
      fail_if_body_not_matches_regexp: ['OK']
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4"

### What is the prometheus.yml scrape config.
global:
  scrape_interval: 25s
  scrape_timeout: 25s
  evaluation_interval: 1m

  - job_name: 'blackbox_Service-HealthChecks'
    metrics_path: /probe
    params:
      module: [http_healthcheck]
    file_sd_configs:
      - files:
        - /etc/blackbox/HTTP_TCP-Targets/HealthCheck_Targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__address__]
        regex: '(.+):(.+)'
        target_label: expo1
        replacement: '${1}:9100'
      - source_labels: [__address__]
        regex: '(.+):(.+)'
        target_label: expo2
        replacement: '${1}:4444'
      - target_label: __address__
        replacement: x.x.x.x:9115
    scrape_interval: 10s

### What logging output did you get from adding `&debug=true` to the probe URL?
Not an issue with a specific URL, the BlackBox throws panic errors.

### What did you expect to see?
No Panic Errors.

### What did you see instead?
Nov  3 15:01:38 infra-prometheus blackbox_exporter: 2020/11/03 15:01:38 http: panic serving y.y.y.y:52194: runtime error: invalid memory address or nil pointer dereference
Nov  3 15:04:08 infra-prometheus blackbox_exporter: 2020/11/03 15:04:08 http: panic serving y.y.y.y:53910: runtime error: invalid memory address or nil pointer dereference
Nov  3 15:09:08 infra-prometheus blackbox_exporter: 2020/11/03 15:09:08 http: panic serving y.y.y.y:57586: runtime error: invalid memory address or nil pointer dereference
Nov  3 15:11:38 infra-prometheus blackbox_exporter: 2020/11/03 15:11:38 http: panic serving y.y.y.y:59352: runtime error: invalid memory address or nil pointer dereference
Nov  3 15:14:08 infra-prometheus blackbox_exporter: 2020/11/03 15:14:08 http: panic serving y.y.y.y:61084: runtime error: invalid memory address or nil pointer dereference
Nov  5 12:11:40 infra-prometheus blackbox_exporter: 2020/11/05 12:11:40 http: panic serving y.y.y.y:54972: runtime error: invalid memory address or nil pointer dereference
Nov  7 02:33:11 infra-prometheus blackbox_exporter: 2020/11/07 02:33:11 http: panic serving x.x.x.x:53326: runtime error: invalid memory address or nil pointer dereference
Nov  7 02:53:11 infra-prometheus blackbox_exporter: 2020/11/07 02:53:11 http: panic serving x.x.x.x:4570: runtime error: invalid memory address or nil pointer dereference
Nov  7 02:55:41 infra-prometheus blackbox_exporter: 2020/11/07 02:55:41 http: panic serving x.x.x.x:6560: runtime error: invalid memory address or nil pointer dereference
Nov  7 02:58:11 infra-prometheus blackbox_exporter: 2020/11/07 02:58:11 http: panic serving x.x.x.x:8636: runtime error: invalid memory address or nil pointer dereference

I have a HA Prometheus setup so. x.x.x.x and y.y.y.y are the instances where my Prometheus is running.

**Comment by brian-brazil** [comment]
That isn't enough to go on, can you give an example of the request that's causing this and a tcpdump?

**Comment by Yagyansh** [comment]
There isn't anything about the request in the logs that could be causing this. Can you help me on how to go about finding that particular request?

**Comment by brian-brazil** [comment]
I'd start out by finding which scrapes are failing in Prometheus by looking at up.

**Comment by brian-brazil** [comment]
Lacking further information I'm afraid I can't do anything to debug this so closing for now.
