### ISSUE TITLE
Multiple Http Probes in Sequence Question

### ISSUE THREAD

**Issue by winshenting** [prometheus/blackbox_exporter#712]
I want to monitor API functions. Therefore, I am doing survey on Prometheus Blackbox_exporter.
I have one request about setting up multiple API monitoring Steps in Sequence in one job
For example, 
Get URL firstly, afterwards Post URL
Is it possible to do it?

**Comment by brian-brazil** [comment]
The http probe will follow redirects, beyond that you'll need to write an exporter for your specific application as this exporter only covers very basic protocol probing.
