### ISSUE TITLE
[Feature Request] > Metric for unknown module

### ISSUE THREAD

**Issue by gavk34** [prometheus/blackbox_exporter#715]
Currently this is hidden in the response
https://github.com/prometheus/blackbox_exporter/blob/9fd70341277528877d55bfeffd46593646bca347/main.go#L77

Would be great to add two info points to this
- Log Error message
- Metric

Reason we ask for a metric is so that we(SRE) team can alert on misconfiguration of the module by teams. Thanks

I might get time to do this myself...seems easy enough 🤞

**Comment by brian-brazil** [comment]
That sounds reasonable to me.

**Comment by gavk34** [comment]
Thanks  @brian-brazil - I have a branch with changes locally but getting 403 when attempting to push.

**Comment by brian-brazil** [comment]
You probably need to push to your fork, rather than to this repo.

**Comment by gavk34** [comment]
🤦  On that - yep will do and raise the PR then 😊

**Comment by gavk34** [comment]
https://github.com/prometheus/blackbox_exporter/pull/716
