### ISSUE TITLE
[Feature Request] provide an easy way to set all status codes as valid

### ISSUE THREAD

**Issue by shibumi** [prometheus/blackbox_exporter#721]
Hi,

I would like to propose a change for the range of valid HTTP status codes for the http probe module.
Right now it's possible to specify a set of valid http status codes. If the probe does not match the valid code the blackbox exporter
will log this code as "0". Furthermore it is possible to set the alias "2xx" for all status codes between [200.300).

I kinda don't understand why it even is this way. It bugs me when I get paged, because of a returned status code "0".
"0" is okay for me if it's a problem of the blackbox exporter, but if the status code has been a error 500 or 400 or whatever the blackbox exporter should log this.

The problem right now is that there is no alias for 'making all status codes valid' for logging. Alerting is a different topic, because this is working fine when I set `status code has to be == 200 or between 200 and 300`. 

What I would like be able to is setting an alias like `xxx` that allows all status codes for logging and then specifying the range as prometheusrule for the alerting.

**Comment by brian-brazil** [comment]
I'm a bit confused here, what type of HTTP endpoint blackbox monitoring are you doing such that the HTTP request completely failing (which is when status code 0 is reported) is not a probe failure? What failures are you catching with probe_success?

> If the probe does not match the valid code the blackbox exporter will log this code as "0".

That's not the case. 0 means a network issue or similar.

I think you're misunderstanding how this exporter works, and how it's intended to be used. I'd suggest https://www.robustperception.io/checking-for-specific-http-status-codes-with-the-blackbox-exporter

**Comment by shibumi** [comment]
@brian-brazil as far as I understood how blackbox exporter works:

If I set the following:
```
modules:
  http_204:
    prober: http
    http:
      valid_status_codes: [204]
```

Every other status code that is different to 204 will get reported as status code "0", because it does not match the configured probe module.

Isn't this correct? If not, what is the exact purpose for `valid_status_codes`? Is it only for specifying a value for `probe_success`?
So if my returned status code does not match 204 the `probe_success` metric will turn to `0`?

I think blackbox exporter is mixing up pure metric gathering functionality with functionality for alerting.

So "0" means network issue or similar. Is "network issue or similar" clearly documented somewhere? In my logs I just see "connection error: PROTOCOL ERROR" no idea what this means.. TCP? HTTP? which protocol layer? and what error exactly?

**Comment by brian-brazil** [comment]
> Isn't this correct?

It's not, if you're seeing that then it's a bug.

> Is it only for specifying a value for probe_success?

Yes.

> In my logs I just see "connection error: PROTOCOL ERROR" no idea what this means.. TCP? HTTP? which protocol layer? and what error exactly?

That is a question that is beyond the scope of this exporter I'm afraid. It can only tell you that something has gone wrong, and provide some hints in the right direction. Exactly what is going wrong with your systems is for you to debug.

**Comment by brian-brazil** [comment]
Closing as this seems to be primarily a usage question.
