### ISSUE TITLE
Support proxy configuration from environment for the http probe

### ISSUE THREAD

**Issue by pelov** [prometheus/blackbox_exporter#727]
### blackbox_exporter version:
```
blackbox_exporter, version 0.18.0 (branch: HEAD, revision: 60c86e6ce5a1111f7958b06ae7a08222bb6ec839)
  build user:       root@53d72328d93f
  build date:       20201012-09:46:31
  go version:       go1.15.2
```
### What did you expect to see?

For the http probe it would be convenient instead of hard coding the proxy url in the configuration file to have an option, for example `proxy_from_environment: true` which reads the proxy configuration from the standard environment variables http_proxy, https_proxy and no_proxy. This will be very useful in situations where one wants to put the config file in version control and deploy it in different environments with different proxy configurations (or no proxy).

### What did you see instead?

Currently, the only way to specify proxy is to hard code it in the config file with the `proxy_url` option.

I am willing to help with a PR if this sounds like a useful feature? I see that there is a function `ProxyFromEnvironment` in the go http client library which will probably do the job.

**Comment by brian-brazil** [comment]
As a matter of policy, we do not read configuration from the environment and configuration only comes from one place. The config file is the way to configure this, and how you making that happen from your configuration management system is up to you.

**Comment by pelov** [comment]
Just found that this has been already discussed [elsewhere](https://github.com/prometheus/common/pull/94).

Thanks anyway for the quick reply!
