### ISSUE TITLE
Support specifying TLS signature_algorithms

### ISSUE THREAD

**Issue by klausenbusk** [prometheus/blackbox_exporter#731]
We are providing both a RSA and ECDSA certificate (https://scotthelme.co.uk/hybrid-rsa-and-ecdsa-certificates-with-nginx/) and we need to monitor both certificates.

This is possible by supporting the `signature_algorithms` extensions, supported by both [TLS 1.2](https://tools.ietf.org/html/rfc5246#section-7.4.1.4.1) and [TLS 1.3](https://tools.ietf.org/html/rfc8446#section-4.2.3) (from the TLS 1.2 RFC):

> The client uses the "signature_algorithms" extension to indicate to
> the server which signature/hash algorithm pairs may be used in
> digital signatures.  The "extension_data" field of this extension
> contains a "supported_signature_algorithms" value.
> [...]
> hash
>    This field indicates the hash algorithm which may be used.  The
>    values indicate support for unhashed data, MD5 [MD5], SHA-1,
>    SHA-224, SHA-256, SHA-384, and SHA-512 [SHS], respectively.  The
>    "none" value is provided for future extensibility, in case of a
>    signature algorithm which does not require hashing before signing.
>
> signature
>    This field indicates the signature algorithm that may be used.
>    The values indicate anonymous signatures, RSASSA-PKCS1-v1_5
>    [PKCS1] and DSA [DSS], and ECDSA [ECDSA], respectively.  The
>    "anonymous" value is meaningless in this context but used in
>    Section 7.4.3.  It MUST NOT appear in this extension.

OpenSSL experiment:
```sh
$ alias op='openssl x509 -text -noout -in'
$ openssl s_client -tls1_2 -sigalgs "RSA+SHA256 " -connect cloudflare.com:443 |& op - | grep "Public Key Algorithm"
            Public Key Algorithm: rsaEncryption
$ openssl s_client -tls1_2 -sigalgs "ECDSA+SHA256 " -connect cloudflare.com:443 |& op - | grep "Public Key Algorithm"
            Public Key Algorithm: id-ecPublicKey
$ openssl s_client -tls1_3 -sigalgs "RSA+SHA256 " -connect cloudflare.com:443 |& op - | grep "Public Key Algorithm"
            Public Key Algorithm: rsaEncryption
$ openssl s_client -tls1_3 -sigalgs "ECDSA+SHA256 " -connect cloudflare.com:443 |& op - | grep "Public Key Algorithm"
            Public Key Algorithm: id-ecPublicKey
```

**Comment by klausenbusk** [comment]
It looks like `crypto/tls` lack support for specifying `signature_algorithms`. I opened a issue: https://github.com/golang/go/issues/43549

**Comment by brian-brazil** [comment]
As I said in #267, I don't think this is something that makes sense to have as an option in all TLS configs in Prometheus/Alertmanager as we only need something to negotiate there. This sounds like something for a custom exporter.

**Comment by klausenbusk** [comment]
> As I said in #267, I don't think this is something that makes sense to have as an option in all TLS configs in Prometheus/Alertmanager as we only need something to negotiate there.

I kinda misread that issue. Correct, this is probably only useful for monitoring.

> This sounds like something for a custom exporter.

That is a option. I could fork blackbox_exporter and add the relevant option, but it seems a bit overkill. Looking at [the code](https://github.com/prometheus/common/blob/20c99e7aa07352b599bd0517cd5ca945f4af0407/config/http_config.go#L83-L95) I expect the amount of code to be low (5-20 LOC).

.. and with certbot [finally](https://github.com/certbot/certbot/releases/tag/v1.10.0) supporting ECDSA certificates, I expect hybrid RSA/ECDSA setups to be more common.

If this features gets implemented, we plan on using it for monitoring the Arch Linux infrastructure: https://gitlab.archlinux.org/archlinux/infrastructure/-/issues/208

**Comment by brian-brazil** [comment]
You might want to look at https://github.com/ribbybibby/ssl_exporter, it does more in depth TLS stuff. This exporter only does basic expiry monitoring as a side effect.

**Comment by klausenbusk** [comment]
Closing this as upstream doesn't want to support the needed features: https://github.com/golang/go/issues/43549#issuecomment-760235026 and I think it is unlikely that you want to switch to a different TLS library for this niche feature.
