### ISSUE TITLE
make doesn't work

### ISSUE THREAD

**Issue by yegle** [prometheus/blackbox_exporter#736]
I was getting this error trying to run `make`:

```
$ make
>> checking code style
>> checking license header
>> running golangci-lint
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
GO111MODULE=on /home/yegle/gopkg/bin/golangci-lint run  ./...
ERRO Running error: context loading failed: failed to load packages: failed to load with go/packages: err: exit status 1: stderr: build flag -mod=vendor only valid when using modules
make: *** [Makefile.common:192: common-lint] Error 3
```

**Comment by yegle** [comment]
`go version`

version
go version go1.15.6 linux/amd64

**Comment by brian-brazil** [comment]
This sounds like an issue with your golangci-lint

**Comment by yegle** [comment]
This is a freshly installed golangci-lint though:

```
go get -v -u github.com/golangci/golangci-lint/cmd/golangci-lint
```

**Comment by brian-brazil** [comment]
I'm not sure what's going on then, it looks to be something specific to your build environment.

**Comment by yegle** [comment]
Hmm it looks like some issue with the latest version of golangci-lint. The doc suggest to not install from master: https://golangci-lint.run/usage/install/#install-from-source

Installing the latest version of golangci-lint seems to fix the breakage. However, when running make on a system without golangci-lint (tested inside the golang container), version 1.18.0 would be installed, which seems old. The latest golangci-lint found a couple of issues in the source code.

I'll close this bug and send a PR to update the version as well as fix the issue it found.

**Comment by brian-brazil** [comment]
Thanks for debugging, if there's something that needs updating on our side the main Prometheus repo is where to tweak it.
