### ISSUE TITLE
golangci-lint 1.35.2 identified some nil pointer dereference

### ISSUE THREAD

**Issue by yegle** [prometheus/blackbox_exporter#738]
I updated golangci-lint to 1.35.2 (the latest as of now) and it appears have identified some possible nil pointer dereference:

```
$ golangci-lint run ./...
prober/http.go:451:48: SA5011: possible nil pointer dereference (staticcheck)
                byteCounter := &byteCounter{ReadCloser: resp.Body}
                                                             ^
prober/http.go:482:36: SA5011: possible nil pointer dereference (staticcheck)
                if t, err := http.ParseTime(resp.Header.Get("Last-Modified")); err == nil {
                                                 ^
prober/http.go:488:71: SA5011: possible nil pointer dereference (staticcheck)
                httpVersionNumber, err = strconv.ParseFloat(strings.TrimPrefix(resp.Proto, "HTTP/"), 64)
```

**Comment by brian-brazil** [comment]
From a quick look those are all false positives.

**Comment by dominikh** [comment]
Strictly speaking they're not false positives. Line 462 checks that `resp != nil && !requestErrored`, while line 451 unconditionally dereferences resp. The check establishes the expectation that resp might be nil.

I agree that at runtime, resp cannot be nil in the else branch, but that makes your `resp != nil` check unnecessary, too. Removing it will remove the warning.

As an aside, when running Staticcheck directly, you would get the following output, pointing at the exact reason for the warning:

```
http.go:451:48: possible nil pointer dereference (SA5011)
	http.go:462:6: this check suggests that the pointer can be nil
http.go:482:36: possible nil pointer dereference (SA5011)
	http.go:462:6: this check suggests that the pointer can be nil
http.go:488:71: possible nil pointer dereference (SA5011)
	http.go:462:6: this check suggests that the pointer can be nil
```

**Comment by brian-brazil** [comment]
> that makes your resp != nil check unnecessary, too

If memory serves, unfortunately not as that call can return a non-nil resp when there's an error.

**Comment by dominikh** [comment]
Right, but if you're saying that resp might be nil in the else branch, then all of the unconditional dereferences of resp could attempt dereferencing a nil pointer.

But the way I am reading it, resp will always be not nil. we're in the else branch of `if err != nil && resp == nil { } else { }` so there are two ways to get here: `err == nil` or `resp != nil`. If `err == nil`, then `resp` will not be nil. If `resp != nil`, then it is obviously not nil.

To be clear, when I say "that makes your resp != nil check unnecessary, too", then I mean the check inside the else branch, namely `if resp != nil && !requestErrored`. I believe that should be `if !requestErrored` instead.

**Comment by brian-brazil** [comment]
Hmm, working through the logic I think you're right for line 462.
