### ISSUE TITLE
Feature Request: Return the resolved IP address 

### ISSUE THREAD

**Issue by stwellman** [prometheus/blackbox_exporter#740]
For modules that return an IP address hash, it would be useful to also return the resolved IP address.  The code is already resolving the IP and could return it as a label similar to the below examples: 

probe_ip_addr_hash{ip_addr="127.0.0.1"} 5.98285105e+08
probe_resolved_ip_addr_info{ip_addr="127.0.0.1"} 1

A specific use-case would be for companies monitoring servers in multiple data centers since the data center can often be derived from the network part of the address.   The presentation layer (like Grafana) could possibly translate the IP to a data center name using regex for easier isolation of root problem.

**Comment by brian-brazil** [comment]
This is on purpose, as it could lead to cardinality issues as there's effectively no bound on how many different IP addresses might be resolved over time especially for v6. Thus it's only returned as a hashed value.

**Comment by stwellman** [comment]
Thanks for the reply.  I think I understand what you are saying.  Basically, each time the address changes, it would be a new time series since the IP is essentially part of the "key".  That would totally break the functionality of the hash.  For my purposes, though, I still think the benefits outweigh the drawbacks.  I am going to modify the code locally, but I can understand why it can't be added here.

**Comment by brian-brazil** [comment]
> Basically, each time the address changes, it would be a new time series since the IP is essentially part of the "key".

Yes, and each of those costs RAM in Prometheus. Thousands are not out of the question, more if IPv6 privacy stuff that continuously rotated addresses is involved.

> That would totally break the functionality of the hash.

That's separate. There's no way to expose this as a label that avoids the cardinality issue.
