### ISSUE TITLE
Issue with blackboxexporter connect: connection refused

### ISSUE THREAD

**Issue by avanichy25** [prometheus/blackbox_exporter#741]
I am trying to use blackexporter with prometheus for testing i am using google.com as target but i am getting error using localhost:9115 which is connect: connection refused and with  machineip:9115 as no host or route found.

### blackbox_exporter version: output of `blackbox_exporter --version`
blackbox-exporter:master

blackboxexporter:
    image: docker.io/prom/blackbox-exporter:master
    volumes:
      - ./blackboxexporter/blackbox.yml:/config/blackbox.yml
    ports:
      - 9115:9115
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - xxxxx
      - xxxxx
    container_name: blackbox-exporter
    restart: always### What is the blackbox.yml module config.

### What is the prometheus.yml scrape config.
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

Error:
  ```
  Get "http://localhost:9115/probe?module=http_2xx&target=https%3A%2F%2Fgoogle.com": dial tcp 127.0.0.1:9115: connect: connection refused

```
```
Get "http://xxxxxx:9115/probe?module=http_2xx&target=https%3A%2F%2Fgoogle.com": dial tcp xxxxxx:9115: connect: no route to host
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
