### ISSUE TITLE
probe failed issue when monitoring web app with blackbox exporter

### ISSUE THREAD

**Issue by hanjerry12** [prometheus/blackbox_exporter#742]
while I use hyperledger fabric web app server i want to use blackbox exporter to see the state but i can't can you help me? 
### Host operating system: output of `uname -a`
Linux aisec.yu.ac.kr 5.4.0-62-generic #70~18.04.1-Ubuntu SMP Tue Jan 12 17:18:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter --version`
blackbox_exporter, version 0.18.0 (branch: HEAD, revision: 60c86e6ce5a1111f7958b06ae7a08222bb6ec839)
  build user:       root@53d72328d93f
  build date:       20201012-09:46:31
  go version:       go1.15.2

### What is the blackbox.yml module config.

modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: []
      method: GET

### What is the prometheus.yml scrape config.
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
            - targets:
                    - http://localhost:8081
                    - http://localhost:9090
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

### What did you expect to see?
probe success 
 
### What did you see instead?
level=error msg="Probe failed"

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
