### ISSUE TITLE
Does Blackbox_Exporter Support Http Method: Delete or Insert

### ISSUE THREAD

**Issue by winshenting** [prometheus/blackbox_exporter#754]
Does BlackBox_Exporter Support Http Method : Delete or Insert. I did not see any examples about them

**Comment by mem** [comment]
It supports any valid method, so yes, it does support DELETE and extension methods. You have to make sure that the request is valid, though.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
