### ISSUE TITLE
Feature request: Blackbox external labels

### ISSUE THREAD

**Issue by rhgreene** [prometheus/blackbox_exporter#756]
I'm using blackboxes to test availability of shared tooling capabilities from within each subnet in a large-scale infrastructure. Having external labels unique to each blackbox (based on where the blackbox is located ie team/department/subnet function) would aid the filtering capability of the final visualisations and aid in routing of alerts in alertmanager.

The blackboxes are discovered within prometheus generically by DNS, so the function of each blackbox's VPC is not available to them. Being able to add labels to each blackbox, that would appear in their scraped metrics, seems like something that would be useful for many use cases?

**Comment by SuperQ** [comment]
Sorry, this is a job for the Prometheus scrape configuration. Exporters should never have the concept of external labels. This is the standard across the whole ecosystem.

**Comment by rhgreene** [comment]
Makes sense if it's ethos.
Thanks
