### ISSUE TITLE
Missing Documentation about specifying valid status code ranges

### ISSUE THREAD

**Issue by Sebi2020** [prometheus/blackbox_exporter#757]
Currently there is no documentation which explains how you can specify valid code ranges. The documentation says "default: 2xx", but if you also want to add 301, 302 as valid codes, for example  `[2xx, 301, 302]` you get the error:

```level error [...] caller=main.go:228 msg="Error loading config" err="error parsing config file: yaml: unmarshal errors:\n  line 7: cannot unmarshal !!str `2xx` into int"```

Does this mean there is no mechanism to specify ranges like 200-299? If this holds true, the documentation at `CONFIGURATION.md` is misleading, because it looks like "2xx" would be a valid value for all 2xx codes. But I think if I really want to catch all 200 codes and the redirection codes I have to enter 102 codes manually...  `[200,201,...,298,299,301,302]`

**Comment by roidelapluie** [comment]
Hello,

We do not provide a way to specify a range. But in the 200-300 range, there is only 10 valid http return code, and I'd expect that you know in advance which code your apps can return in the 2xx range.

**Comment by Sebi2020** [comment]
Thank you for your reply.
