### ISSUE TITLE
Redirect for non-empty route-prefix if asking for /

### ISSUE THREAD

**Issue by kmille** [prometheus/blackbox_exporter#772]
Hey, 
If I specify `--web.route-prefix /abc` and make a request to /, shouldn't we get redirected to /abc?

```bash
kmille@linbox:blackbox_exporter ./blackbox_exporter --log.level=debug --web.route-prefix /abc
level=info ts=2021-04-03T19:21:39.063Z caller=main.go:224 msg="Starting blackbox_exporter" version="(version=0.18.0, branch=master, revision=e9482560a52eaadde1bf7cf083f5d1c7f9fba5b4)"
level=info ts=2021-04-03T19:21:39.063Z caller=main.go:225 build_context="(go=go1.16.2, user=kmille@linbox, date=20210403-19:20:47)"
level=info ts=2021-04-03T19:21:39.064Z caller=main.go:237 msg="Loaded config file"
level=debug ts=2021-04-03T19:21:39.064Z caller=main.go:245 externalURL=http://linbox:9115
level=debug ts=2021-04-03T19:21:39.064Z caller=main.go:259 routePrefix=/abc/
level=info ts=2021-04-03T19:21:39.064Z caller=main.go:381 msg="Listening on address" address=:9115
level=info ts=2021-04-03T19:21:39.064Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
```

```bash
kmille@linbox:blackbox_exporter curl localhost:9115/           
<a href="http://linbox:9115">Found</a>.
```
I expected to see a redirect to http://linbox:9115/abc. Redirecting to / doesn't make any sense to me. But If we are behind a reverse proxy, blackbox exporter won't get a request to /.

I'm a little bit confused by this behaviour. If you confirm that it's a bug I can create a PR.

**Comment by electron0zero** [comment]
This is expected behaviour and not a bug. 

If you don't want prefix, you can remove `--web.route-prefix /abc` , and it will be available at root.

when using prefix like `--web.route-prefix /abc`, we do redirect from `http://localhost:9115/abc` to `http://localhost:9115/abc/`
