### ISSUE TITLE
"Resolution with IP protocol failed"

### ISSUE THREAD

**Issue by TuNGO-86** [prometheus/blackbox_exporter#773]
### Host operating system: output of `uname -a`
Ubuntu 20.04 LTS
### What is the blackbox.yml module config.
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: true

### What is the prometheus.yml scrape config.
- job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://portal.infini.vn
        - https://portal.vninfini.vn
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.2.5.17:9115

### What logging output did you get from adding `&debug=true` to the probe URL?
Logs for the probe:
ts=2021-04-05T02:54:08.256144218Z caller=main.go:304 module=http_2xx target=https://portal.infini.vn level=info msg="Beginning probe" probe=http timeout_seconds=5
ts=2021-04-05T02:54:08.256770391Z caller=http.go:342 module=http_2xx target=https://portal.infini.vn level=info msg="Resolving target address" ip_protocol=ip4
ts=2021-04-05T02:54:08.259016797Z caller=http.go:342 module=http_2xx target=https://portal.infini.vn level=error msg="Resolution with IP protocol failed" err="lookup portal.infini.vn on 127.0.0.53:53: no such host"
ts=2021-04-05T02:54:08.259098964Z caller=main.go:119 module=http_2xx target=https://portal.infini.vn level=error msg="Error resolving address" err="lookup portal.infini.vn on 127.0.0.53:53: no such host"
ts=2021-04-05T02:54:08.259125284Z caller=main.go:304 module=http_2xx target=https://portal.infini.vn level=error msg="Probe failed" duration_seconds=0.002731403

Metrics that would have been returned:
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.00225112
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.002731403
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length 0
# HELP probe_http_duration_seconds Duration of http request by phase, summed over all redirects
# TYPE probe_http_duration_seconds gauge
probe_http_duration_seconds{phase="connect"} 0
probe_http_duration_seconds{phase="processing"} 0
probe_http_duration_seconds{phase="resolve"} 0
probe_http_duration_seconds{phase="tls"} 0
probe_http_duration_seconds{phase="transfer"} 0
# HELP probe_http_redirects The number of redirects
# TYPE probe_http_redirects gauge
probe_http_redirects 0
# HELP probe_http_ssl Indicates if SSL was used for the final redirect
# TYPE probe_http_ssl gauge
probe_http_ssl 0
# HELP probe_http_status_code Response HTTP status code
# TYPE probe_http_status_code gauge
probe_http_status_code 0
# HELP probe_http_uncompressed_body_length Length of uncompressed response body
# TYPE probe_http_uncompressed_body_length gauge
probe_http_uncompressed_body_length 0
# HELP probe_http_version Returns the version of HTTP of the probe response
# TYPE probe_http_version gauge
probe_http_version 0
# HELP probe_ip_addr_hash Specifies the hash of IP address. It's useful to detect if the IP address changes.
# TYPE probe_ip_addr_hash gauge
probe_ip_addr_hash 0
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 0
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0

Module configuration:
prober: http
timeout: 5s
http:
    valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
    preferred_ip_protocol: ip4
    ip_protocol_fallback: true
    method: GET
tcp:
    ip_protocol_fallback: true
icmp:
    ip_protocol_fallback: true
dns:
    ip_protocol_fallback: true
### What did you do that produced an error?
I probe https://portal.infini.vn and https://portal.vninfini.vn
portal.inifi.vn gives successful results probe_success 1
**But portal.vninfini.vn This site again failed**

### What did you expect to see?
probe_success 1
![123123213](https://user-images.githubusercontent.com/77654266/113534332-a48d0500-95fa-11eb-9457-a6ec026fe084.jpg)

### What did you see instead?
report probe_success 0

**Comment by electron0zero** [comment]
checkout https://github.com/prometheus/blackbox_exporter/issues/424#issuecomment-475790826
