### ISSUE TITLE
doubt - reverse expected result tcp_connect 

### ISSUE THREAD

**Issue by DgoNascimento** [prometheus/blackbox_exporter#774]
Good afternoon people,

I would like to support you.

Basically, what I would like to do is invert the expected result of tcp_connect.

When the communication closes, I would like to get the result "0" in prometheus, indicate failure.
Any result other than this (timeout, for example), returns "1", with an indication of success.

I tried something according to CONFIGURATION.md, without success. In whatever they can help, I thank you in advance.

**Comment by roidelapluie** [comment]
What proble are you trying to solve here? I do not understand your issue.

**Comment by DgoNascimento** [comment]
Hi roidelapluie,

I need to make two tcp calls:

first-host-host on port 6379
first-host-host on port 6380

Port 6380 is successful and therefore the return from probe_sucess is "1".
However, port 6379 does not respond (which is correct). This way it fails and the return of sonda_sucesso is "0".

What I need is for the test return to port 6379 to be successful when a communication is not made. Probe_Success = 1
And if by chance the test closes the communication, return fails. Probe_Success = 0

In http calls we have "valid_status_codes" where we were able to change the expected return, but I was unable to achieve something similar to tcp_probe
