### ISSUE TITLE
Support source IP interface for ICMP probe

### ISSUE THREAD

**Issue by n0rad** [prometheus/blackbox_exporter#775]
I'm trying to implement ICMP probes on kube nodes with multiple interface.
This requires `source_ip_address` to be set, but as soon as you deploy it in kube, you cannot really control the ip you will need, since it can be running on any or all nodes. 

I'm wondering if it could be possible to implement a mechanism to support the interface instead of the ip like it's supported with ping : 

```bash
ping -I br22 8.8.8.8
```

This could be implemented by supporting interface names on `source_ip_address` or adding a `source_interface` parameter.

**Comment by electron0zero** [comment]
this is supported, you can use `source_ip_address` on ICMP probe config. https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md#icmp_probe
