### ISSUE TITLE
Sometimes one failed probe fails all another probes

### ISSUE THREAD

**Issue by stupidlamo** [prometheus/blackbox_exporter#790]
Hello there

I have many probers with latest blackbox exporter and many targets for blackbox, looks like a:
blackbox:
  http_2xx:
    notify:
      - https://hidden.url.1
      - https:/hidden.url.2
 http_auth_2xx:
    notify:
      - https://hidden.url.3
      - https://hidden.url.4
...etc, about 100 urls...

modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: [200, 204, 301, 302]
      preferred_ip_protocol: "ip4"
 http_auth_2xx:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: [200, 204, 301, 302]
      preferred_ip_protocol: "ip4"
      basic_auth:
        username: "user"
        password: "password"

And sometimes if one of this urls fails, then exporter automatically fails all another probes instantly.
But sometimes it works correctly and returns one failed URL, but sometimes it looks like failed all urls (I know that they are did not failed 100%)
Logs for the probe looks like:

Logs for the probe:
ts=2021-05-13T18:24:26.375725833Z caller=main.go:304 module=http_2xx target=hidden.url.1 level=info msg="Beginning probe" probe=http timeout_seconds=4.5
ts=2021-05-13T18:24:26.375925454Z caller=http.go:323 module=http_2xx target=hidden.url.1 level=info msg="Resolving target address" ip_protocol=ip4
ts=2021-05-13T18:24:30.875800359Z caller=http.go:323 module=http_2xx target=hidden.url.1 level=error msg="Resolution with IP protocol failed" err="i/o timeout"
ts=2021-05-13T18:24:30.875863724Z caller=main.go:119 module=http_2xx target=hidden.url.1 level=error msg="Error resolving address" err="i/o timeout"
ts=2021-05-13T18:24:30.875890643Z caller=main.go:304 module=http_2xx target=hidden.url.1 level=error msg="Probe failed" duration_seconds=4.500113924

And I don't know how I can solve this problem.
I expect that in the case when a timeout occurs, the error is returned only for the probe that timeouts, and not for all checks.

**Comment by electron0zero** [comment]
unable to reproduce this issue, please reopen if you can reproduce this, and share the steps to reproduce this issue.
