### ISSUE TITLE
Trying to find the metric probe_all_success_sum

### ISSUE THREAD

**Issue by vishnu-anil** [prometheus/blackbox_exporter#792]
### Host operating system: output of `uname -a`
Ubuntu 20
### blackbox_exporter version: output of `blackbox_exporter --version`

0.11.0
### What is the blackbox.yml module config.

> modules:
  http_2xx:
    prober: http
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      no_follow_redirects: false
      preferred_ip_protocol: "ip4"
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true
  http_post_2xx:
    prober: http
    http:
      method: GET
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4"
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp

### What did you expect to see?
I am trying to find a metric probe_all_success_sum so as to get aggregate of the successful probe for a job over a time. I found this is Grafana Synthetic monitoring which uses Blackbox monitoring. 
### What did you see instead?
http://localhost:9115/probe?target=myhost&module=http_200 do not show this metric available in the output

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
