### ISSUE TITLE
Metric for rcode returned from DNS probe

### ISSUE THREAD

**Issue by bennetty** [prometheus/blackbox_exporter#799]
This is a feature request.

Currently the for the DNS probe, the metric `probe_success` returned 0/1 based on the success of the probe but i was wondering if it would be of value to return a metric which counts the number of each rcode for example?

this could give greater detail into the failed DNS probe without having to look through the logs.

Fo example:
rate(probe_dns_rcode{rcode="SERVFAIL"}[5m]) > 0.5
vs 
rate(probe_dns_rcode{rcode="REFUSED"}[5m]) > 0.5
could give better alerts

If this is a feature that is worth doing, i dont mind trying to implement it. Please let me know what you think :)

**Comment by dgl** [comment]
This is covered by #474.

Note using labels would be nice for readability, but is also adding a lot of labels per probe, so I'm looking into doing this with a metric that has the value of the rcode instead.
