### ISSUE TITLE
increate icmp packet count

### ISSUE THREAD

**Issue by svenvg93** [prometheus/blackbox_exporter#806]
I hope someone can help me out.
Im setting up Prometheus and blackbox exporter with icmp module to monitor my internet connection. But it seems it only send one ping per time. is this correct and can I increase that number somewhere.
Blackbox config
```
modules:
http_2xx:
prober: http
http:
preferred_ip_protocol: "ip4"
http_post_2xx:
prober: http
http:
method: POST
tcp_connect:
prober: tcp
icmp:
prober: icmp
```

Prometheus scrape config

```
- job_name: 'ping'
metrics_path: /probe
scrape_interval: 5s
params:
module: [icmp]
file_sd_configs:
- files:
- pinghosts.yaml
relabel_configs:
- source_labels: [__address__]
regex: '(.*);(.*);(.*);(.*)'
target_label: instance
replacement: $1
- source_labels: [__address__]
regex: '(.*);(.*);(.*);(.*)'
target_label: type
replacement: $2
- source_labels: [__address__]
regex: '(.*);(.*);(.*);(.*)'
target_label: provider
replacement: $3
- source_labels: [__address__]
regex: '(.*);(.*);(.*);(.*)'
target_label: target
replacement: $4
- source_labels: [instance]
target_label: __param_target
- target_label: __address__
replacement: blackbox:9115
```

**Comment by SuperQ** [comment]
No, the exporter only sends one packet per probe. You probably want the [smokeping_prober(https://github.com/SuperQ/smokeping_prober).

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
