### ISSUE TITLE
cert vs wildcard

### ISSUE THREAD

**Issue by raypettersen** [prometheus/blackbox_exporter#81]
I'm getting errors in log; 
certificate is valid for *.foo.com, foo.com, not abc.foo.com

Shouldn't blackbox accept a wildcard cert without the extra noise?

**Comment by brian-brazil** [comment]
Are you sure that's a valid wildcard cert?

**Comment by raypettersen** [comment]
It's a valid geotrust certificate. However it might just be a matter of missing CA on the server itself. This is perhaps by design?

**Comment by brian-brazil** [comment]
I'd expect a different error in that case.

**Comment by raypettersen** [comment]
I'm also getting "certificate signed by unknown authority", even-though the CA is updated and I can successfully curl the site without the --insecure flag. How does the validation work?

**Comment by brian-brazil** [comment]
It's Go's standard validation.

**Comment by raypettersen** [comment]
I suspect something is missing here. We have to be able to orchestrate which certificates we trust and vice versa. For example, the exporter needs to pick-up the ca-certs bundle on the server it's running on for starts. Either automatically or through some sort of --include-ca-folder parameter.

My checks are failing miserably at the moment, and I am at a loss on how I can "help" go trust well known certificates that the server and any modern browser trusts.

**Comment by brian-brazil** [comment]
I'd suggest writing a trivial Go program to do a HTTP Get from the site. If that fails, then you can debug from there.

**Comment by raypettersen** [comment]
Thanks. I'll see what I can manage on my own. I'm fairly new to Go.

**Comment by pj42** [comment]
I needed support for a custom root ca certificate so I have added this functionality on my forked repo. See this commit:

https://github.com/pj42/blackbox_exporter/commit/cba4aea68a01d583da29560422f3640834fa497c

To use configure 'root_ca_pem_path' in your http module, for example:

  http_2xx:
    prober: http
    timeout: 5s
    http:
      root_ca_pem_path: "custom_root_ca.pem"

**Comment by pj42** [comment]
I found with my previous solution that only websites signed with that root ca worked, so all other ssl websites no longer worked. I have now updated it so you can add multiple ca cert files and this means you can include the public certificates as well. See:

https://github.com/pj42/blackbox_exporter/commit/db6ddba29c920b1ac640aba8f0ea01529f93e103

You can find the path to the relevant public certificate in the golang src code, for example see:

https://golang.org/src/crypto/x509/root_linux.go

I have also changed the config name to 'cacerts', so now to use it you can do:

    http_2xx:
      prober: http
      timeout: 5s
      http:
        cacerts: "/etc/ssl/certs/ca-certificates.crt,custom_root_ca.pem"

**Comment by pj42** [comment]
This can be achieved using the standard tls_config options supported in prometheus common code:

    http:
      tls_config:
        ca_file: "custom_root_ca.pem"

and you can have a different module for each ca_file you wish to support and if you want to support a standard ssl website using the public root certificates than use a module that doesn't specify a ca_file.
