### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by devosalain** [prometheus/blackbox_exporter#812]
Using the blackbox exporter on a local freebsd 13.0 shows no data except that the exporter is running.
Did I miss a configuration ? Or is it broken.

**Comment by willjp** [comment]
Also FreeBSD-13.0, I have this issue as well. 
I am not experienced enough with prometheus yet to have a good intution.
The exporter itself works fine from a manual probe.
```bash
xdg-open http://${YOUR_IP}:9115/probe?target=https://google.com&module=http_2xx&debug=true
```

The logs at the top indicate success, and you'll see the `probe_successful 1` near the bottom.
These metrics are not making it to prometheus for me either though (ex: queries).
I also tried running prometheus/blackbox_exporter temporarily as root without success.

**Comment by electron0zero** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
