### ISSUE TITLE
POST Data for URL monitors - Issue with URL Redirects

### ISSUE THREAD

**Issue by virasatkhan** [prometheus/blackbox_exporter#813]
Hi,

I have been trying hard to create a module inside my blackbox.yml file that will do a POST request to a URL along with the payLoad and then check a perticular content on the page. This is basically a URL Sequence monitor where I do following steps.
1) Login to a URL.
2) Do a content_check for a perticular text on the home page after login.

When I do this, and try do use below URL to test my probe(via below url). I see it is simply returning me the same metrices that I see while doing a basic GET module. My Expectation was this should have made a POST request like coded in my blackbox.yml file

http://server.domain.com:9115/probe?module=myCustomModule&target=https://myurl.com/login/portal

My configuration file is like this.

##################################START - blackbox.yml #######################################
`

`

modules:
  urlStatus:
    prober: http
    timeout: 15s
    http:
      valid_status_codes: [200]
      method: GET
      fail_if_ssl: false
      fail_if_not_ssl: false
      preferred_ip_protocol: ip4
      tls_config:
        insecure_skip_verify: true

  myCustomModule
    prober: http
    http:
      method: POST
      headers:
        Content-Type: 'application/json'
      body: '{
      "username":"myuser",
      "password":"mypwd",
      "ESS":"true"
      }'
      fail_if_ssl: false
      fail_if_not_ssl: false
      preferred_ip_protocol: ip4
      tls_config:
        insecure_skip_verify: true
      fail_if_body_not_matches_regexp:
        - "checkForContent"

`

`##################################END-` blackbox.yml #######################################

**Comment by virasatkhan** [comment]
I have gone through the sample blackbox.yml that provides info on POST method. However, when I do the same, I don't see it logged and most importantly, it just looks for 200 and succeeds. Infact the probe logger for my query over that module doesn't even indicates that it made a POST request.


  urlPost:
    prober: http
    timeout: 20s
    http:
      method: 'POST'
      headers:
        Content-Type: 'application/json'
      basic_auth:
        username: <usr>
        password: <pwd>
      body: "{}"
      fail_if_body_not_matches_regexp:
        - "Welcome"

**Comment by virasatkhan** [comment]
I was able to finally achieve this, just a matter of researching a bit more.
Howerver, the issue that I have right now is the url-redirects.

My targeturl=https://myprimaryurl.com/1111/portal 
is redirectign to another url = https://myprimaryurl.com/1111/applications/internalnav/navigation.do?var1=true
which intern to another url = https://myprimaryurl.com/1111/logonWithUID?ssoReturnUrl=https%3A%2F%2Fmyprimaryurl%2Ecom%2F1111%2Fapplications%2Finternalnav%2Fnavigation%2Edo%3Fvar1%3Dtrue



Below is the log


Logs for the probe:
ts=2021-08-05T16:05:08.210292809Z caller=main.go:320 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Beginning probe" probe=http timeout_seconds=10
ts=2021-08-05T16:05:08.210442079Z caller=http.go:335 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Resolving target address" ip_protocol=ip4
ts=2021-08-05T16:05:08.211408173Z caller=http.go:335 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Resolved target address" ip=xx.xx.xx.xx
ts=2021-08-05T16:05:08.211481938Z caller=client.go:251 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Making HTTP request" url=https://xx.xx.xx.xx/1111/portal host=myprimaryurl.com
ts=2021-08-05T16:05:08.515482634Z caller=client.go:492 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Received redirect" location="https://myprimaryurl.com/1111/applications/internalnav/navigation.do?var1=true"
ts=2021-08-05T16:05:08.515541013Z caller=client.go:251 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Making HTTP request" url="https://myprimaryurl.com/1111/applications/internalnav/navigation.do?ESS=true" host=
ts=2021-08-05T16:05:08.51555461Z caller=client.go:251 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Address does not match first address, not sending TLS ServerName" first=xx.xx.xx.xx address=myprimaryurl.com
ts=2021-08-05T16:05:08.754759867Z caller=client.go:492 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Received redirect" location="https://myprimaryurl.com/1111/logonWithUID?ssoReturnUrl=https%3A%2F%2Fmyprimaryurl%2Eadp%2Ecom%2F1111%2Fapplications%2Finternalnav%2Fnavigation%2Edo%3FESS%3Dtrue"
ts=2021-08-05T16:05:08.75486508Z caller=client.go:251 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Making HTTP request" url="https://myprimaryurl.com/1111/logonWithUID?ssoReturnUrl=https%3A%2F%2Fmyprimaryurl%2Ecom%2F1111%2Fapplications%2Finternalnav%2Fnavigation%2Edo%3FESS%3Dtrue" host=
ts=2021-08-05T16:05:08.754879297Z caller=client.go:251 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Address does not match first address, not sending TLS ServerName" first=xx.xx.xx.xx address=myprimaryurl.com
ts=2021-08-05T16:05:09.045279503Z caller=main.go:130 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Received HTTP response" status_code=200
ts=2021-08-05T16:05:09.04536982Z caller=http.go:469 module=externalURL target=https://myprimaryurl.com/1111/portal level=error msg="Header did not match regular expression" header=Set-Cookie regexp=(IMP_ID) value_count=1
ts=2021-08-05T16:05:09.225999278Z caller=main.go:130 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Response timings for roundtrip" roundtrip=0 start=2021-08-05T16:05:08.21157526Z dnsDone=2021-08-05T16:05:08.21157526Z connectDone=2021-08-05T16:05:08.240742589Z gotConn=2021-08-05T16:05:08.370187366Z responseStart=2021-08-05T16:05:08.515348666Z tlsStart=2021-08-05T16:05:08.240813168Z tlsDone=2021-08-05T16:05:08.370168237Z end=0001-01-01T00:00:00Z
ts=2021-08-05T16:05:09.226116026Z caller=main.go:130 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Response timings for roundtrip" roundtrip=1 start=2021-08-05T16:05:08.515669707Z dnsDone=2021-08-05T16:05:08.51692408Z connectDone=2021-08-05T16:05:08.538905096Z gotConn=2021-08-05T16:05:08.658119249Z responseStart=2021-08-05T16:05:08.754527302Z tlsStart=2021-08-05T16:05:08.538959145Z tlsDone=2021-08-05T16:05:08.65810609Z end=0001-01-01T00:00:00Z
ts=2021-08-05T16:05:09.226143876Z caller=main.go:130 module=externalURL target=https://myprimaryurl.com/1111/portal level=info msg="Response timings for roundtrip" roundtrip=2 start=2021-08-05T16:05:08.754959013Z dnsDone=2021-08-05T16:05:08.755943943Z connectDone=2021-08-05T16:05:08.775916767Z gotConn=2021-08-05T16:05:08.925648738Z responseStart=2021-08-05T16:05:09.045072369Z tlsStart=2021-08-05T16:05:08.776023818Z tlsDone=2021-08-05T16:05:08.92560681Z end=2021-08-05T16:05:09.225981205Z
ts=2021-08-05T16:05:09.226228984Z caller=main.go:320 module=externalURL target=https://myprimaryurl.com/1111/portal level=error msg="Probe failed" duration_seconds=1.015898016

**Comment by electron0zero** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
