### ISSUE TITLE
blackbox exporter certificate validation is showing expired for few of the websites even it is valid, but few works better which use same intermediate certificate

### ISSUE THREAD

**Issue by MrSunny-M** [prometheus/blackbox_exporter#815]
### Host operating system: output of `uname -a`
Linux server490 2.6.32-754.39.1.el6.x86_64 #1 SMP Fri Apr 9 08:06:22 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter --version`

blackbox_exporter, version 0.19.0 (branch: HEAD, revision: 5d575b88eb12c65720862e8ad2c5890ba33d1ed0)
  build user:       root@2b0258d5a55a
  build date:       20210510-12:56:44
  go version:       go1.16.4
  platform:         linux/amd64

### What is the blackbox.yml module config.
modules:
  http_prometheus:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: "ip4"
      valid_http_versions: ["HTTP/1.0", "HTTP/1.1", "HTTP/2.0"]
      method: GET
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
#        ca_file: /users/sm00007/project/blackBox/blackbox_exporter-0.19.0.linux-amd64/comodo-intermediate-bundle.crt
        insecure_skip_verify: true

### What is the prometheus.yml scrape config.

    static_configs:
    - targets: ['localhost:9090', 'localhost:9115']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_prometheus]
    static_configs:
      - targets:
 - https://abc.xyz.com
 - https://def.xyz.com
 - https://tuv.xyz.com
 relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.xx.xx.x:9115  # The blackbox exporter's real hostname:port.

### What logging output did you get from adding `&debug=true` to the probe URL?

ts=2021-08-04T23:43:02.338855662Z caller=main.go:130 module=http_prometheus target=xxx.xyz.com level=error msg="Final request was not over SSL"
ts=2021-08-04T23:43:02.338899208Z caller=main.go:320 module=http_prometheus target=xxx.xyz.com level=error msg="Probe failed" duration_seconds=0.009424533

### What did you do that produced an error?

http://10.xx.xx.x:9115/probe?target=xxx.xyz.com&module=http_prometheus&debug=true

### What did you expect to see?
SSL Validation

### What did you see instead?
Incorrect certificate expiry date from from 7587 dashboard

**Comment by kingbyteking** [comment]
I met the same issue, could dev team help?

**Comment by HamidEDD** [comment]
Hello, 

We are facing the same issue, here is a concrete example: 

`curl 'localhost:9115/probe?target=https://volume.compute.bhs5.cloud.ovh.net&module=http_2xx'`

Blackbox-exporter return  `1590835718` (May 30, 2020)  meaning that the certificate is already expired ... however it still valid till  `Mon, 24 Jan 2022 23:59:59 GMT`

same issue with : 
* https://cloudformation.bhs5.cloud.ovh.net
* https://workflow.bhs5.cloud.ovh.net
* https://volume.compute.de1.cloud.ovh.net
* ... and many others

**Comment by HamidEDD** [comment]
Hey @roidelapluie :)

Can you take a look to this issue please ? Thanks

**Comment by electron0zero** [comment]
@HamidEDD I tested ` volume.compute.bhs5.cloud.ovh.net` on ssllabs.com ([see results](https://www.ssllabs.com/ssltest/analyze.html?d=volume.compute.bhs5.cloud.ovh.net)), and it shows an expired certificate under Additional Certificates. 


same is true for `workflow.bhs5.cloud.ovh.net` ([test results](https://www.ssllabs.com/ssltest/analyze.html?d=workflow.bhs5.cloud.ovh.net)), and `cloudformation.bhs5.cloud.ovh.net` ([test results](https://www.ssllabs.com/ssltest/analyze.html?d=cloudformation.bhs5.cloud.ovh.net))

**Comment by electron0zero** [comment]
@Sunny-2772 can you test your targets using [ssllabs.com SSL server test](https://www.ssllabs.com/ssltest/index.html) and share results with us?

**Comment by avonwyss** [comment]
The issue is likely related to this: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

However, only one of the paths is invalid, the other is valid. I'm not sure what the expected output of the blackbox exporter should be in that case.
