### ISSUE TITLE
Static Configuration

### ISSUE THREAD

**Issue by lswith** [prometheus/blackbox_exporter#82]
I would like to have the blackbox_exporter support static configuration. This means that the configuration such as:
- target
- period 
- module + target combination

can be specified in the configuration file and the blackbox_exporter will add labels to the metrics and scrape the combinations periodically. This could be exposed over a /metrics endpoint alongside the /probe endpoint already exposed.

The reason for this feature is mainly to avoid complex and specific relabelling configuration in prometheus. Also, for our use case, the relabelling doesn't easily work when the blackbox_exporter is exposed as a service over consul.

**Comment by brian-brazil** [comment]
This is not the intended architecture of a Prometheus exporter. Scheduling and service discovery belong with Prometheus, not exporters.

You should run the blackbox exporter beside Prometheus.

**Comment by lswith** [comment]
This would simply be an additional feature alongside the current feature set.

**Comment by lswith** [comment]
Are all exporters intended to run alongside prometheus? Why is the blackbox-exporter a special case?

**Comment by brian-brazil** [comment]
What you request is an explicit non-goal of this exporter.

> Are all exporters intended to run alongside prometheus? Why is the blackbox-exporter a special case?

There's very few exporters in this category, currently only SNMP also fits. It's that way as it's impossible to run an exporter on something like a VIP.

**Comment by lswith** [comment]
Why can't the blackbox-exporter have its own explicit service discovery? It would allow it to be even more decoupled from Prometheus which I'm sure was the intent of making it a exporter in the first place.

**Comment by brian-brazil** [comment]
> Why can't the blackbox-exporter have its own explicit service discovery?

That is explicitly not the responsibility of an exporter. It's Prometheus's responsibility.

**Comment by lswith** [comment]
It just seems odd that we have extremely specific modules for very specific endpoints, and then pass in dynamic target configuration.

**Comment by brian-brazil** [comment]
That doesn't seem odd to me. You'll want to probe potentially thousands of targets with the same sort of probe.
