### ISSUE TITLE
Test HTTPS only resources

### ISSUE THREAD

**Issue by svenmueller** [prometheus/blackbox_exporter#83]
Hi,

We have some URLs which are only accessible using https. When using the given module `http_2xx`, the check fail since a request with http schema is sent (`getsockopt: connection refused" source="http.go:159"`).

How can i test HTTPS only resources?

Thx,
Sven

**Comment by brian-brazil** [comment]
That should work out of the box if you provide a https url. See https://www.robustperception.io/get-alerted-before-your-ssl-certificates-expire/ for example.

**Comment by svenmueller** [comment]
I added the scheme now in the URLs and it works as described. Thx a lot!
