### ISSUE TITLE
Security check issues

### ISSUE THREAD

**Issue by solo-yolo** [prometheus/blackbox_exporter#845]
Hello!

We were going to try to use the blackbox exporter for some periodic HTTP probing.

Before including it in our infrastructure, we've tried to perform some basic superficial analysis of the source code, particularly using the [gosec](https://github.com/securego/gosec) utility.

Results reveal there is a number of issues of different priority, here's the list of different types:
```
[HIGH]   G108 (CWE-200): Profiling endpoint is automatically exposed on /debug/pprof
[HIGH]   G404 (CWE-338): Use of weak random number generator (math/rand instead of crypto/rand)
[MEDIUM] G304 (CWE-22): Potential file inclusion via variable
[MEDIUM] G601 (CWE-118): Implicit memory aliasing in for loop
[MEDIUM] G307 (CWE-703): Deferring unsafe method "Close" on type "*os.File"
[LOW]    G104 (CWE-703): Errors unhandled.
```

Some of them, like the `Potential file inclusion via variable` or `Deferring unsafe method "Close" on type "*os.File"` are looks like idiomatic approach or intended behavior to me, although I'm not an expert in go by any means.
While others like `profiling endpoint` or `implicit memory aliasing` look concerning.

I'd appreciate it if someone from contributors can assess those to see which will need a fix or could be safely ignored.

Just in case, the scan results can be reviewed [here](https://gistcdn.githack.com/solo-yolo/b134100dea70faf34a05e4f7f544246f/raw/6ab9407c61455d9b152c87b6552cad7cf2118ee5/blackbox-exporter-gosec-scan-results.html).

**Comment by roidelapluie** [comment]
* CWE-200 is expected. We export pprof endpoints for operational reasons.
* CWE-338 the random number is not used for anything related to crytography, it is not needed to use a secure rng.
* CWE-22 the file is specified by the command line so it has to be a variable (seriously, why is this even flagged)
* CWE-118 seems to be a false positive
* CWE-703 G307 is harmless in our case
* CWE-703 G104 we never check errors for logging

**Comment by electron0zero** [comment]
closing due to age, and answer above.
