### ISSUE TITLE
Excuse me, is there a retry mechanism for detecting the http interface? For example, if the detection is unsuccessful after 3 times, an alarm is issued?

### ISSUE THREAD

**Issue by wwdz** [prometheus/blackbox_exporter#853]
Excuse me, is there a retry mechanism for detecting the http interface? For example, if the detection is unsuccessful after 3 times, an alarm is issued?

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
