### ISSUE TITLE
Publish container images with git sha

### ISSUE THREAD

**Issue by mlazowik** [prometheus/blackbox_exporter#874]
This would allow to use prerelease versions without having to use the `master` tag which moves around.

**Comment by SuperQ** [comment]
This would be a discussion for the Prometheus developers list.

**Comment by mlazowik** [comment]
Ack, thanks

**Comment by mlazowik** [comment]
For posterity: discussion moved to https://groups.google.com/g/prometheus-users/c/WNb3Aq55KKc
