### ISSUE TITLE
icmp probe 0 seconds response/duration

### ISSUE THREAD

**Issue by bygmakavi** [prometheus/blackbox_exporter#880]
Im trying to setup a ping monitoring setup using prometheus and blackbox_exporter
Most if the icmp results look find but once every X intervals results comes back as 0 seconds/milliseconds
It's random which ip resturns with 0 seconds, and at random intervals. 

i can't replicate a 0 milliseconds response using other ping tools, or any packetloss

### Host operating system: output of `uname -a`
Windows 2016 - 64bit

### blackbox_exporter version: output of `blackbox_exporter --version`
blackbox_exporter, version 0.19.0 (branch: HEAD, revision: 5d575b88eb12c65720862e8ad2c5890ba33d1ed0)
  build user:       root@39fb15744b98
  build date:       20210510-13:02:55
  go version:       go1.16.4
  platform:         windows/amd64

### What is the blackbox.yml module config.
modules:
  icmp:
    prober: icmp
    timeout: 10s
    icmp:
      preferred_ip_protocol: "ip4"

### What is the prometheus.yml scrape config.
global:
  scrape_interval:     30s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'adm-it'

remote_write:
  - url: "http://X.X.X.X:8086/api/v1/prom/write?db=prometheus"

remote_read:
  - url: "http://X.X.X.X:8086/api/v1/prom/read?db=prometheus"

scrape_configs:
  - job_name: 'prometheus'

    #scrape_interval: 60s

    static_configs:
      - targets: ['localhost:9090']
        labels:

  - job_name:       'node'

    scrape_interval: 30s

    static_configs:
      - targets: ['X.X.X.X:9182']
        labels:
          group: 'production'
        

  - job_name: 'blackbox_hq'
    scrape_interval: 30s  
    metrics_path: /probe
    params:
      module: [icmp]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
		- x.x.x.x (here i have 130 ip's, and 4 dns names)
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: X.X.X.X:9115  # The blackbox exporter's real hostname:port.     

### What logging output did you get from adding `&debug=true` to the probe URL?
Nothing additionally

### What logging output did you get from adding debug to the probe Console?
ts=2022-02-15T08:39:34.666Z caller=main.go:180 module=icmp target=X.X.X.X level=debug msg="Beginning probe" probe=icmp timeout_seconds=9.5
ts=2022-02-15T08:39:34.666Z caller=main.go:180 module=icmp target=X.X.X.X level=debug msg="Resolving target address" ip_protocol=ip4
ts=2022-02-15T08:39:34.666Z caller=main.go:180 module=icmp target=X.X.X.X level=debug msg="Resolved target address" ip=X.X.X.X
ts=2022-02-15T08:39:34.666Z caller=main.go:180 module=icmp target=X.X.X.X level=debug msg="Creating socket"
ts=2022-02-15T08:39:34.666Z caller=main.go:180 module=icmp target=X.X.X.X level=debug msg="Failed to set Control Message for retrieving TTL" err="not implemented on windows/amd64"
ts=2022-02-15T08:39:34.666Z caller=main.go:180 module=icmp target=X.X.X.X level=debug msg="Creating ICMP packet" seq=35568 id=5896
ts=2022-02-15T08:39:34.666Z caller=main.go:180 module=icmp target=X.X.X.X level=debug msg="Writing out packet"
ts=2022-02-15T08:39:34.666Z caller=main.go:180 module=icmp target=X.X.X.X level=debug msg="Waiting for reply packets"
ts=2022-02-15T08:39:34.666Z caller=main.go:180 module=icmp target=X.X.X.X level=debug msg="Cannot get TTL from the received packet. 'probe_icmp_reply_hop_limit' will be missing."
ts=2022-02-15T08:39:34.666Z caller=main.go:180 module=icmp target=X.X.X.X level=debug msg="Found matching reply packet"
ts=2022-02-15T08:39:34.666Z caller=main.go:180 module=icmp target=X.X.X.X level=debug msg="Probe succeeded" duration_seconds=0

### What did you do that produced an error?
Used the ICMP probe with 130+ instances

### What did you expect to see?
Milliseconds

### What did you see instead?
Results with 0 seconds as duration

**Comment by electron0zero** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
