### ISSUE TITLE
Can you include debug output?

### ISSUE THREAD

**Issue by guipichina** [prometheus/blackbox_exporter#897]
Which is the exact comand for &debug=true with the curl comand¿?
_Originally posted by @brian-brazil in https://github.com/prometheus/blackbox_exporter/issues/258#issuecomment-342736804_

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
