### ISSUE TITLE
probe_succes 0 when the http is up

### ISSUE THREAD

**Issue by guipichina** [prometheus/blackbox_exporter#898]
I've been searching for a couples of weeks how to resolve this problem but i can't manage to solve it. The problem is the same as many people, probe_success returns 0, probe_http_status_code returns 0 as well, etc...

The answer to this problem is the protocol, i have tried to change it form ipv6 to ipv4 but it aint working, anybody has any ideas?

**Comment by electron0zero** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by JeffDeans** [comment]
I had a similar problem and was stuck...

**Comment by zcharym** [comment]
if anyone also loaded blackbox_exporter using the `docker-compose`. Instead of mapping ports, configure the `network_mode: "host"`.
