### ISSUE TITLE
Blocking external access to Blackbox

### ISSUE THREAD

**Issue by callahan22** [prometheus/blackbox_exporter#908]
I was going to add this as a feature request but it's not really one as I have no suggestions as to how to resolve, it's also not a bug but I have nowhere else to post so apologies.

I've just spun up a docker stack with prom, grafana, blackbox-exporter and nginx running as the reverse proxy for them all. Config all done and everything works. I'm using the nginx reverse proxy as the route into the containers, it means that I can forgo the need to expose the containers to the outside LAN. All name resolution is handled by the container names inside the docker stack. The problem is that if I remove the "ports" section of the config for blackbox, it fails. If I add it back in as:
```
    ports:
      - "9115"
```
blackbox-exporter will spin up and dynamically generate a port:
```
a35e173fa60d   bitnami/blackbox-exporter   "/opt/bitnami/blackb…"   10 hours ago   Up About an hour   0.0.0.0:49153->9115/tcp, :::49153->9115/tcp  blackbox
```
This makes it accessible from the outside on port 49153. Only a matter of time before one of our Security tools finds that and I'm forced to remove.

I'm aware that I can use the web-config file to both add basic auth and assign it a cert. It seems a huge overkill though when the only thing I'm trying to do is to stop the container from listening on the outside.

I'd like all containers to only be access able through the reverse proxy. Is there a simpler, cleaner way around this or am I going to have to just add a cert and switch on basic auth in this container?

Guess I could use the firewall and set up rules but again, seems overkill!

Thanks for any suggestions.

### What is the expected behavior?

I'd like to be able to stop blackbox from being accessible from the LAN.

### What do you see instead?

Blackbox just spins up a dynamic port number and listens on 0.0.0.0.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
