### ISSUE TITLE
The output for version flag is printed on stderr

### ISSUE THREAD

**Issue by nkn1111** [prometheus/blackbox_exporter#912]
Was facing an issue with the version check for the exporter. But found a similar issue on node_exporter issues which is already fixed. Linking the same here https://github.com/prometheus/node_exporter/issues/1271

Can we do the same fix here?

### What did you do that produced an error?
Register the version output via ansible and display it using debug.
"cmd": [
            "/usr/local/bin/blackbox_exporter",
            "--version"
        ]

### What did you expect to see?
"stdout": "blackbox_exporter, version 0.20.0

### What did you see instead?
"stderr": "blackbox_exporter, version 0.20.0

**Comment by nkn1111** [comment]
Thank you. I might have found a workaround for my issue on ansible by adding multiple conditions to check both stdout and stderr. Since the Prometheus and other subsidiaries of Prometheus are showing the version output on stdout, It makes sense to have the same in here as well. Can you consider this improvement in a future release?

**Comment by roidelapluie** [comment]
Yes, are you willing to contribute this change to the project? Thanks!

**Comment by roidelapluie** [comment]
> But it's worth nothing that this is NOT what Prometheus (or promtool, etc) does.


It was changed in Prometheus: https://github.com/prometheus/prometheus/pull/8542 and per dev summit, we want it everywhere.

**Comment by nkn1111** [comment]
Hey! I missed this update. TBH I don't have prior knowledge in go lang. To save you some time, it's better for someone familiar with the exporter code to raise a PR. TIA.

**Comment by nkn1111** [comment]
Thank you so much @mem @roidelapluie
