### ISSUE TITLE
smtp_starttls cannot work well

### ISSUE THREAD

**Issue by gnnx0425** [prometheus/blackbox_exporter#913]
Hi,

I'm using module smtp_starttls to implement Nagios check_smtp.

- job_name: check_smtp
        metrics_path: /probe
        params:
          module: [smtp_starttls]
        static_configs:
          - targets:
              - 10.1.1.1:25
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: prometheus-blackbox-exporter:9115

smtp_starttls:
        prober: tcp
        timeout: 5s
        tcp:
          query_response:
            - expect: "^220 ([^ ]+) ESMTP (.+)$"
            - send: "EHLO prober\r"
            - expect: "^250-STARTTLS"
            - send: "STARTTLS\r"
            - expect: "^220"
            - starttls: true
            - send: "EHLO prober\r"
            - expect: "^250-AUTH"
            - send: "QUIT\r"

Checked on blackbox UI, the status of smtp_starttls is failed.
when curling https://prometheus-blackbox-exporter:9115/probe?module=smtp_starttls&target=10.1.1.1, returned a whole HTML page which includes all the prometheus blackbox checks.

**Comment by dswarbrick** [comment]
Please post the log output from running the probe with `&debug=true` in the URL.

Since I have a working SMTP STARTTLS probe based on your config, I suspect you are probably running into a certification validation error.

**Comment by electron0zero** [comment]
as reported above, users are able to run SMTP STARTTLS check.

also see this example config for reference: https://github.com/prometheus/blackbox_exporter/blob/9cc59c38aa1ee9235a88568b28257951f33235bd/example.yml#L120-L133 

For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
