### ISSUE TITLE
Clarify Docs on configuration

### ISSUE THREAD

**Issue by brasilikum** [prometheus/blackbox_exporter#93]
From the README.md it is not clear to me which configurations are needed and which are optional.

1. There is a `blackbox.yaml` configuration file for the exporter.
2. There is a section in the prometheus configuration.
3. You can visit `http://localhost:9115/probe?target=google.com&module=http_2xx`.

Could someone please explain how these interact? 
Do I need the `relable configs` if I specified the probes in the blackbox.yaml?
Do I need `backbox.yaml` if I pass the targets as parameters in the http call?

I will use the answers to try to clarify the docs in that regard.

**Comment by brian-brazil** [comment]
You need everything as described in the readme.

**Comment by brasilikum** [comment]
So I have to specify the probe target in blackbox.yaml `headers: host:` as well as in prometheus.yaml `static_config: targets:`, right?

I guess I am just confused because in the blackbox.yaml the target is `vhost.example.com` and in the prometheus.yaml the target is `prometheus.io`.

**Comment by brian-brazil** [comment]
The header is just a header and is always the same for a module, it's not related to the target.
