### ISSUE TITLE
Endpoint Target shows UP in blackbox but alert shows DOWN and Firing

### ISSUE THREAD

**Issue by DareLekan** [prometheus/blackbox_exporter#931]
Good day. I am facing a similar issue here. I have alertmanager and blackbox configured. However, both shows different information for same endpoint. What am I doing wrong. Please help.

I have attached screenshot to help in explaining my pain point
![alert probe 2](https://user-images.githubusercontent.com/77133189/174429262-13d2fd6f-9710-4192-af3e-c4d001e85f0c.JPG)
![alert probe](https://user-images.githubusercontent.com/77133189/174429263-5b02288d-0bab-4206-9c3c-8b74389e04c2.JPG)
![blackbox probe](https://user-images.githubusercontent.com/77133189/174429264-b53c36ee-5d40-4463-9c56-16c1a0245504.JPG)
![prometheus config 1](https://user-images.githubusercontent.com/77133189/174429265-a8714efc-a593-457c-9017-add8e583a9e3.JPG)
![prometheus config 2](https://user-images.githubusercontent.com/77133189/174429266-4e748420-1fab-41a9-8169-aa6d1c2d0202.JPG)
![prometheus UI alertmanagere](https://user-images.githubusercontent.com/77133189/174429267-93b83b24-5f12-46ac-acf7-363d1432db3f.JPG)
![prometheus UI alertmanagere22](https://user-images.githubusercontent.com/77133189/174429268-e1261039-c6f1-47b6-8fcf-36154aa9f9b8.JPG)
![prometheus UI alertmanagere33](https://user-images.githubusercontent.com/77133189/174429270-73d129bb-e351-49e3-a168-21f728f2b43f.JPG)
![prometheus UI alertmanagere44](https://user-images.githubusercontent.com/77133189/174429272-873a7ef6-b5cb-449e-ab53-87ae7b13a6cf.JPG)
![prometheus UI blackbox](https://user-images.githubusercontent.com/77133189/174429273-17c92d73-08a2-4519-aff5-1e7fbb263115.JPG)

**Comment by mem** [comment]
I see...

The "UP" value in the state column refers to the Prometheus scrape target, not the target of the blackbox module (the next column).

From the Prometheus docs:

> up{job="<job-name>", instance="<instance-id>"}: 1 if the instance is healthy, i.e. reachable, or 0 if the scrape failed.

https://prometheus.io/docs/concepts/jobs_instances/

It means that Prometheus is able to scrape the target and obtain metrics.

**Comment by Excpt0r** [comment]
Hi @mem 
I guess I have a similar issue:
I would like the prometheus "up" metric to fail, when blackbox-exporter cannot reach a tcp target.
Is it possible to configure blackbox exporter to return failure (i.e. http 5xx) to prometheus, when a target check failed?

Thanks for your help

**Comment by hasanbozok** [comment]
Any update on this problem? I am facing the same problem.

**Comment by DareLekan** [comment]
I did not hear the last in the issue. Had to use a make-shift tool oending
when I get a solution.

**Comment by justbuilding** [comment]
prometheus的target显示up状态，只是代表prometheus能正常和blackbox，kubelet等等Prometheus scrape target组件交互，不代表blackbox写的tpc监控等是正常的，得看alert有没有告警，所以如上属于正常现象

**Comment by electron0zero** [comment]
going to close this issue for now because community channels are more suitable for this discussion.

For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
