### ISSUE TITLE
Getting constant syslog messages at level=debug even when ARGS set to --log.level=info or --log.level=error

### ISSUE THREAD

**Issue by therealcodlord** [prometheus/blackbox_exporter#940]
Today I found my syslog was being filled with constant level=debug messages from prometheus-blackbox-exporter and I can't seem to stop these messages even after attempting to set the process ARGS to --log.level=info or --log.level=error  

A few example syslog messages:
```
Jun 29 16:50:40 server1 prometheus-blackbox-exporter[2128509]: ts=2022-06-29T15:50:40.060Z caller=main.go:180 module=tcp_connect target=172.16.0.102:8000 level=debug msg="Dialing TCP without TLS"
Jun 29 16:50:40 server1 prometheus-blackbox-exporter[2128509]: ts=2022-06-29T15:50:40.061Z caller=main.go:180 module=tcp_connect target=172.16.0.102:8000 level=debug msg="Successfully dialed"
Jun 29 16:50:40 server1 prometheus-blackbox-exporter[2128509]: ts=2022-06-29T15:50:40.061Z caller=main.go:180 module=tcp_connect target=172.16.0.102:8000 level=debug msg="Probe succeeded" duration_seconds=0.001227543
```

And the service status shows that the ARGS are set to --log.level=info:
```
$ service prometheus-blackbox-exporter status
● prometheus-blackbox-exporter.service - Blackbox exporter for Prometheus
     Loaded: loaded (/lib/systemd/system/prometheus-blackbox-exporter.service; enabled; vendor preset: e>
     Active: active (running) since Wed 2022-06-29 16:37:32 BST; 16min ago
       Docs: https://prometheus.io/docs/introduction/overview/
             man:prometheus-blackbox-exporter(1)
   Main PID: 2128509 (prometheus-blac)
      Tasks: 10 (limit: 19046)
     Memory: 12.2M
        CPU: 6.795s
     CGroup: /system.slice/prometheus-blackbox-exporter.service
             └─2128509 /usr/bin/prometheus-blackbox-exporter --log.level=info --config.file /etc/prometh>
```

I know I am not using the latest version, but I am using the latest packaged version for Ubuntu 22.04 LTS

### Host operating system: output of `uname -a`
Linux server1 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter --version`
prometheus-blackbox-exporter --version
blackbox_exporter, version 0.19.0 (branch: debian/sid, revision: 0.19.0-1)
  build user:       team+pkg-go@tracker.debian.org
  build date:       20211130-22:21:56
  go version:       go1.17.3
  platform:         linux/amd64

### What is the blackbox.yml module config.
I don't think this is relevant to my issue (nothing in there related to logging or log levels anyway).

### What is the prometheus.yml scrape config.
I don't think this is relevant to my issue (nothing in there related to logging or log levels anyway).

**Comment by roidelapluie** [comment]
Please raise this issue with the debian team, it's unrelated to this repository, but is from the debian package.

Thanks!

**Comment by therealcodlord** [comment]
Thanks, I went there and I can see it's an already reported bug, so for anyone else searching here, see [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010054) instead.
