### ISSUE TITLE
Pulling prom/blackbox-exporter:master  and running locally is causing config file error

### ISSUE THREAD

**Issue by elliottb303** [prometheus/blackbox_exporter#958]
### Host operating system: output of `uname -a`
Darwin M 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64

### What did you do that produced an error?

Following the readme instructions to run BB container locally started giving error apparently with latest build. ( prom/blackbox-exporter:master  )

❯ docker run -it -p 9115:9115 --name blackbox_exporter_wtf -v `pwd`:/config prom/blackbox-exporter:master --config.file=/config/blackbox.yml

ts=2022-08-15T18:38:27.705Z caller=main.go:255 level=info msg="Starting blackbox_exporter" version="(version=0.21.0-rc.0, branch=master, revision=6b655cdaf8727ff9bc301bfd50270c373b776085)"
ts=2022-08-15T18:38:27.705Z caller=main.go:256 level=info build_context="(go=go1.18.1, user=root@230c784520f0, date=20220510-12:07:23)"
ts=2022-08-15T18:38:27.711Z caller=main.go:259 level=error msg="Error loading config" err="error parsing config file: yaml: unmarshal errors:\n  line 49: field ttl not found in type config.plain"
❯ docker run -it -p 9115:9115 --name blackbox_exporter_wtf -v `pwd`:/config prom/blackbox-exporter:v0.21.1 --config.file=/config/blackbox.yml

### What did you expect to see? ( prom/blackbox-exporter:v0.21.1 ) I specified previous container and the issue does not occur.:

> ❯ docker run -it -p 9115:9115 --name blackbox_exporter_ -v `pwd`:/config prom/blackbox-exporter:v0.21.1 --config.file=/config/blackbox.yml

ts=2022-08-15T18:48:24.222Z caller=main.go:255 level=info msg="Starting blackbox_exporter" version="(version=0.21.1, branch=HEAD, revision=e0d5e4453c54b6e508531a761131d7f21007783c)"
ts=2022-08-15T18:48:24.223Z caller=main.go:256 level=info build_context="(go=go1.18.3, user=root@6e3666c7d63f, date=20220617-12:22:49)"
ts=2022-08-15T18:48:24.229Z caller=main.go:268 level=info msg="Loaded config file"
ts=2022-08-15T18:48:24.230Z caller=main.go:416 level=info msg="Listening on address" address=:9115
ts=2022-08-15T18:48:24.230Z caller=tls_config.go:195 level=info msg="TLS is disabled." http2=false

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
