### ISSUE TITLE
Let's Encrypt certificates are invalid by default.

### ISSUE THREAD

**Issue by dragonsmith** [prometheus/blackbox_exporter#97]
Hello,

I'm running blackbox exporter v0.3.0 official docker image.

I've just noticed that the popular certificates issued by Let's Encrypt are considered as `x509: certificate signed by unknown authority`.

What do you think, maybe it is possible to add acme's root CA certificate to the image by default?

Thank you!

**Comment by brian-brazil** [comment]
We're just using whatever the OS provides as certs. If that's not working for you, you should take it up with upstream.

**Comment by SuperQ** [comment]
We are upstream for the docker image.

Is this still a problem with v0.4.0?

**Comment by srt** [comment]
Yes, it is still a problem with the current docker image and blackbox_exporter, version 0.4.0.

**Comment by andrewhowdencom** [comment]
Conversely, I use Lets Encrypt quite a lot and I haven't seen any issues with the Lets Encrypt certificates! Happy to help diagnose.

Certificates aren't mounted in or anything, and image is `prom/blackbox-exporter:v0.3.0`

**Comment by strangeman** [comment]
+1 to @andrewhowdencom 
I use LE certs and Blackbox detects them as valid. Maybe you're don't have chain/CA certs (on Blackbox or on target host)?

**Comment by srt** [comment]
I no longer experience this issue, seems like it was a local problem.

**Comment by SuperQ** [comment]
Thanks for following up.
