### ISSUE TITLE
Can't test for redirect status code

### ISSUE THREAD

**Issue by Jean-Daniel** [prometheus/blackbox_exporter#98]
I'd like to make sure a monitored web server properly responds with a redirect code 301. 

As far as I know, the actual http module don't allow that. If I test with no_follow_redirects false, I got the final page status code (200 in my case) and not the redirect status.

If i try with no_follow_redirects true, it immediately fails, even if I put 301 in the valid status code.

Did I miss something ?

**Comment by brian-brazil** [comment]
The no follow redirects should work for you. Can you share your module config?

**Comment by Jean-Daniel** [comment]
You're right. After reading your reply I double check and found that the issue was elsewhere.
I did had a non empty 'fail_if_matches_regexp', and that test fails if the body is empty (which is a behavior I didn't expect).
