### ISSUE TITLE
how to set scrape_interval for blackbox_exporter?

### ISSUE THREAD

**Issue by celery-xqq** [prometheus/blackbox_exporter#988]
###

**Comment by electron0zero** [comment]
This seems like a config issue in PromQL query, [please read up for more](https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/)


For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
